import { useEffect, useRef } from "react";
import { usePersistFn } from "./usePersistFn";

type SupportedElement = HTMLInputElement | HTMLTextAreaElement;
type Timer = ReturnType<typeof setTimeout>;

export interface UseCompositionReturn<
  T extends SupportedElement = HTMLInputElement,
> {
  onCompositionStart: React.CompositionEventHandler<T>;
  onCompositionEnd: React.CompositionEventHandler<T>;
  onKeyDown: React.KeyboardEventHandler<T>;
  isComposing: () => boolean;
}

export interface UseCompositionOptions<
  T extends SupportedElement = HTMLInputElement,
> {
  onKeyDown?: React.KeyboardEventHandler<T>;
  onCompositionStart?: React.CompositionEventHandler<T>;
  onCompositionEnd?: React.CompositionEventHandler<T>;

  /**
   * Prevent event propagation for these keys while IME is composing.
   *
   * Default:
   * - Escape
   * - Enter (except Shift+Enter)
   */
  blockKeys?: Array<"Enter" | "Escape">;

  /**
   * If true, preventDefault() in addition to stopPropagation().
   *
   * Default: false
   */
  preventDefault?: boolean;
}

export function useComposition<
  T extends SupportedElement = HTMLInputElement,
>(
  options: UseCompositionOptions<T> = {},
): UseCompositionReturn<T> {
  const {
    onKeyDown: originalOnKeyDown,
    onCompositionStart: originalOnCompositionStart,
    onCompositionEnd: originalOnCompositionEnd,
    blockKeys = ["Enter", "Escape"],
    preventDefault = false,
  } = options;

  /**
   * The authoritative internal IME state.
   */
  const composingRef = useRef(false);

  /**
   * Safari can dispatch compositionend before the final keydown.
   *
   * We keep a very short-lived state so that the final Enter/Escape
   * generated by IME is still treated as part of the composition cycle.
   */
  const pendingCompositionEndRef = useRef(false);

  const cleanupTimerRef = useRef<Timer | null>(null);

  /**
   * Avoid recreating Set on every keydown.
   */
  const blockKeysRef = useRef(blockKeys);

  useEffect(() => {
    blockKeysRef.current = blockKeys;
  }, [blockKeys]);

  /**
   * Keep the latest callback references without making event handlers
   * depend on callback identity.
   */
  const onKeyDownCallback = usePersistFn(originalOnKeyDown);
  const onCompositionStartCallback = usePersistFn(
    originalOnCompositionStart,
  );
  const onCompositionEndCallback = usePersistFn(originalOnCompositionEnd);

  /**
   * Cleanup on unmount.
   */
  useEffect(() => {
    return () => {
      if (cleanupTimerRef.current !== null) {
        clearTimeout(cleanupTimerRef.current);
        cleanupTimerRef.current = null;
      }

      composingRef.current = false;
      pendingCompositionEndRef.current = false;
    };
  }, []);

  const onCompositionStart = usePersistFn(
    (event: React.CompositionEvent<T>) => {
      if (cleanupTimerRef.current !== null) {
        clearTimeout(cleanupTimerRef.current);
        cleanupTimerRef.current = null;
      }

      composingRef.current = true;
      pendingCompositionEndRef.current = false;

      onCompositionStartCallback?.(event);
    },
  );

  const onCompositionEnd = usePersistFn(
    (event: React.CompositionEvent<T>) => {
      /**
       * Do not immediately consider the IME cycle completely finished.
       *
       * Safari may emit:
       *
       * compositionend
       * keydown(Enter)
       *
       * while Chromium/Firefox commonly emit the events in the opposite
       * order.
       */
      composingRef.current = false;
      pendingCompositionEndRef.current = true;

      onCompositionEndCallback?.(event);

      if (cleanupTimerRef.current !== null) {
        clearTimeout(cleanupTimerRef.current);
      }

      /**
       * One macrotask is enough to bridge Safari's event ordering
       * without the previous nested setTimeout approach.
       */
      cleanupTimerRef.current = setTimeout(() => {
        pendingCompositionEndRef.current = false;
        cleanupTimerRef.current = null;
      }, 0);
    },
  );

  const onKeyDown = usePersistFn(
    (event: React.KeyboardEvent<T>) => {
      const nativeEvent = event.nativeEvent as KeyboardEvent;

      /**
       * Prefer the browser's native IME signal whenever available.
       *
       * React's `nativeEvent.isComposing` maps to the browser's
       * KeyboardEvent.isComposing.
       */
      const nativeIsComposing = nativeEvent.isComposing === true;

      const composing =
        composingRef.current ||
        nativeIsComposing ||
        pendingCompositionEndRef.current;

      if (composing) {
        const isEscape =
          event.key === "Escape" &&
          blockKeysRef.current.includes("Escape");

        const isEnter =
          event.key === "Enter" &&
          !event.shiftKey &&
          blockKeysRef.current.includes("Enter");

        if (isEscape || isEnter) {
          /**
           * Prevent parent handlers such as:
           *
           * - form submit
           * - modal close
           * - command execution
           * - chat send
           */
          event.stopPropagation();

          if (preventDefault) {
            event.preventDefault();
          }

          return;
        }
      }

      onKeyDownCallback?.(event);
    },
  );

  const isComposing = usePersistFn(() => {
    return composingRef.current;
  });

  return {
    onCompositionStart,
    onCompositionEnd,
    onKeyDown,
    isComposing,
  };
}