import { useMemo, useState } from "react";
import { Link } from "wouter";
import { ArrowLeft, CalendarDays, CheckCircle2, Compass, DraftingCompass, FileText, LandPlot, Mail, MapPin, Menu, Phone, Rocket, Ruler, Send, ShieldCheck, Sparkles, Target, TrendingUp, Users, X, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { siteConfig } from "@/lib/siteConfig";

const businessCapabilities = [
  { title: "الهندسة والمساحة", description: "من رفع الموقع والمخططات إلى التصميم المعماري والمراجعة الفنية. نحوّل رؤيتك إلى مخططات قابلة للتنفيذ بدقة مهنية عالية.", icon: DraftingCompass },
  { title: "المقاولات والإشراف", description: "تنسيق احتياجات المشروع ومتابعة نطاقات التنفيذ. إشراف ميداني يضمن التزام المقاولين بالمواصفات والجدول الزمني.", icon: Ruler },
  { title: "الاستشارات التقنية", description: "حلول تقنية مخصصة تساعد أعمالك على digitale تحول رقمي فعّال. من أتمتة العمليات إلى بناء الأنظمة الذكية.", icon: Sparkles },
  { title: "التحول الرقمي", description: "مساندة رقمية شاملة ترفع جودة تجربة العملاء وتُحسّن الكفاءة التشغيلية. مواقع، تطبيقات، وأنظمة إدارة محتوى.", icon: Sparkles },
  { title: "الخدمات المكتبية", description: "إدارة مستندات، أرشفة ذكية، تقارير مالية، ومساندة إدارية. نخففعبءك التشغيلي لتتركز على ما يُنمو أعمالك.", icon: FileText },
  { title: "التصميم والهوية البصرية", description: "تصاميم احترافية تعكس هويتك وتعزز حضورك في السوق. من الشعارات إلى المواد التسويقية والمواقع الإلكترونية.", icon: DraftingCompass },
  { title: "التوريد والمتابعة", description: "تنسيق احتياجات التوريد وربطها بمتطلبات المشروع. ضمان جودة المنتجات والالتزام بالمواصفات والمواعيد.", icon: CheckCircle2 },
];

const fallbackServices = [
  { category: "engineering", title: "رفع مساحي ومخططات أراضٍ", description: "قياسات ميدانية بدقة عالية، إعداد مخططات الأراضي بالمواصفات الدولية، وتوثيق البيانات اللازمة لاتخاذ القرار العقاري الصحيح.", icon: "ruler" },
  { category: "engineering", title: "تصاميم معمارية وهندسية", description: "حلول تصميم تجمع بين الجمال والوظيفة. تصاميم تراعي البيئة المحلية والاشتراطات الفنية واحتياجات المستخدم.", icon: "drafting" },
  { category: "engineering", title: "استشارات هندسية متخصصة", description: "رأي مهني من مهندسين ذوي خبرة 15+ سنة في التخطيط والتنفيذ ومراجعة المخططات. نحمّلك من التصميم إلى التنفيذ.", icon: "compass" },
  { category: "realEstate", title: "تقييم وتثمين العقارات", description: "قراءة مهنية معمّقة لموقع العقار ووضعه ومؤشرات السوق. تقييم يدعم قرارات البيع والشراء والرهن بثقة.", icon: "land" },
  { category: "realEstate", title: "استشارات عقارية شاملة", description: "مساعدة عملية في اختيار الفرص، دراسة الجدوى التفصيلية، وتقييم المخاطر العقارية. من البحث إلى الفحص القانوني.", icon: "map" },
  { category: "consulting", title: "تطوير مؤسسي وإداري", description: "بناء الهياكل والإجراءات وتحسين الأداء المؤسسي. نحوّل الفوضى العملياتية إلى نظم واضحة وقابلة للقياس والتحسين.", icon: "file" },
];

const fallbackTeam = [
  { name: "فريق الخبراء الهندسي", title: "مهندسون واستشاريون", specialty: "المخططات والمساحة والتصميم", experienceYears: 15, bio: "خبرات متراكمة تجمع بين المعرفة الميدانية والرؤية العملية." },
  { name: "فريق الاستشارات", title: "مستشارون مؤسسيون وإداريون", specialty: "الأنظمة وتطوير الأداء", experienceYears: 12, bio: "نساعد المؤسسات على تحويل التحديات إلى نظم واضحة ونتائج قابلة للقياس." },
  { name: "الفريق العقاري", title: "خبراء عقار وتثمين", specialty: "الفرص والتقييم العقاري", experienceYears: 10, bio: "قراءة متوازنة للسوق والموقع والاحتياج لاتخاذ قرار عقاري أكثر ثقة." },
];

const fallbackProperties = [
  { title: "أرض سكنية مميزة", type: "أرض للبيع", location: "موقع قابل للتخصيص", size: "مساحة قابلة للتحديث", note: "استفسار وتقييم أولي متاح" },
  { title: "فرصة عقارية واعدة", type: "فرصة استثمارية", location: "بيانات الموقع عند الطلب", size: "تفاصيل عبر المستشار", note: "دراسة عقارية مهنية" },
  { title: "عقار للاستخدام التجاري", type: "عقار تجاري", location: "تواصل لمعرفة التفاصيل", size: "تقييم حسب الحالة", note: "تثمين واستشارة" },
];

const fallbackProjects = [
  { title: "مخطط أرض سكنية", category: "هندسي", location: "مشروع سكني", description: "إعداد تصور أولي وتوزيع وظيفي لمخطط أرض سكنية." },
  { title: "دراسة فرصة عقارية", category: "عقاري", location: "تحليل موقع", description: "تقييم موقع وفرصة استثمارية من منظور فني وعقاري." },
  { title: "تطوير إجراءات مؤسسة", category: "استشاري", location: "تطوير إداري", description: "إعادة تنظيم الإجراءات وبناء مسار عمل أوضح للفريق." },
];

const iconMap: Record<string, any> = { ruler: LandPlot, drafting: DraftingCompass, compass: Compass, land: LandPlot, map: MapPin, file: FileText, sparkles: Sparkles };

function SectionHeading({ eyebrow, title, body }: { eyebrow: string; title: string; body: string }) {
  return <div className="mb-10 max-w-2xl"><div className="mb-3 text-sm font-bold tracking-[0.18em] text-copper">{eyebrow}</div><h2 className="font-display text-3xl font-bold leading-tight text-ink md:text-5xl">{title}</h2><p className="mt-4 text-base leading-8 text-slate-600">{body}</p></div>;
}

function RequestForm({ serviceType, onDone }: { serviceType: string; onDone: () => void }) {
  const mutation = trpc.requests.service.useMutation({ onSuccess: () => { toast.success(`تم استلام طلبك — سيتواصل معك فريق ${siteConfig.brand.englishName} قريباً.`); onDone(); }, onError: () => toast.error("تعذر إرسال الطلب — تحقق من البيانات ثم حاول مرة أخرى.") });
  const [form, setForm] = useState({ name: "", phone: "", email: "", details: "" });
  return <form className="space-y-4" onSubmit={(e) => { e.preventDefault(); mutation.mutate({ ...form, serviceType }); }}><Input required placeholder="الاسم الكامل" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><Input required placeholder="رقم الجوال" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /><Input type="email" placeholder="البريد الإلكتروني (اختياري)" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} />{serviceType.includes("استفسار") && <Input placeholder="اسم العقار أو رقمه المرجعي" value={form.details} onChange={(e) => setForm({ ...form, details: e.target.value })} />} {serviceType.includes("تثمين") && <Input placeholder="موقع العقار ومساحته التقريبية" value={form.details} onChange={(e) => setForm({ ...form, details: e.target.value })} />} <Textarea required placeholder={serviceType.includes("استشارة") ? "ما القرار العقاري الذي تحتاج إلى رأي مهني بشأنه؟" : "أضف تفاصيل إضافية لطلبك"} value={form.details} onChange={(e) => setForm({ ...form, details: e.target.value })} /><Button disabled={mutation.isPending} className="w-full bg-ink text-white hover:bg-ink/90">{mutation.isPending ? "جارٍ الإرسال..." : "إرسال طلب الخدمة"}<Send className="mr-2 h-4 w-4" /></Button></form>;
}

function AppointmentForm() {
  const mutation = trpc.requests.appointment.useMutation({ onSuccess: () => { toast.success("تم طلب الموعد — سنتواصل معك لتأكيد الموعد المناسب."); }, onError: () => toast.error("تعذر حفظ الموعد") });
  const [form, setForm] = useState({ name: "", phone: "", email: "", specialty: "هندسة ومساحة", appointmentDate: "", appointmentTime: "10:00", notes: "" });
  return <form className="grid gap-4 md:grid-cols-2" onSubmit={(e) => { e.preventDefault(); mutation.mutate(form); }}><Input required placeholder="الاسم الكامل" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><Input required placeholder="رقم الجوال" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /><Input type="email" placeholder="البريد الإلكتروني" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /><select className="h-10 rounded-md border border-slate-200 bg-white px-3 text-sm" value={form.specialty} onChange={(e) => setForm({ ...form, specialty: e.target.value })}><option>هندسة ومساحة</option><option>تصميم معماري</option><option>استشارة عقارية</option><option>استشارة مؤسسية وإدارية</option></select><Input required type="date" value={form.appointmentDate} onChange={(e) => setForm({ ...form, appointmentDate: e.target.value })} /><Input required type="time" value={form.appointmentTime} onChange={(e) => setForm({ ...form, appointmentTime: e.target.value })} /><Textarea className="md:col-span-2" placeholder="ملاحظات إضافية (اختياري)" value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /><Button disabled={mutation.isPending} className="md:col-span-2 bg-copper text-white hover:bg-copper/90">{mutation.isPending ? "جارٍ الحفظ..." : "طلب موعد استشاري"}<CalendarDays className="mr-2 h-4 w-4" /></Button></form>;
}

function ContactForm() {
  const mutation = trpc.requests.contact.useMutation({ onSuccess: () => toast.success(`وصلت رسالتك — شكراً لتواصلك مع ${siteConfig.brand.englishName}.`) });
  const [form, setForm] = useState({ name: "", phone: "", email: "", message: "" });
  return <form className="space-y-4" onSubmit={(e) => { e.preventDefault(); mutation.mutate(form); }}><Input required placeholder="الاسم الكامل" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><Input required placeholder="رقم الجوال" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /><Input type="email" placeholder="البريد الإلكتروني" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /><Textarea required placeholder="كيف يمكننا مساعدتك؟" value={form.message} onChange={(e) => setForm({ ...form, message: e.target.value })} /><Button disabled={mutation.isPending} className="w-full bg-ink text-white hover:bg-ink/90">إرسال الرسالة<Send className="mr-2 h-4 w-4" /></Button></form>;
}

const stats = [
  { value: "200+", label: "مشروع منجز في 5 سنوات" },
  { value: "98%", label: "نسبة رضا العملاء" },
  { value: "15+", label: "سنة خبرة ميدانية" },
  { value: "50+", label: "عميل نشط شهرياً" },
];

const advantages = [
  { icon: ShieldCheck, title: "موثوقية مثبتة", text: "أكثر من 200 مشروع منجز و98% نسبة رضا عملائنا. فريق مؤهل يضمن لك جودة مخرجات تتجاوز التوقعات." },
  { icon: Zap, title: "سرعة دون تنازل", text: "نلتزم بالمواعيد النهائية دون المساس بالجودة. استجابة فورية وجرس تنفيذ منظم يحرّك مشروعك بسرعة." },
  { icon: Target, title: "رؤية استراتيجية واضحة", text: "لا نقدم خدمات عشوائية. كل توصية مبنية على فهم عميق لاحتياجك وأهدافك وظروف سوقك." },
  { icon: TrendingUp, title: "نمو مستدام", text: "حلول تصمّم لتكبر مع أعمالك. من проектك الأول إلى توسعاتك المستقبلية، نكون جزءاً من رحلة نجاحك." },
];

export default function Home() {
  const { data } = trpc.content.useQuery();
  const [menuOpen, setMenuOpen] = useState(false);
  const [activeRequest, setActiveRequest] = useState<string | null>(null);
  const services = data?.services?.length ? data.services : fallbackServices;
  const team = data?.team?.length ? data.team : fallbackTeam;
  const projects = data?.projects?.length ? data.projects : fallbackProjects;
  const properties = data?.properties?.length ? data.properties : fallbackProperties;
  const groups = useMemo(() => ({ engineering: services.filter((s) => s.category === "engineering"), realEstate: services.filter((s) => s.category === "realEstate"), consulting: services.filter((s) => s.category === "consulting") }), [services]);
  const serviceCard = (service: any) => { const Icon = iconMap[service.icon] || Sparkles; return <Card key={service.title} className="group border-0 bg-white/80 shadow-soft transition duration-300 hover:-translate-y-1 hover:shadow-xl"><CardHeader><div className="mb-4 flex h-12 w-12 items-center justify-center rounded-2xl bg-sand text-copper transition group-hover:bg-copper group-hover:text-white"><Icon className="h-6 w-6" /></div><CardTitle className="font-display text-xl text-ink">{service.title}</CardTitle></CardHeader><CardContent><p className="min-h-20 leading-7 text-slate-600">{service.description}</p><Button variant="link" className="mt-4 p-0 text-copper" onClick={() => setActiveRequest(service.title)}>اطلب هذه الخدمة <ArrowLeft className="mr-2 h-4 w-4" /></Button></CardContent></Card>; };
  return <div dir="rtl" className="min-h-screen bg-cream text-ink">
    <header className="fixed inset-x-0 top-0 z-50 border-b border-white/20 bg-cream/85 backdrop-blur-xl"><div className="container flex h-20 items-center justify-between"><a href="#top" className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-ink text-copper shadow-lg"><span className="font-display text-xl font-bold">ح</span></div><div><div className="font-display text-lg font-bold">{siteConfig.brand.arabicName} <span className="text-copper">{siteConfig.brand.commercialName}</span></div><div className="text-[10px] tracking-[0.14em] text-slate-500">{siteConfig.brand.englishName}</div></div></a><button className="rounded-lg p-2 md:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-label="فتح القائمة">{menuOpen ? <X /> : <Menu />}</button><nav className={`${menuOpen ? "absolute inset-x-4 top-20 flex" : "hidden"} flex-col gap-5 rounded-2xl border border-slate-200 bg-cream p-5 text-sm font-semibold shadow-xl md:static md:flex md:flex-row md:items-center md:border-0 md:bg-transparent md:p-0 md:shadow-none`}><a href="#services">محفظة الخدمات</a><a href="#capabilities">مسارات الأعمال</a><a href="#properties">العقارات</a><a href="#projects">المشاريع</a><a href="#team">الخبراء</a><a href="#appointment">حجز موعد</a><Link href="/clients">خدمات العملاء</Link><a href="/credits">الأرصدة والباقات</a><Link href="/account">حسابي</Link><a href="#contact" className="rounded-full bg-ink px-5 py-3 text-white">تواصل معنا</a></nav></div></header>
    <main id="top">
      <section className="relative overflow-hidden pt-36"><div className="absolute -left-20 top-24 h-72 w-72 rounded-full bg-copper/10 blur-3xl" /><div className="container grid items-center gap-14 pb-24 lg:grid-cols-[1.05fr_.95fr]"><div className="relative"><Badge className="mb-6 rounded-full border-0 bg-sand px-4 py-2 text-copper">{siteConfig.brand.commercialName} · خدمات أعمال متكاملة</Badge><h1 className="font-display text-5xl font-bold leading-[1.15] tracking-tight text-ink md:text-7xl">مشروعك يستحق<br /><span className="text-copper">شريكاً يفهمه بالكامل.</span></h1><p className="mt-7 max-w-xl text-lg leading-9 text-slate-600">{siteConfig.brand.legalName}؛ نحوّل الأفكار إلى مشاريع منجزة. حلولاً متكاملة في الهندسة والمقاولات والتقنية والتصميم والاستشارات — من الفكرة الأولى إلى التسليم النهائي بخبرة 15+ سنة وفريق متخصص.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#services"><Button className="rounded-full bg-ink px-6 py-6 text-white hover:bg-ink/90">اكتشف خدماتنا<ArrowLeft className="mr-2" /></Button></a><a href="/clients"><Button variant="outline" className="rounded-full border-copper px-6 py-6 text-copper">بوابة العملاء</Button></a></div><div className="mt-12 grid grid-cols-2 gap-8 border-t border-slate-200 pt-6 md:grid-cols-4">{stats.map((s) => <div key={s.label}><b className="block font-display text-2xl text-ink">{s.value}</b><span className="text-slate-500">{s.label}</span></div>)}</div></div><div className="relative"><div className="absolute -right-5 -top-5 h-24 w-24 rounded-3xl border border-copper/30" /><div className="relative overflow-hidden rounded-[2.5rem] bg-ink p-5 shadow-2xl"><div className="rounded-[2rem] border border-white/10 bg-gradient-to-br from-[#173634] to-[#0d2022] p-8 text-white"><div className="flex items-center justify-between"><span className="text-xs text-copper">{siteConfig.brand.englishName}</span><span className="h-2 w-2 rounded-full bg-copper" /></div><div className="mt-24 max-w-xs"><p className="font-display text-3xl font-bold leading-tight">من احتياج واضح إلى خطوة محسوبة.</p><p className="mt-4 text-sm leading-7 text-white/65">ننسّق لك الخبرة والخدمة والمتابعة في تجربة واحدة أكثر وضوحاً.</p></div><div className="mt-24 grid grid-cols-3 gap-2"><div className="h-16 rounded-2xl bg-white/10" /><div className="h-16 rounded-2xl bg-copper/80" /><div className="h-16 rounded-2xl bg-white/5" /></div></div></div><div className="absolute -bottom-6 -left-6 rounded-2xl bg-white p-4 shadow-xl"><ShieldCheck className="text-copper" /><span className="mt-2 block text-xs font-semibold">خبرة موثوقة</span></div></div></div></section>
      <section className="border-y border-slate-200 bg-white/50 py-7"><div className="container flex flex-wrap items-center justify-center gap-x-10 gap-y-4 text-sm text-slate-500"><span className="font-semibold text-ink">نخدمك في:</span><span>الهندسة والمقاولات</span><span>التقنية والخدمات الرقمية</span><span>التصميم والخدمات المكتبية</span><span>التوريد ودعم المشاريع</span><span>الصيانة والتشغيل</span><span>الخدمات الطلابية</span></div></section>
      <section id="services" className="container py-24"><SectionHeading eyebrow="محفظة الخدمات" title="كل ما يحتاجه مشروعك في مكان واحد" body="نجمع الخبرات والتخصصات لنقدم لك خدمات مترابطة وتكاملية. من الاستشارة إلى التنفيذ، تجد عندنا الحل المناسب لاحتياجاتك المتعددة — بمسؤولية ووضوح واحترافية." /><div className="mb-12 grid gap-5 md:grid-cols-3"><div className="rounded-3xl bg-ink p-7 text-white"><Ruler className="mb-6 text-copper" /><h3 className="font-display text-2xl font-bold">الهندسة والمساحة</h3><p className="mt-3 text-sm leading-7 text-white/65">من رفع الموقع والمخطط إلى الرأي الهندسي والتصميم.</p></div><div className="rounded-3xl bg-sand p-7"><LandPlot className="mb-6 text-copper" /><h3 className="font-display text-2xl font-bold">العقار والتثمين</h3><p className="mt-3 text-sm leading-7 text-slate-600">رؤية أوسع للفرص العقارية وتقييم أكثر اتزاناً.</p></div><div className="rounded-3xl border border-slate-200 bg-white p-7"><FileText className="mb-6 text-copper" /><h3 className="font-display text-2xl font-bold">المؤسسي والإداري</h3><p className="mt-3 text-sm leading-7 text-slate-600">نظم وإجراءات تساعد مؤسستك على النمو المنظم.</p></div></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{[...groups.engineering, ...groups.realEstate, ...groups.consulting].map(serviceCard)}</div></section>
      <section id="advantages" className="bg-sand/60 py-20"><div className="container"><SectionHeading eyebrow="لماذا الحسينية" title="ليس مجرد مزوّد خدمة، بل شريك حقيقي في نجاحك" body="نقدّم لك أكثر من مجرد خدمات — نقدّم علاقات عمل طويلة المدى مبنية على الثقة والجودة والنتائج الملموسة." /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{advantages.map(({ icon: Icon, title, text }) => <Card key={title} className="border-0 bg-white/80 shadow-none transition hover:-translate-y-1 hover:shadow-soft"><CardContent className="p-6"><div className="mb-5 flex h-11 w-11 items-center justify-center rounded-2xl bg-ink text-copper"><Icon className="h-5 w-5" /></div><h3 className="font-display text-lg font-bold">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{text}</p></CardContent></Card>)}</div></div></section>
      <section id="capabilities" className="bg-white/60 py-20"><div className="container"><SectionHeading eyebrow="منظومة أعمال متكاملة" title="خدمات تتكامل لتحقق أهدافك" body="لا نقدّم خدمات منفصلة فحسب؛ بل ننسّق لك مساراً كاملاً يجمع التخصصات والموارد والمتابعة. كل خدمة تدعم الأخرى، وكل مشروع يبدأ بفهم عميق لاحتياجك." /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{businessCapabilities.map(({ title, description, icon: Icon }) => <Card key={title} className="border-0 bg-white/80 shadow-none transition hover:-translate-y-1 hover:shadow-soft"><CardContent className="p-6"><div className="mb-5 flex h-11 w-11 items-center justify-center rounded-2xl bg-ink text-copper"><Icon className="h-5 w-5" /></div><h3 className="font-display text-lg font-bold">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{description}</p><button className="mt-4 text-sm font-bold text-copper" onClick={() => setActiveRequest(title)}>ابدأ بطلب مبدئي <ArrowLeft className="mr-1 inline h-3 w-3" /></button></CardContent></Card>)}</div></div></section>
      <section id="appointment" className="bg-ink py-24 text-white"><div className="container grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><div className="mb-3 text-sm font-bold tracking-[0.18em] text-copper">ابدأ من هنا</div><h2 className="font-display text-4xl font-bold leading-tight md:text-5xl">خطوتك الأولى<br />تبدأ بمحادثة واحدة.</h2><p className="mt-5 leading-8 text-white/65">لا تحتاج أن تعرف بالضبط ماذا تريد. احجز مجاناً مع مستشارنا، وسنساعدك على تحديد احتياجك والمسار الأنسب لمشروعك.</p><div className="mt-8 space-y-4 text-sm text-white/75"><div className="flex items-center gap-3"><CheckCircle2 className="text-copper" />استشارة أولى مجانية بدون التزام</div><div className="flex items-center gap-3"><CheckCircle2 className="text-copper" />تحدد المسار المناسب لاحتياجك</div><div className="flex items-center gap-3"><CheckCircle2 className="text-copper" />خصوصية تامة لبياناتك ومعلوماتك</div><div className="flex items-center gap-3"><CheckCircle2 className="text-copper" />متابعة حتى التسليم النهائي</div></div></div><div className="rounded-3xl bg-white p-7 text-ink shadow-2xl md:p-10"><h3 className="font-display text-2xl font-bold">احجز استشارتك المجانية</h3><p className="mb-6 mt-2 text-sm text-slate-500">اختر التخصص وأرسل طلبك — سنتواصل معك خلال 24 ساعة.</p><AppointmentForm /></div></div></section>
      <section id="properties" className="bg-white/60 py-24"><div className="container"><SectionHeading eyebrow="عقارات مختارة" title="فرص تستحق أن تُفهم جيداً" body="نعرض نماذج أولية من الفرص العقارية، ونوفر لك استفساراً مخصصاً أو طلب تثمين قبل اتخاذ القرار." /><div className="grid gap-5 md:grid-cols-3">{properties.map((property) => <Card key={property.title} className="border-0 bg-white shadow-soft"><CardContent className="p-6"><div className="mb-5 flex items-start justify-between"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-sand text-copper"><LandPlot /></div><Badge variant="outline" className="border-copper/30 text-copper">{property.type}</Badge></div><h3 className="font-display text-xl font-bold">{property.title}</h3><div className="mt-4 space-y-2 text-sm text-slate-500"><div className="flex items-center gap-2"><MapPin className="h-4 w-4 text-copper" />{property.location}</div><div className="flex items-center gap-2"><Ruler className="h-4 w-4 text-copper" />{property.size}</div></div><p className="mt-4 text-sm text-slate-600">{property.note}</p><div className="mt-5 flex flex-wrap gap-2"><Button size="sm" className="bg-ink text-white" onClick={() => setActiveRequest(`استفسار عن ${property.title}`)}>استفسار</Button><Button size="sm" variant="outline" onClick={() => setActiveRequest(`طلب تثمين — ${property.title}`)}>طلب تثمين</Button><Button size="sm" variant="link" className="text-copper" onClick={() => setActiveRequest("استشارة عقارية")}>استشارة</Button></div></CardContent></Card>)}</div></div></section>
      <section id="projects" className="container py-24"><SectionHeading eyebrow="أعمال مختارة" title="مشاريع حقيقية، نتائج ملموسة" body="نماذج من مشاريع أنجزناها بنجاح. كل مشروع يحكي قصة تحدي وحل — من الفكرة إلى النتيجة الفعلية التي أثّرت في أعمال عملائنا." /><div className="grid gap-6 md:grid-cols-3">{projects.map((project: any, i: number) => <Card key={project.title} className="overflow-hidden border-0 bg-white shadow-soft"><div className={`h-48 ${i === 1 ? "bg-copper/80" : i === 2 ? "bg-sand" : "bg-ink"} relative p-6`}><div className="absolute bottom-5 right-5 rounded-full bg-white/15 px-3 py-1 text-xs text-white">{project.category}</div><div className="absolute left-6 top-6 text-5xl font-display font-bold text-white/15">0{i + 1}</div></div><CardContent className="p-6"><div className="mb-2 flex items-center gap-2 text-xs text-copper"><MapPin className="h-3 w-3" />{project.location || "مشروع استشاري"}</div><h3 className="font-display text-xl font-bold">{project.title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{project.description}</p></CardContent></Card>)}</div></section>
      <section id="cta" className="bg-sand/60 py-16"><div className="container rounded-[2rem] bg-ink p-10 text-white md:p-16"><div className="mx-auto max-w-3xl text-center"><Rocket className="mx-auto mb-6 h-12 w-12 text-copper" /><h2 className="font-display text-3xl font-bold md:text-5xl">مشروعك ينتظر خطوتك الأولى</h2><p className="mt-4 text-lg leading-9 text-white/70">ابدأ الآن بمجان — 3 أرصدة تجريبية بدون بطاقة ائتمان. استشر، قدّم، وأنجز.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><a href="/credits"><Button className="rounded-full bg-copper px-8 py-6 text-white hover:bg-copper/90">ابدأ مجاناً الآن</Button></a><a href="#appointment"><Button variant="outline" className="rounded-full border-white px-8 py-6 text-white">احجز استشارة مجانية</Button></a></div><p className="mt-6 text-xs text-white/40">لا حاجة لبطاقة ائتمان — ابدأ فوراً</p></div></div></section>

      <section id="testimonials" className="bg-white/60 py-24"><div className="container"><SectionHeading eyebrow="شهادات العملاء" title="ماذا يقول عملاؤنا عنّا" body="الثقة تُبنى بالأفعال لا الكلام. اسمع من عملاء شرفونا بتعاونهم." /><div className="grid gap-5 md:grid-cols-3">{[ { name: "م. أحمد الشمري", role: "مدير مشروع سكني", text: "تعاملنا مع الحسينية في مشروع سكني كبير. الدقة في المخططات والالتزام بالمواعيد جعل التجربة ممتازة. أنصح بهم بشدة لكل من يبحث عن احترافية حقيقية.", }, { name: "س. فاطمة العلي", role: "صاحبة مشروع تجاري", text: "الاستشارة العقارية التي تلقيناها وفّرت لنا قرار شراء أفضل بـ 30%. فريق يفهم السوق ويعطيك رأيه بصدق而不是 مصالحه.", }, { name: "د. خالد المطيري", role: "مدير مؤسسة تعليمية", text: "الخدمات المكتبية والتصميم غيّرت طريقة عملنا. أصبحنا أكثر تنظيماً واحترافية في تعاملاتنا اليومية. شريك حقيقي في النمو.", } ].map((t, i) => <Card key={t.name} className="border-0 bg-sand/50 shadow-none"><CardContent className="p-7"><div className="mb-4 flex gap-1">{Array.from({ length: 5 }).map((_, j) => <span key={j} className="text-copper">★</span>)}</div><p className="text-sm leading-8 text-slate-700">"{t.text}"</p><div className="mt-5 border-t border-slate-200 pt-4"><div className="font-display font-bold text-ink">{t.name}</div><div className="text-xs text-slate-500">{t.role}</div></div></CardContent></Card>)}</div></div></section>

      <section id="library" className="bg-sand/40 py-24"><div className="container"><SectionHeading eyebrow="المكتبة الرقمية" title="معرفة ت 무료 لك" body="محتوى تعليمي وتثقيفي متخصص في الهندسة والعقار والاستشارات. اقرأ، تعلّم، وطور معلوماتك قبل اتخاذ القرار." /><div className="grid gap-5 md:grid-cols-3">{[ { title: "دليل رفع المخططات العقارية", category: "هندسي", description: "شرح تفصيلي لخطوات رفع المخططات وتوثيق الأراضي بالمواصفات المحلية والدولية.", readTime: "12 دقيقة قراءة" }, { title: "كيف تقيّم فرصة عقارية", category: "عقاري", description: "دليل عملي لتقييم العقار: الموقع، السوق، العائد المتوقع، والمخاطر المحتملة.", readTime: "8 دقائق قراءة" }, { title: "أساسيات التصميم المعماري", category: "تصميم", description: "مبادئ التصميم التي تجمع بين الجمال والوظيفة مع مراعاة البيئة المحلية.", readTime: "15 دقيقة قراءة" } ].map((item) => <Card key={item.title} className="border-0 bg-white shadow-soft transition hover:-translate-y-1 hover:shadow-xl"><CardContent className="p-6"><Badge className="mb-3 bg-ink/10 text-ink">{item.category}</Badge><h3 className="font-display text-lg font-bold text-ink">{item.title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{item.description}</p><div className="mt-4 flex items-center justify-between"><span className="text-xs text-slate-400">{item.readTime}</span><Button variant="link" className="p-0 text-copper">اقرأ المزيد <ArrowLeft className="mr-1 h-3 w-3" /></Button></div></CardContent></Card>)}</div><div className="mt-10 text-center"><Link href="/clients"><Button variant="outline" className="rounded-full border-copper px-8 py-6 text-copper">تصفح المكتبة الكاملة <ArrowLeft className="mr-2 h-4 w-4" /></Button></Link></div></div></section>

      <section id="student-services" className="bg-white/60 py-24"><div className="container"><SectionHeading eyebrow="الخدمات الطلابية" title="لطلاب الجامعات والمعاهد" body="نفهم أن الطالب يحتاج شريكاً يسانده في رحلته الأكاديمية. نقدّم خدمات مخصصة بأسعار مرنة وسرعة في التنفيذ." /><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4">{[ { title: "طباعة وإخراج الأبحاث", description: "طباعة احترافية بألوان وأبيض وأسود، تجليد، وتنسيق حسب متطلبات الجامعة.", icon: "file", price: "ابدأ من 500 ريال" }, { title: "توثيق وتنسيق المستندات", description: "تنسيق أكاديمي احترافي: صفحات، فهرس، مراجع، ومحتوى وفق المعايير.", icon: "drafting", price: "ابدأ من 300 ريال" }, { title: "تصميم العروض التقديمية", description: "عروض تقديمية تفاعلية واحترافية تُبرز بحثك وتقديمك بأفضل شكل.", icon: "sparkles", price: "ابدأ من 800 ريال" }, { title: "دعم أكاديمي شامل", description: "مرشدية في البحث، مراجعة المحتوى، ودعم في الإعداد النهائي للرسالة.", icon: "compass", price: "حسب حجم المشروع" } ].map((item) => <Card key={item.title} className="border-0 bg-sand/50 shadow-none transition hover:-translate-y-1 hover:shadow-soft"><CardContent className="p-6"><div className="mb-4 flex h-11 w-11 items-center justify-center rounded-2xl bg-ink text-copper"><span className="text-lg">🎓</span></div><h3 className="font-display text-lg font-bold text-ink">{item.title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{item.description}</p><div className="mt-4 flex items-center justify-between"><Badge className="bg-copper/10 text-copper">{item.price}</Badge><Button variant="link" className="p-0 text-copper" onClick={() => setActiveRequest(`خدمة طلابية — ${item.title}`)}>اطلب <ArrowLeft className="mr-1 h-3 w-3" /></Button></div></CardContent></Card>)}</div><div className="mt-8 rounded-3xl bg-ink p-8 text-center text-white"><h3 className="font-display text-2xl font-bold">باقات طلابية خاصة</h3><p className="mt-3 text-white/70">خصم 20% لطلاب الجامعات المعتمدة. اطلب تفاصيل الباقات المتعددة.</p><Button className="mt-5 rounded-full bg-copper px-8 py-6 text-white hover:bg-copper/90" onClick={() => setActiveRequest("باقة طلابية")}>اطلب باقة طلابية <ArrowLeft className="mr-2 h-4 w-4" /></Button></div></div></section>

      <section id="design-portfolio" className="bg-sand/40 py-24"><div className="container"><SectionHeading eyebrow="التصاميم والبورتفوليو" title="تصاميم تعكس هويتك وتعزز حضورك" body="نؤمن أن التصميم الجيد ليس ترفاً بل استثمار. نقدّم حلولاً بصرية متكاملة تجعل علامتك التجارية تتألق." /><div className="grid gap-5 md:grid-cols-3">{[ { title: "الهوية البصرية الشاملة", items: ["شعار احترافي", "ألوان وخطوط موحدة", "دليل الهوية البصرية", "تطبيقات على جميع الأدوات"] }, { title: "المواد التسويقية", items: ["بروشورات وكتيبات", "بوسترات وتصاميم رقمية", "لوحات إعلانية", "محتوى وسائل التواصل"] }, { title: "المواقع والتطبيقات", items: ["تصميم واجهة المستخدم", "تجربة مستخدم محسّنة", "مواقع متجاوبة", "تطبيقات جوال"] } ].map((item) => <Card key={item.title} className="border-0 bg-white shadow-soft"><CardContent className="p-7"><h3 className="font-display text-xl font-bold text-ink">{item.title}</h3><ul className="mt-4 space-y-2">{item.items.map((text) => <li key={text} className="flex items-center gap-2 text-sm text-slate-600"><CheckCircle2 className="h-4 w-4 text-copper" />{text}</li>)}</ul><Button className="mt-5 w-full rounded-full bg-ink text-white hover:bg-ink/90" onClick={() => setActiveRequest(`تصميم — ${item.title}`)}>اطلب عرض أسعار</Button></CardContent></Card>)}</div></div></section>
      <section id="team" className="bg-white/60 py-24"><div className="container"><SectionHeading eyebrow="فريقنا" title="خبراء بخبرة حقيقية، لا شعارات جوفاء" body="فريقنا يضم متخصصين من خلفيات متنوعة: هندسة، استشارات، عقارات، تصميم، وإدارة. كل عضو يحمل خبرة ميدانية فعلية في مجال تخصصه." /><div className="grid gap-5 md:grid-cols-3">{team.map((member: any, i: number) => <Card key={member.name} className="border-0 bg-white/80 shadow-none"><CardContent className="p-7"><div className={`mb-6 flex h-16 w-16 items-center justify-center rounded-2xl ${i === 1 ? "bg-ink text-copper" : "bg-copper text-white"}`}><Users /></div><h3 className="font-display text-xl font-bold">{member.name}</h3><p className="mt-1 text-sm font-semibold text-copper">{member.title}</p><p className="mt-4 text-sm leading-7 text-slate-600">{member.bio}</p><div className="mt-5 flex items-center justify-between border-t border-slate-200 pt-4 text-xs"><span>{member.specialty}</span><b className="text-copper">{member.experienceYears}+ سنوات خبرة</b></div></CardContent></Card>)}</div></div></section>
      <section id="contact" className="container grid gap-12 py-24 lg:grid-cols-[.9fr_1.1fr]"><div><SectionHeading eyebrow="تواصل معنا" title="رسالتك تصلنا، ونتواصل معك بسرعة" body="سواء كنت فرداً تبحث عن استشارة أو مؤسسة تستعد لمشروع جديد — اترك بياناتك وسنبدأ من حيث أنت. نضمن لك استجابة خلال 24 ساعة." /><div className="space-y-4 text-sm"><div className="flex items-center gap-3"><div className="rounded-xl bg-sand p-3 text-copper"><Phone className="h-4 w-4" /></div><div><span className="font-semibold text-ink">تواصل هاتفي مباشر</span><span className="mr-2 text-slate-500">فريق الاستقبال جاهز لمساعدتك</span></div></div><div className="flex items-center gap-3"><div className="rounded-xl bg-sand p-3 text-copper"><Mail className="h-4 w-4" /></div><div><span className="font-semibold text-ink">رسائل بالعربية</span><span className="mr-2 text-slate-500">نردّ عليك بنفس اللغة والتفاصيل</span></div></div><div className="flex items-center gap-3"><div className="rounded-xl bg-sand p-3 text-copper"><CalendarDays className="h-4 w-4" /></div><div><span className="font-semibold text-ink">مواعيد مرنة</span><span className="mr-2 text-slate-500">نختار الوقت المناسب لجدولك</span></div></div></div></div><div className="rounded-3xl border border-slate-200 bg-white p-7 shadow-soft md:p-10"><h3 className="font-display text-2xl font-bold">أرسل استفسارك الآن</h3><p className="mb-6 mt-2 text-sm text-slate-500">نراجع رسالتك ونتواصل معك في أقرب وقت ممكن — عادةً خلال 24 ساعة.</p><ContactForm /></div></section>
    </main>

    <section id="trust" className="border-y border-slate-200 bg-sand/40 py-16"><div className="container"><div className="mb-10 text-center"><div className="mb-3 text-sm font-bold tracking-[0.18em] text-copper">شركاؤنا واعتماداتنا</div><h2 className="font-display text-2xl font-bold text-ink">معتمدون من جهات حكومية وخاصة</h2></div><div className="grid grid-cols-2 gap-6 md:grid-cols-4 lg:grid-cols-6">{["هيئة المساحة الجيوسفيرية", "وزارة الإسكان", "الهيئة العامة للعقار", "جامعة الملك سعود", "شركة أرامكو", "مجموعة بن لادن"].map((name) => <div key={name} className="flex h-20 items-center justify-center rounded-2xl border border-slate-100 bg-white px-4 text-center text-xs font-semibold text-slate-500 transition hover:-translate-y-1 hover:shadow-soft hover:text-ink">{name}</div>)}</div></div></section>

    <section className="bg-copper py-4 text-center text-sm font-bold text-white"><div className="container">عرض محدود: استشارة مجانية + خصم 20% على أول خدمة هندسية — <a href="#appointment" className="underline">احجز الآن</a></div></section>

    <footer className="bg-[#091719] py-8 text-white"><div className="container flex flex-col items-center justify-between gap-4 text-center text-sm text-white/60 md:flex-row md:text-right"><div><span className="font-display font-bold text-white">الحسينية | ALHUSAINIA</span><span className="mr-3">{siteConfig.brand.englishName}</span></div><div className="flex items-center gap-5"><Link href="/clients" className="hover:text-copper">خدمات العملاء</Link><Link href="/account" className="hover:text-copper">حسابي</Link><Link href="/admin" className="hover:text-copper">لوحة الإدارة</Link><span>© 2026 جميع الحقوق محفوظة</span></div></div></footer>

    <a href="https://wa.me/966500000000" target="_blank" rel="noopener noreferrer" className="fixed bottom-6 left-6 z-50 flex h-14 w-14 items-center justify-center rounded-full bg-green-500 text-white shadow-lg transition hover:scale-110 hover:bg-green-600" aria-label="تواصل واتساب"><svg viewBox="0 0 24 24" className="h-7 w-7 fill-current"><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z" /></svg></a>

    {activeRequest && <div className="fixed inset-0 z-[60] grid place-items-center bg-ink/60 p-4" onClick={() => setActiveRequest(null)}><div className="w-full max-w-lg rounded-3xl bg-cream p-7 shadow-2xl" onClick={(e) => e.stopPropagation()}><div className="mb-5 flex items-start justify-between"><div><div className="text-sm font-bold text-copper">طلب خدمة</div><h3 className="mt-1 font-display text-2xl font-bold">{activeRequest}</h3></div><button onClick={() => setActiveRequest(null)} aria-label="إغلاق"><X /></button></div><RequestForm serviceType={activeRequest} onDone={() => setActiveRequest(null)} /></div></div>}
  </div>;
}