/**
 * server/_core/migrate.ts
 * -------------
 * Pure, testable helpers for the project's SQL-file migration runner.
 *
 * The project stores Drizzle-generated schema snapshots as `drizzle/*.sql`
 * files that are applied by `scripts/run-migrations.ts`. This module keeps
 * the fragile parsing/decision logic isolated so it can be unit-tested
 * without a database or the Neon driver.
 */

/** Drizzle-kit embeds this marker between consecutive SQL statements. */
export const MIGRATION_BREAKPOINT = "--> statement-breakpoint";

/**
 * Split a Drizzle-generated SQL file into standalone statements.
 *
 * Robust to both LF (`\n`) and Windows CRLF (`\r\n`) line endings — the
 * previous implementation split on `\n` only and therefore produced a single
 * giant (unexecutable) chunk on Windows machines.
 *
 * Hand-written migration files (not generated by drizzle-kit) omit the
 * breakpoint marker and instead separate statements with a semicolon. Those
 * are split on *top-level* `;` only — i.e. semicolons that sit outside:
 *   - single/double-quoted strings
 *   - dollar-quoted blocks (`$$ … $$` or `$tag$ … $tag$`, plpgsql bodies)
 *   - `--` line comments and `/*` … `*​/` block comments
 * so a `;` inside a function body never breaks the file apart.
 */
export function splitMigrationStatements(sqlText: string): string[] {
  const normalized = sqlText.replace(/\r\n/g, "\n");
  const chunks = normalized
    .split(`${MIGRATION_BREAKPOINT}\n`)
    .map(s => s.trim())
    .filter(s => s.length > 0);

  return chunks.flatMap(splitTopLevelStatements);
}

/** Strip `--` line comments and block comments; used to skip comment-only segments. */
function withoutComments(sql: string): string {
  return sql
    .replace(/--[^\n]*/g, "")
    .replace(/\/\*[\s\S]*?\*\//g, "");
}

/**
 * Scan a SQL chunk and split on semicolons that are at "top level" —
 * outside strings, dollar-quoted blocks, and comments. Preserves all
 * whitespace/comment content within each statement.
 */
function splitTopLevelStatements(chunk: string): string[] {
  const parts: string[] = [];
  let current = "";
  let i = 0;
  const n = chunk.length;

  while (i < n) {
    const ch = chunk[i];

    // `--` line comment — runs to end of line (terminator kept).
    if (ch === "-" && chunk[i + 1] === "-") {
      const end = chunk.indexOf("\n", i);
      const stop = end === -1 ? n : end + 1;
      current += chunk.slice(i, stop);
      i = stop;
      continue;
    }

    // Block comment — runs to closing `*/`.
    if (ch === "/" && chunk[i + 1] === "*") {
      const end = chunk.indexOf("*/", i + 2);
      const stop = end === -1 ? n : end + 2;
      current += chunk.slice(i, stop);
      i = stop;
      continue;
    }

    // Single- or double-quoted string. Doubled quotes ('') are escapes.
    if (ch === "'" || ch === '"') {
      let j = i + 1;
      while (j < n) {
        if (chunk[j] === ch) {
          if (chunk[j + 1] === ch) {
            j += 2; // escaped quote ('' or "")
            continue;
          }
          j++;
          break;
        }
        j++;
      }
      current += chunk.slice(i, j);
      i = j;
      continue;
    }

    // Dollar-quoted block: `$$…$$` or `$tag$…$tag$`. The identical tag
    // terminates it; nothing inside (semicolons, quotes) is top-level.
    if (ch === "$") {
      const tagMatch = /^\$(?:[A-Za-z_][A-Za-z0-9_]*)?\$/.exec(chunk.slice(i));
      if (tagMatch) {
        const tag = tagMatch[0];
        const close = chunk.indexOf(tag, i + tag.length);
        const stop = close === -1 ? n : close + tag.length;
        current += chunk.slice(i, stop);
        i = stop;
        continue;
      }
    }

    // Top-level statement separator.
    if (ch === ";") {
      const stmt = current.trim();
      if (stmt.length > 0 && withoutComments(stmt).trim().length > 0) {
        parts.push(stmt.endsWith(";") ? stmt : `${stmt};`);
      }
      current = "";
      i++;
      continue;
    }

    current += ch;
    i++;
  }

  const tail = current.trim();
  if (tail.length > 0 && withoutComments(tail).trim().length > 0) {
    parts.push(tail.endsWith(";") ? tail : `${tail};`);
  }

  return parts.length > 0 ? parts : [chunk];
}

/** A statement that the postgres server explicitly said already exists. */
const IDEMPOTENT_ERROR_CODES = new Set([
  "42P07", // duplicate_table
  "42710", // duplicate_object (index/constraint already exists)
  "42704", // undefined_object (e.g. DROP CONSTRAINT on a missing one)
  "23505", // unique_violation
]);

/** Codes that mean "we tried to create something that is already there". */
const ALREADY_EXISTS_HINTS = [
  "already exists",
  "already used for an index",
  "duplicate key value violates unique constraint",
];

export type MigrationDecision =
  | { kind: "applied" }
  | { kind: "exists"; reason: string }
  | { kind: "failed"; reason: string };

/**
 * Classify a statement-execution error. CREATE/ALTER/DROP are treated as
 * idempotent when the server reports the object already exists (or is already
 * absent for drops), which lets the same migration directory run safely on
 * top of a partially-migrated database.
 */
export function classifyStatementError(
  error: unknown,
  statement?: string
): MigrationDecision {
  const raw =
    error instanceof Error ? error.message : String(error ?? "unknown error");
  // Neon driver errors carry the SQLSTATE in a `code` property that is not
  // always embedded in the message text; normalize it so the code checks below work.
  const codeProp = (error as any)?.code;
  const message =
    typeof codeProp === "string" &&
    /^\d{5}$/.test(codeProp) &&
    !raw.includes(codeProp)
      ? `${raw} (code ${codeProp})`
      : raw;
  const codeMatch = message.match(/code '([^']+)'|code (\d{5})/);
  const code = codeMatch ? (codeMatch[1] ?? codeMatch[2]) : "";
  if (
    IDEMPOTENT_ERROR_CODES.has(code) ||
    ALREADY_EXISTS_HINTS.some(h => message.includes(h))
  ) {
    return { kind: "exists", reason: message.slice(0, 160) };
  }
  // Dropping an object that isn't there is already the desired state — treat
  // it as idempotent success (only for actual DROP statements, so a missing
  // column on INSERT/SELECT still surfaces real schema drift).
  if (
    statement &&
    /^\s*DROP\b/i.test(statement) &&
    message.includes("does not exist")
  ) {
    return { kind: "exists", reason: message.slice(0, 160) };
  }
  return { kind: "failed", reason: message.slice(0, 300) };
}

/** Stable, git-friendly fingerprint of a migration file's content. */
export function checksumOf(text: string): string {
  let h1 = 0xdeadbeef;
  let h2 = 0x41c6ce57;
  for (let i = 0; i < text.length; i++) {
    const ch = text.charCodeAt(i);
    h1 = Math.imul(h1 ^ ch, 2654435761);
    h2 = Math.imul(h2 ^ ch, 1597334677);
  }
  h1 = Math.imul(h1 ^ (h1 >>> 16), 2246822507);
  h2 = Math.imul(h2 ^ (h2 >>> 13), 3266489909);
  const n1 = (h1 ^ (h1 >>> 16)) >>> 0;
  const n2 = (h2 ^ (h2 >>> 16)) >>> 0;
  return n1.toString(16).padStart(8, "0") + n2.toString(16).padStart(8, "0");
}
