/**
 * server/_core/migrate.ts
 * -------------
 * Pure, testable helpers for the project's SQL-file migration runner.
 *
 * The project stores Drizzle-generated schema snapshots as `drizzle/*.sql`
 * files that are applied by `scripts/run-migrations.ts`. This module keeps
 * the fragile parsing/decision logic isolated so it can be unit-tested
 * without a database or the Neon driver.
 */

/** Drizzle-kit embeds this marker between consecutive SQL statements. */
export const MIGRATION_BREAKPOINT = "--> statement-breakpoint";

/**
 * Split a Drizzle-generated SQL file into standalone statements.
 *
 * Robust to both LF (`\n`) and Windows CRLF (`\r\n`) line endings — the
 * previous implementation split on `\n` only and therefore produced a single
 * giant (unexecutable) chunk on Windows machines.
 */
export function splitMigrationStatements(sqlText: string): string[] {
  const normalized = sqlText.replace(/\r\n/g, "\n");
  const chunks = normalized
    .split(`${MIGRATION_BREAKPOINT}\n`)
    .map((s) => s.trim())
    .filter((s) => s.length > 0);
  // Hand-written migration files (not generated by drizzle-kit) may omit the
  // breakpoint marker and instead separate statements with a semicolon at the
  // end of each line. Postgres' extended protocol rejects multi-command
  // strings ("cannot insert multiple commands into a prepared statement"), so
  // split those chunks further on `;` line endings — but leave dollar-quoted
  // blocks (functions/DO $$ … $$) untouched, since they can contain `;`.
  return chunks.flatMap((chunk) => {
    if (!chunk.includes(";") || chunk.includes("$$")) return [chunk];
    const parts = chunk
      .split(/;\s*\n/)
      .map((p) => p.trim())
      .filter((p) => p.length > 0)
      .map((p) => (p.endsWith(";") ? p : `${p};`));
    return parts.length > 1 ? parts : [chunk];
  });
}

/** A statement that the postgres server explicitly said already exists. */
const IDEMPOTENT_ERROR_CODES = new Set([
  "42P07", // duplicate_table
  "42710", // duplicate_object (index/constraint already exists)
  "42704", // undefined_object (e.g. DROP CONSTRAINT on a missing one)
  "23505", // unique_violation
]);

/** Codes that mean "we tried to create something that is already there". */
const ALREADY_EXISTS_HINTS = [
  "already exists",
  "already used for an index",
  "duplicate key value violates unique constraint",
];

export type MigrationDecision =
  | { kind: "applied" }
  | { kind: "exists"; reason: string }
  | { kind: "failed"; reason: string };

/**
 * Classify a statement-execution error. CREATE/ALTER/DROP are treated as
 * idempotent when the server reports the object already exists (or is already
 * absent for drops), which lets the same migration directory run safely on
 * top of a partially-migrated database.
 */
export function classifyStatementError(
  error: unknown,
  statement?: string
): MigrationDecision {
  const raw =
    error instanceof Error ? error.message : String(error ?? "unknown error");
  // Neon driver errors carry the SQLSTATE in a `code` property that is not
  // always embedded in the message text; normalize it so the code checks below work.
  const codeProp = (error as any)?.code;
  const message =
    typeof codeProp === "string" && /^\d{5}$/.test(codeProp) && !raw.includes(codeProp)
      ? `${raw} (code ${codeProp})`
      : raw;
  const codeMatch = message.match(/code '([^']+)'|code (\d{5})/);
  const code = codeMatch ? codeMatch[1] ?? codeMatch[2] : "";
  if (IDEMPOTENT_ERROR_CODES.has(code) || ALREADY_EXISTS_HINTS.some((h) => message.includes(h))) {
    return { kind: "exists", reason: message.slice(0, 160) };
  }
  // Dropping an object that isn't there is already the desired state — treat
  // it as idempotent success (only for actual DROP statements, so a missing
  // column on INSERT/SELECT still surfaces real schema drift).
  if (
    statement &&
    /^\s*DROP\b/i.test(statement) &&
    message.includes("does not exist")
  ) {
    return { kind: "exists", reason: message.slice(0, 160) };
  }
  return { kind: "failed", reason: message.slice(0, 300) };
}

/** Stable, git-friendly fingerprint of a migration file's content. */
export function checksumOf(text: string): string {
  let h1 = 0xdeadbeef;
  let h2 = 0x41c6ce57;
  for (let i = 0; i < text.length; i++) {
    const ch = text.charCodeAt(i);
    h1 = Math.imul(h1 ^ ch, 2654435761);
    h2 = Math.imul(h2 ^ ch, 1597334677);
  }
  h1 = Math.imul(h1 ^ (h1 >>> 16), 2246822507);
  h2 = Math.imul(h2 ^ (h2 >>> 13), 3266489909);
  const n1 = (h1 ^ (h1 >>> 16)) >>> 0;
  const n2 = (h2 ^ (h2 >>> 16)) >>> 0;
  return n1.toString(16).padStart(8, "0") + n2.toString(16).padStart(8, "0");
}