// Healthcare Patients Seed Data
// Realistic Yemeni patients with medical conditions
// Aligned with Yemeni, Gulf, and International Healthcare Standards

import { SeedPatient } from "./healthcareTenantData";

export const healthcarePatients: SeedPatient[] = [
  // ─── VIP & Prominent Patients ─────────────────────────────────────────────────
  {
    patientNumber: "PAT-001",
    firstName: "Abdullah",
    lastName: "Al-Houthi",
    localFirstName: "عبدالله",
    localLastName: " Houthis",
    gender: "male",
    dateOfBirth: "1965-03-15",
    age: 60,
    bloodType: "A+",
    nationality: "Yemeni",
    nationalId: "ID-1001234567",
    maritalStatus: "married",
    occupation: "Business Executive",
    email: "abdullah.alhouthi@husseiniya.ye",
    phone: "+967-1-2345678",
    mobile: "+967-771234567",
    address: " Haddah Street, Block 15",
    city: "Sana'a",
    region: "Sana'a Governorate",
    country: "Yemen",
    emergencyContactName: "Mohammed Abdullah",
    emergencyContactPhone: "+967-772345678",
    emergencyContactRelation: "Son",
    insuranceProvider: "اليمن للتأمين الصحي",
    insurancePolicyNumber: "YHI-VIP-001234",
    insuranceCardNumber: "YHI-77001234-001",
    insuranceExpiry: "2026-12-31",
    coPaymentPercent: "10",
    allergies: [
      { allergen: "Penicillin", severity: "severe", reaction: "Anaphylaxis" },
    ],
    chronicConditions: [
      {
        condition: "Type 2 Diabetes",
        icdCode: "E11.9",
        diagnosedDate: "2015-06-01",
        status: "managed",
      },
      {
        condition: "Hypertension",
        icdCode: "I10",
        diagnosedDate: "2012-03-15",
        status: "managed",
      },
      {
        condition: "Hyperlipidemia",
        icdCode: "E78.5",
        diagnosedDate: "2018-09-20",
        status: "managed",
      },
    ],
    medications: [
      { name: "Metformin 500mg", dosage: "1-0-1", frequency: "Twice daily" },
      { name: "Amlodipine 5mg", dosage: "1-0-0", frequency: "Once daily" },
      {
        name: "Atorvastatin 20mg",
        dosage: "0-0-1",
        frequency: "Once daily at night",
      },
    ],
    isVIP: true,
  },
  {
    patientNumber: "PAT-002",
    firstName: "Fatima",
    lastName: "Ahmed",
    localFirstName: "فاطمة",
    localLastName: "الحسن",
    gender: "female",
    dateOfBirth: "1978-07-22",
    age: 47,
    bloodType: "O+",
    nationality: "Yemeni",
    nationalId: "ID-2002345678",
    maritalStatus: "married",
    occupation: "Professor - Sana'a University",
    email: "fatima.ahmed@sanaa.edu.ye",
    phone: "+967-1-3456789",
    mobile: "+967-773456789",
    address: " Al-Zubairy Street",
    city: "Sana'a",
    region: "Sana'a Governorate",
    country: "Yemen",
    emergencyContactName: "Ahmed Mohammed",
    emergencyContactPhone: "+967-774567890",
    emergencyContactRelation: "Husband",
    insuranceProvider: "التأمين الصحي الشامل",
    insurancePolicyNumber: "GHI-STD-002345",
    insuranceCardNumber: "GHI-77002345-002",
    insuranceExpiry: "2026-06-30",
    coPaymentPercent: "15",
    allergies: [
      { allergen: "Sulfa drugs", severity: "moderate", reaction: "Skin rash" },
    ],
    chronicConditions: [
      {
        condition: "Asthma",
        icdCode: "J45.9",
        diagnosedDate: "2010-04-12",
        status: "controlled",
      },
      {
        condition: "Hypothyroidism",
        icdCode: "E03.9",
        diagnosedDate: "2019-01-15",
        status: "managed",
      },
    ],
    medications: [
      {
        name: "Levothyroxine 75mcg",
        dosage: "1-0-0",
        frequency: "Once daily morning",
      },
      {
        name: "Salbutamol inhaler",
        dosage: "As needed",
        frequency: "When needed",
      },
      {
        name: "Fluticasone inhaler",
        dosage: "1-0-1",
        frequency: "Twice daily",
      },
    ],
    isVIP: true,
  },
  // ─── Government Officials ─────────────────────────────────────────────────────
  {
    patientNumber: "PAT-003",
    firstName: "Mohammed",
    lastName: "Al-Sabri",
    localFirstName: "محمد",
    localLastName: "الصابري",
    gender: "male",
    dateOfBirth: "1970-11-08",
    age: 54,
    bloodType: "B+",
    nationality: "Yemeni",
    nationalId: "ID-1003456789",
    maritalStatus: "married",
    occupation: "Government Minister",
    email: "m.alsabri@gov.ye",
    phone: "+967-1-4567890",
    mobile: "+967-775678901",
    address: " Al-Maziah Street",
    city: "Sana'a",
    region: "Sana'a Governorate",
    country: "Yemen",
    emergencyContactName: "Ali Mohammed",
    emergencyContactPhone: "+967-776789012",
    emergencyContactRelation: "Brother",
    insuranceProvider: "اليمن للتأمين الصحي",
    insurancePolicyNumber: "YHI-GOV-003456",
    insuranceCardNumber: "YHI-77003456-003",
    insuranceExpiry: "2026-12-31",
    coPaymentPercent: "0",
    allergies: [],
    chronicConditions: [
      {
        condition: "Coronary Artery Disease",
        icdCode: "I25.10",
        diagnosedDate: "2020-02-14",
        status: "under treatment",
      },
      {
        condition: "Type 2 Diabetes",
        icdCode: "E11.9",
        diagnosedDate: "2018-05-20",
        status: "managed",
      },
      {
        condition: "Hypertension",
        icdCode: "I10",
        diagnosedDate: "2016-08-10",
        status: "managed",
      },
    ],
    medications: [
      { name: "Metformin 850mg", dosage: "1-0-1", frequency: "Twice daily" },
      { name: "Lisinopril 10mg", dosage: "1-0-0", frequency: "Once daily" },
      { name: "Aspirin 81mg", dosage: "1-0-0", frequency: "Once daily" },
      {
        name: "Atorvastatin 40mg",
        dosage: "0-0-1",
        frequency: "Once daily at night",
      },
    ],
    isVIP: true,
  },
  {
    patientNumber: "PAT-004",
    firstName: "Khaled",
    lastName: "Al-Qadasi",
    localFirstName: "خالد",
    localLastName: "القادسي",
    gender: "male",
    dateOfBirth: "1962-04-30",
    age: 62,
    bloodType: "AB+",
    nationality: "Yemeni",
    nationalId: "ID-1004567890",
    maritalStatus: "married",
    occupation: "Retired Military Officer",
    phone: "+967-1-5678901",
    mobile: "+967-777890123",
    address: " Al-Thawra Street",
    city: "Aden",
    region: "Aden Governorate",
    country: "Yemen",
    emergencyContactName: "Saleh Khaled",
    emergencyContactPhone: "+967-778901234",
    emergencyContactRelation: "Son",
    insuranceProvider: "شركة التأمين اليمنية",
    insurancePolicyNumber: "YIC-MIL-004567",
    insuranceCardNumber: "YIC-77004567-004",
    insuranceExpiry: "2026-09-30",
    coPaymentPercent: "10",
    allergies: [
      { allergen: "Iodine contrast", severity: "moderate", reaction: "Nausea" },
    ],
    chronicConditions: [
      {
        condition: "Benign Prostatic Hyperplasia",
        icdCode: "N40.1",
        diagnosedDate: "2019-07-12",
        status: "monitoring",
      },
      {
        condition: "Osteoarthritis",
        icdCode: "M19.90",
        diagnosedDate: "2017-03-25",
        status: "managed",
      },
    ],
    medications: [
      {
        name: "Tamsulosin 0.4mg",
        dosage: "0-0-1",
        frequency: "Once daily at night",
      },
      { name: "Diclofenac 50mg", dosage: "1-0-1", frequency: "When needed" },
    ],
  },
  // ─── Business Professionals ───────────────────────────────────────────────────
  {
    patientNumber: "PAT-005",
    firstName: "Nabil",
    lastName: "Bamashmoos",
    localFirstName: "نبيل",
    localLastName: "باماشموس",
    gender: "male",
    dateOfBirth: "1985-09-18",
    age: 40,
    bloodType: "O-",
    nationality: "Yemeni",
    nationalId: "ID-1005678901",
    maritalStatus: "married",
    occupation: "Business Owner - Trading",
    email: "nabil@bamashmoos-trading.ye",
    phone: "+967-1-6789012",
    mobile: "+967-779012345",
    address: " Al-Maziah Compound",
    city: "Sana'a",
    region: "Sana'a Governorate",
    country: "Yemen",
    emergencyContactName: "Sarah Nabil",
    emergencyContactPhone: "+967-770123456",
    emergencyContactRelation: "Wife",
    insuranceProvider: "التأمين الصحي الشامل",
    insurancePolicyNumber: "GHI-BUS-005678",
    insuranceCardNumber: "GHI-77005678-005",
    insuranceExpiry: "2026-08-31",
    coPaymentPercent: "20",
    allergies: [],
    chronicConditions: [],
    medications: [],
  },
  {
    patientNumber: "PAT-006",
    firstName: "Rashid",
    lastName: "Al-Emadi",
    localFirstName: "راشد",
    localLastName: "العمدي",
    gender: "male",
    dateOfBirth: "1980-12-05",
    age: 44,
    bloodType: "A-",
    nationality: "Yemeni",
    nationalId: "ID-1006789012",
    maritalStatus: "married",
    occupation: "CEO - Al-Emadi Group",
    email: "rashid@alemadi-group.ye",
    phone: "+967-1-7890123",
    mobile: "+967-771234567",
    address: " Al-Maziah Villa 12",
    city: "Sana'a",
    region: "Sana'a Governorate",
    country: "Yemen",
    emergencyContactName: "Hana Rashid",
    emergencyContactPhone: "+967-772345678",
    emergencyContactRelation: "Wife",
    insuranceProvider: "اليمن للتأمين الصحي",
    insurancePolicyNumber: "YHI-CORP-006789",
    insuranceCardNumber: "YHI-77006789-006",
    insuranceExpiry: "2026-12-31",
    coPaymentPercent: "5",
    allergies: [
      { allergen: "Latex", severity: "mild", reaction: "Contact dermatitis" },
    ],
    chronicConditions: [
      {
        condition: "Migraine",
        icdCode: "G43.9",
        diagnosedDate: "2015-11-20",
        status: "controlled",
      },
    ],
    medications: [
      {
        name: "Sumatriptan 50mg",
        dosage: "As needed",
        frequency: "When migraine starts",
      },
    ],
    isVIP: true,
  },
  // ─── Medical Staff ────────────────────────────────────────────────────────────
  {
    patientNumber: "PAT-007",
    firstName: "Dr. Ameera",
    lastName: "Al-Khorasani",
    localFirstName: "أميرة",
    localLastName: "الخُراساني",
    gender: "female",
    dateOfBirth: "1982-06-14",
    age: 43,
    bloodType: "B-",
    nationality: "Yemeni",
    nationalId: "ID-2007890123",
    maritalStatus: "married",
    occupation: "Cardiologist",
    email: "ameera.khorasani@husseiniya.ye",
    phone: "+967-1-8901234",
    mobile: "+967-773456789",
    address: " Haddah Medical District",
    city: "Sana'a",
    region: "Sana'a Governorate",
    country: "Yemen",
    emergencyContactName: "Dr. Youssef Al-Khorasani",
    emergencyContactPhone: "+967-774567890",
    emergencyContactRelation: "Husband",
    allergies: [],
    chronicConditions: [],
    medications: [],
  },
  {
    patientNumber: "PAT-008",
    firstName: "Dr. Tarek",
    lastName: "Al-Shami",
    localFirstName: "طارق",
    localLastName: "الشامي",
    gender: "male",
    dateOfBirth: "1979-01-28",
    age: 46,
    bloodType: "O+",
    nationality: "Yemeni",
    nationalId: "ID-1008901234",
    maritalStatus: "married",
    occupation: "General Surgeon",
    email: "tarek.shami@husseiniya.ye",
    phone: "+967-1-9012345",
    mobile: "+967-775678901",
    address: " Al-Thawra Medical Complex",
    city: "Sana'a",
    region: "Sana'a Governorate",
    country: "Yemen",
    emergencyContactName: "Layla Tarek",
    emergencyContactPhone: "+967-776789012",
    emergencyContactRelation: "Wife",
    allergies: [
      { allergen: "Codeine", severity: "moderate", reaction: "Severe nausea" },
    ],
    chronicConditions: [],
    medications: [],
  },
  // ─── Women & Children ─────────────────────────────────────────────────────────
  {
    patientNumber: "PAT-009",
    firstName: "Mariam",
    lastName: "Hassan",
    localFirstName: "مريم",
    localLastName: "حسن",
    gender: "female",
    dateOfBirth: "1995-08-20",
    age: 30,
    bloodType: "A+",
    nationality: "Yemeni",
    nationalId: "ID-2009012345",
    maritalStatus: "married",
    occupation: "Teacher",
    email: "mariam.hassan@edu.ye",
    phone: "+967-2-1234567",
    mobile: "+967-777890123",
    address: " Al-Mansoura Street",
    city: "Aden",
    region: "Aden Governorate",
    country: "Yemen",
    emergencyContactName: "Omar Hassan",
    emergencyContactPhone: "+967-778901234",
    emergencyContactRelation: "Husband",
    insuranceProvider: "التأمين الصحي الشامل",
    insurancePolicyNumber: "GHI-FAM-007890",
    insuranceCardNumber: "GHI-77007890-009",
    insuranceExpiry: "2026-05-31",
    coPaymentPercent: "15",
    allergies: [
      { allergen: "NSAIDs", severity: "severe", reaction: "Anaphylaxis" },
    ],
    chronicConditions: [],
    medications: [],
  },
  {
    patientNumber: "PAT-010",
    firstName: "Hana",
    lastName: "Al-Maqtari",
    localFirstName: "هناء",
    localLastName: "المقطري",
    gender: "female",
    dateOfBirth: "1990-03-10",
    age: 35,
    bloodType: "O-",
    nationality: "Yemeni",
    nationalId: "ID-2010123456",
    maritalStatus: "married",
    occupation: "Accountant",
    email: "hana.maqtari@company.ye",
    phone: "+967-1-2345679",
    mobile: "+967-779012345",
    address: " Al-Shaab Street",
    city: "Sana'a",
    region: "Sana'a Governorate",
    country: "Yemen",
    emergencyContactName: "Saif Al-Maqtari",
    emergencyContactPhone: "+967-770123456",
    emergencyContactRelation: "Husband",
    allergies: [
      { allergen: "Bee stings", severity: "moderate", reaction: "Swelling" },
    ],
    chronicConditions: [
      {
        condition: "Gestational Diabetes (history)",
        icdCode: "O24.4",
        diagnosedDate: "2023-06-15",
        status: "resolved",
      },
    ],
    medications: [],
  },
  {
    patientNumber: "PAT-011",
    firstName: "Aisha",
    lastName: "Al-Awlaki",
    localFirstName: "عائشة",
    localLastName: "الأيولي",
    gender: "female",
    dateOfBirth: "1988-11-25",
    age: 37,
    bloodType: "AB+",
    nationality: "Yemeni",
    nationalId: "ID-2011234567",
    maritalStatus: "divorced",
    occupation: "HR Manager",
    email: "aisha.awlaki@corp.ye",
    phone: "+967-1-3456780",
    mobile: "+967-771234567",
    address: " Al-Maziah Street",
    city: "Sana'a",
    region: "Sana'a Governorate",
    country: "Yemen",
    emergencyContactName: "Fatima Al-Awlaki",
    emergencyContactPhone: "+967-772345678",
    emergencyContactRelation: "Mother",
    insuranceProvider: "شركة التأمين اليمنية",
    insurancePolicyNumber: "YIC-CORP-008901",
    insuranceCardNumber: "YIC-77008901-011",
    insuranceExpiry: "2026-10-31",
    coPaymentPercent: "20",
    allergies: [],
    chronicConditions: [
      {
        condition: "Depression",
        icdCode: "F32.9",
        diagnosedDate: "2022-03-10",
        status: "under treatment",
      },
    ],
    medications: [
      {
        name: "Sertraline 50mg",
        dosage: "1-0-0",
        frequency: "Once daily morning",
      },
    ],
  },
  // ─── Pediatric Cases ───────────────────────────────────────────────────────────
  {
    patientNumber: "PAT-012",
    firstName: "Youssef",
    lastName: "Mansoor",
    localFirstName: "يوسف",
    localLastName: "منصور",
    gender: "male",
    dateOfBirth: "2018-04-12",
    age: 7,
    bloodType: "A+",
    nationality: "Yemeni",
    nationalId: "ID-1012345678",
    maritalStatus: "single",
    occupation: "Student",
    phone: "+967-1-4567891",
    mobile: "+967-773456789",
    address: " Al-Thawra District",
    city: "Sana'a",
    region: "Sana'a Governorate",
    country: "Yemen",
    emergencyContactName: "Ahmed Mansoor",
    emergencyContactPhone: "+967-774567890",
    emergencyContactRelation: "Father",
    insuranceProvider: "التأمين الصحي الشامل",
    insurancePolicyNumber: "GHI-PED-009012",
    insuranceCardNumber: "GHI-77009012-012",
    insuranceExpiry: "2026-03-31",
    coPaymentPercent: "10",
    allergies: [
      { allergen: "Amoxicillin", severity: "moderate", reaction: "Rash" },
    ],
    chronicConditions: [],
    medications: [],
  },
  {
    patientNumber: "PAT-013",
    firstName: "Leila",
    lastName: "Nasser",
    localFirstName: "ليلى",
    localLastName: "ناصر",
    gender: "female",
    dateOfBirth: "2020-09-05",
    age: 5,
    bloodType: "O+",
    nationality: "Yemeni",
    nationalId: "ID-1023456789",
    maritalStatus: "single",
    occupation: "Kindergarten",
    phone: "+967-2-2345678",
    mobile: "+967-775678901",
    address: " Khormaksar District",
    city: "Aden",
    region: "Aden Governorate",
    country: "Yemen",
    emergencyContactName: "Nasser Ali",
    emergencyContactPhone: "+967-776789012",
    emergencyContactRelation: "Father",
    allergies: [],
    chronicConditions: [],
    medications: [],
  },
  {
    patientNumber: "PAT-014",
    firstName: "Omar",
    lastName: "Qahtan",
    localFirstName: "عمر",
    localLastName: "قحطان",
    gender: "male",
    dateOfBirth: "2015-07-18",
    age: 10,
    bloodType: "B+",
    nationality: "Yemeni",
    nationalId: "ID-1034567890",
    maritalStatus: "single",
    occupation: "Student",
    phone: "+967-3-3456789",
    mobile: "+967-777890123",
    address: " Taiz Central",
    city: "Taiz",
    region: "Taiz Governorate",
    country: "Yemen",
    emergencyContactName: "Qahtan Mohammed",
    emergencyContactPhone: "+967-778901234",
    emergencyContactRelation: "Father",
    allergies: [
      { allergen: "Peanuts", severity: "severe", reaction: "Anaphylaxis" },
    ],
    chronicConditions: [
      {
        condition: "Asthma",
        icdCode: "J45.20",
        diagnosedDate: "2017-02-10",
        status: "controlled",
      },
    ],
    medications: [
      {
        name: "Montelukast 5mg",
        dosage: "1-0-0",
        frequency: "Once daily evening",
      },
      {
        name: "Salbutamol inhaler",
        dosage: "As needed",
        frequency: "When needed",
      },
    ],
  },
  // ─── Elderly Patients ─────────────────────────────────────────────────────────
  {
    patientNumber: "PAT-015",
    firstName: "Abdulrahman",
    lastName: "Al-Sayyidi",
    localFirstName: "عبدالرحمن",
    localLastName: "السييدي",
    gender: "male",
    dateOfBirth: "1950-02-14",
    age: 75,
    bloodType: "A-",
    nationality: "Yemeni",
    nationalId: "ID-1045678901",
    maritalStatus: "widowed",
    occupation: "Retired",
    phone: "+967-1-5678902",
    mobile: "+967-779012345",
    address: " Old City",
    city: "Sana'a",
    region: "Sana'a Governorate",
    country: "Yemen",
    emergencyContactName: "Khalid Abdulrahman",
    emergencyContactPhone: "+967-770123456",
    emergencyContactRelation: "Son",
    insuranceProvider: "اليمن للتأمين الصحي",
    insurancePolicyNumber: "YHI-SEN-010234",
    insuranceCardNumber: "YHI-77010234-015",
    insuranceExpiry: "2026-12-31",
    coPaymentPercent: "5",
    allergies: [],
    chronicConditions: [
      {
        condition: "Type 2 Diabetes",
        icdCode: "E11.9",
        diagnosedDate: "2005-03-20",
        status: "managed",
      },
      {
        condition: "Hypertension",
        icdCode: "I10",
        diagnosedDate: "2008-06-15",
        status: "managed",
      },
      {
        condition: "Cataract",
        icdCode: "H26.9",
        diagnosedDate: "2019-08-10",
        status: "monitoring",
      },
      {
        condition: "Chronic Kidney Disease Stage 3",
        icdCode: "N18.3",
        diagnosedDate: "2021-01-15",
        status: "monitoring",
      },
    ],
    medications: [
      { name: "Metformin 500mg", dosage: "1-0-1", frequency: "Twice daily" },
      { name: "Amlodipine 10mg", dosage: "1-0-0", frequency: "Once daily" },
      { name: "Ramipril 5mg", dosage: "1-0-0", frequency: "Once daily" },
      {
        name: "Furosemide 40mg",
        dosage: "1-0-0",
        frequency: "Once daily morning",
      },
    ],
  },
  {
    patientNumber: "PAT-016",
    firstName: "Sana",
    lastName: "Al-Ansi",
    localFirstName: "ثنا",
    localLastName: "الأنسي",
    gender: "female",
    dateOfBirth: "1952-08-30",
    age: 72,
    bloodType: "O+",
    nationality: "Yemeni",
    nationalId: "ID-2056789012",
    maritalStatus: "widowed",
    occupation: "Retired Teacher",
    phone: "+967-4-4567890",
    mobile: "+967-771234567",
    address: " Al-Mudhakkir Street",
    city: "Hodeidah",
    region: "Hodeidah Governorate",
    country: "Yemen",
    emergencyContactName: "Amira Sana",
    emergencyContactPhone: "+967-772345678",
    emergencyContactRelation: "Daughter",
    insuranceProvider: "شركة التأمين اليمنية",
    insurancePolicyNumber: "YIC-SEN-011345",
    insuranceCardNumber: "YIC-77011345-016",
    insuranceExpiry: "2026-11-30",
    coPaymentPercent: "10",
    allergies: [
      { allergen: "Aspirin", severity: "moderate", reaction: "GI bleeding" },
    ],
    chronicConditions: [
      {
        condition: "Osteoporosis",
        icdCode: "M81.0",
        diagnosedDate: "2018-05-20",
        status: "managed",
      },
      {
        condition: "Hypertension",
        icdCode: "I10",
        diagnosedDate: "2015-03-10",
        status: "managed",
      },
      {
        condition: "Osteoarthritis",
        icdCode: "M19.90",
        diagnosedDate: "2016-07-15",
        status: "managed",
      },
    ],
    medications: [
      {
        name: "Alendronate 70mg",
        dosage: "1-0-0 weekly",
        frequency: "Once weekly",
      },
      { name: "Losartan 50mg", dosage: "1-0-0", frequency: "Once daily" },
      {
        name: "Calcium + Vitamin D",
        dosage: "1-0-1",
        frequency: "Twice daily",
      },
    ],
  },
  // ─── Chronic Disease Management ───────────────────────────────────────────────
  {
    patientNumber: "PAT-017",
    firstName: "Ahmed",
    lastName: "Ba fadhl",
    localFirstName: "أحمد",
    localLastName: "بافاضل",
    gender: "male",
    dateOfBirth: "1968-05-22",
    age: 57,
    bloodType: "B+",
    nationality: "Yemeni",
    nationalId: "ID-1057890123",
    maritalStatus: "married",
    occupation: "Pharmacist",
    email: "ahmed.bafadhl@pharma.ye",
    phone: "+967-1-6789013",
    mobile: "+967-773456789",
    address: " Al-Maziah Street",
    city: "Sana'a",
    region: "Sana'a Governorate",
    country: "Yemen",
    emergencyContactName: "Mohammed Ahmed",
    emergencyContactPhone: "+967-774567890",
    emergencyContactRelation: "Son",
    insuranceProvider: "التأمين الصحي الشامل",
    insurancePolicyNumber: "GHI-MED-012456",
    insuranceCardNumber: "GHI-77012456-017",
    insuranceExpiry: "2026-07-31",
    coPaymentPercent: "10",
    allergies: [
      { allergen: "Penicillin", severity: "severe", reaction: "Anaphylaxis" },
    ],
    chronicConditions: [
      {
        condition: "Type 2 Diabetes",
        icdCode: "E11.9",
        diagnosedDate: "2010-04-15",
        status: "managed",
      },
      {
        condition: "Hypertension",
        icdCode: "I10",
        diagnosedDate: "2012-08-20",
        status: "managed",
      },
      {
        condition: "Diabetic Neuropathy",
        icdCode: "E11.40",
        diagnosedDate: "2018-02-10",
        status: "under treatment",
      },
    ],
    medications: [
      { name: "Metformin 1000mg", dosage: "1-0-1", frequency: "Twice daily" },
      {
        name: "Glibenclamide 5mg",
        dosage: "1-0-0",
        frequency: "Once daily morning",
      },
      { name: "Amlodipine 5mg", dosage: "1-0-0", frequency: "Once daily" },
      {
        name: "Gabapentin 300mg",
        dosage: "1-1-1",
        frequency: "Three times daily",
      },
    ],
  },
  {
    patientNumber: "PAT-018",
    firstName: "Salim",
    lastName: "Al-Hakimi",
    localFirstName: "سالم",
    localLastName: "الحكمي",
    gender: "male",
    dateOfBirth: "1975-09-08",
    age: 50,
    bloodType: "AB-",
    nationality: "Yemeni",
    nationalId: "ID-1068901234",
    maritalStatus: "married",
    occupation: "Engineer",
    email: "salim.hakimi@eng.ye",
    phone: "+967-1-7890124",
    mobile: "+967-775678901",
    address: " Al-Thawra Street",
    city: "Sana'a",
    region: "Sana'a Governorate",
    country: "Yemen",
    emergencyContactName: "Fatima Salim",
    emergencyContactPhone: "+967-776789012",
    emergencyContactRelation: "Wife",
    insuranceProvider: "اليمن للتأمين الصحي",
    insurancePolicyNumber: "YHI-CORP-013567",
    insuranceCardNumber: "YHI-77013567-018",
    insuranceExpiry: "2026-12-31",
    coPaymentPercent: "15",
    allergies: [],
    chronicConditions: [
      {
        condition: "Rheumatoid Arthritis",
        icdCode: "M05.90",
        diagnosedDate: "2015-06-20",
        status: "under treatment",
      },
      {
        condition: "Anemia - Iron Deficiency",
        icdCode: "D50.9",
        diagnosedDate: "2020-03-15",
        status: "treated",
      },
    ],
    medications: [
      {
        name: "Methotrexate 15mg",
        dosage: "1-0-0 weekly",
        frequency: "Once weekly",
      },
      {
        name: "Folic acid 5mg",
        dosage: "1-0-0 weekly",
        frequency: "Once weekly",
      },
      {
        name: "Ferrous sulfate 325mg",
        dosage: "1-0-0",
        frequency: "Once daily",
      },
      {
        name: "Ibuprofen 400mg",
        dosage: "As needed",
        frequency: "When needed",
      },
    ],
  },
  {
    patientNumber: "PAT-019",
    firstName: "Layla",
    lastName: "Al-Sharjabi",
    localFirstName: "ليلى",
    localLastName: "الشرجبي",
    gender: "female",
    dateOfBirth: "1988-12-15",
    age: 37,
    bloodType: "A-",
    nationality: "Yemeni",
    nationalId: "ID-2078901234",
    maritalStatus: "married",
    occupation: "IT Professional",
    email: "layla.sharjabi@tech.ye",
    phone: "+967-1-8901235",
    mobile: "+967-777890123",
    address: " Haddah Street",
    city: "Sana'a",
    region: "Sana'a Governorate",
    country: "Yemen",
    emergencyContactName: "Omar Al-Sharjabi",
    emergencyContactPhone: "+967-778901234",
    emergencyContactRelation: "Husband",
    insuranceProvider: "التأمين الصحي الشامل",
    insurancePolicyNumber: "GHI-TECH-014678",
    insuranceCardNumber: "GHI-77014678-019",
    insuranceExpiry: "2026-09-30",
    coPaymentPercent: "20",
    allergies: [
      { allergen: "Shellfish", severity: "moderate", reaction: "Urticaria" },
    ],
    chronicConditions: [
      {
        condition: "Systemic Lupus Erythematosus",
        icdCode: "M32.9",
        diagnosedDate: "2019-07-20",
        status: "under treatment",
      },
    ],
    medications: [
      {
        name: "Hydroxychloroquine 200mg",
        dosage: "1-1-0",
        frequency: "Twice daily",
      },
      {
        name: "Prednisone 5mg",
        dosage: "1-0-0",
        frequency: "Once daily morning",
      },
      { name: "Folic acid 1mg", dosage: "1-0-0", frequency: "Once daily" },
    ],
    isVIP: true,
  },
  // ─── Cancer Patients ──────────────────────────────────────────────────────────
  {
    patientNumber: "PAT-020",
    firstName: "Hassan",
    lastName: "Al-Maqtari",
    localFirstName: "حسن",
    localLastName: "المقطري",
    gender: "male",
    dateOfBirth: "1960-06-18",
    age: 65,
    bloodType: "O+",
    nationality: "Yemeni",
    nationalId: "ID-1079012345",
    maritalStatus: "married",
    occupation: "Retired Bank Manager",
    phone: "+967-1-9012346",
    mobile: "+967-779012345",
    address: " Al-Mudhakkir Street",
    city: "Hodeidah",
    region: "Hodeidah Governorate",
    country: "Yemen",
    emergencyContactName: "Tariq Hassan",
    emergencyContactPhone: "+967-770123456",
    emergencyContactRelation: "Son",
    insuranceProvider: "اليمن للتأمين الصحي",
    insurancePolicyNumber: "YHI-ONCO-015789",
    insuranceCardNumber: "YHI-77015789-020",
    insuranceExpiry: "2026-12-31",
    coPaymentPercent: "0",
    allergies: [],
    chronicConditions: [
      {
        condition: "Colorectal Cancer - Stage III",
        icdCode: "C18.9",
        diagnosedDate: "2023-09-10",
        status: "under treatment",
      },
      {
        condition: "Type 2 Diabetes",
        icdCode: "E11.9",
        diagnosedDate: "2015-04-20",
        status: "managed",
      },
    ],
    medications: [
      { name: "Metformin 500mg", dosage: "1-0-1", frequency: "Twice daily" },
      {
        name: "FOLFOX chemotherapy",
        dosage: "Per protocol",
        frequency: "Every 2 weeks",
      },
    ],
    isVIP: true,
  },
  {
    patientNumber: "PAT-021",
    firstName: "Amina",
    lastName: "Binthaj",
    localFirstName: "أمينة",
    localLastName: "بن تهامة",
    gender: "female",
    dateOfBirth: "1975-03-25",
    age: 50,
    bloodType: "B+",
    nationality: "Yemeni",
    nationalId: "ID-2080123456",
    maritalStatus: "married",
    occupation: "Housewife",
    phone: "+967-2-3456789",
    mobile: "+967-771234567",
    address: " Crater District",
    city: "Aden",
    region: "Aden Governorate",
    country: "Yemen",
    emergencyContactName: "Binthaj Mohammed",
    emergencyContactPhone: "+967-772345678",
    emergencyContactRelation: "Husband",
    insuranceProvider: "شركة التأمين اليمنية",
    insurancePolicyNumber: "YIC-ONCO-016890",
    insuranceCardNumber: "YIC-77016890-021",
    insuranceExpiry: "2026-08-31",
    coPaymentPercent: "10",
    allergies: [],
    chronicConditions: [
      {
        condition: "Breast Cancer - Stage II",
        icdCode: "C50.919",
        diagnosedDate: "2024-01-15",
        status: "under treatment",
      },
      {
        condition: "Hypertension",
        icdCode: "I10",
        diagnosedDate: "2020-06-10",
        status: "managed",
      },
    ],
    medications: [
      { name: "Lisinopril 10mg", dosage: "1-0-0", frequency: "Once daily" },
      {
        name: "AC-T chemotherapy",
        dosage: "Per protocol",
        frequency: "Every 3 weeks",
      },
    ],
  },
  // ─── Dialysis Patients ─────────────────────────────────────────────────────────
  {
    patientNumber: "PAT-022",
    firstName: "Ibrahim",
    lastName: "Al-Dhubhani",
    localFirstName: "إبراهيم",
    localLastName: "الضباعي",
    gender: "male",
    dateOfBirth: "1958-11-12",
    age: 67,
    bloodType: "A+",
    nationality: "Yemeni",
    nationalId: "ID-1081234567",
    maritalStatus: "married",
    occupation: "Retired Teacher",
    phone: "+967-3-4567890",
    mobile: "+967-773456789",
    address: " Al-Qahira Street",
    city: "Taiz",
    region: "Taiz Governorate",
    country: "Yemen",
    emergencyContactName: "Abdullah Ibrahim",
    emergencyContactPhone: "+967-774567890",
    emergencyContactRelation: "Son",
    insuranceProvider: "اليمن للتأمين الصحي",
    insurancePolicyNumber: "YHI-RENAL-017901",
    insuranceCardNumber: "YHI-77017901-022",
    insuranceExpiry: "2026-12-31",
    coPaymentPercent: "0",
    allergies: [],
    chronicConditions: [
      {
        condition: "End-Stage Renal Disease",
        icdCode: "N18.6",
        diagnosedDate: "2020-08-15",
        status: "on dialysis",
      },
      {
        condition: "Hypertension",
        icdCode: "I10",
        diagnosedDate: "2010-03-20",
        status: "managed",
      },
      {
        condition: "Secondary Hyperparathyroidism",
        icdCode: "N25.81",
        diagnosedDate: "2021-02-10",
        status: "managed",
      },
    ],
    medications: [
      {
        name: "Sevelamer 800mg",
        dosage: "1-1-1",
        frequency: "Three times daily with meals",
      },
      { name: "Calcitriol 0.25mcg", dosage: "1-0-0", frequency: "Once daily" },
      {
        name: "Epoetin alfa 4000 units",
        dosage: "Per dialysis",
        frequency: "3x weekly",
      },
      { name: "Amlodipine 5mg", dosage: "1-0-0", frequency: "Once daily" },
    ],
  },
  {
    patientNumber: "PAT-023",
    firstName: "Mona",
    lastName: "Al-Mehdar",
    localFirstName: "منى",
    localLastName: "المهدي",
    gender: "female",
    dateOfBirth: "1965-07-30",
    age: 60,
    bloodType: "O-",
    nationality: "Yemeni",
    nationalId: "ID-2092345678",
    maritalStatus: "widowed",
    occupation: "Retired Nurse",
    phone: "+967-1-5678913",
    mobile: "+967-775678901",
    address: " Al-Thawra Street",
    city: "Sana'a",
    region: "Sana'a Governorate",
    country: "Yemen",
    emergencyContactName: "Salim Mona",
    emergencyContactPhone: "+967-776789012",
    emergencyContactRelation: "Son",
    insuranceProvider: "التأمين الصحي الشامل",
    insurancePolicyNumber: "GHI-RENAL-018012",
    insuranceCardNumber: "GHI-77018012-023",
    insuranceExpiry: "2026-11-30",
    coPaymentPercent: "5",
    allergies: [
      {
        allergen: "Contrast dye",
        severity: "moderate",
        reaction: "Nausea and vomiting",
      },
    ],
    chronicConditions: [
      {
        condition: "Chronic Kidney Disease Stage 5",
        icdCode: "N18.5",
        diagnosedDate: "2019-04-20",
        status: "on dialysis",
      },
      {
        condition: "Diabetes Type 2",
        icdCode: "E11.9",
        diagnosedDate: "2008-09-15",
        status: "managed",
      },
      {
        condition: "Hypertension",
        icdCode: "I10",
        diagnosedDate: "2012-01-10",
        status: "managed",
      },
    ],
    medications: [
      { name: "Hemodialysis", dosage: "3x weekly", frequency: "Every session" },
      {
        name: "Insulin Glargine 20 units",
        dosage: "1-0-0",
        frequency: "Once daily night",
      },
      {
        name: "Metformin 500mg",
        dosage: "0-0-1",
        frequency: "Once daily evening",
      },
      { name: " carvedilol 12.5mg", dosage: "1-0-0", frequency: "Once daily" },
    ],
  },
  // ─── Cardiac Patients ───────────────────────────────────────────────────────────
  {
    patientNumber: "PAT-024",
    firstName: "Mahmoud",
    lastName: "Al-Aini",
    localFirstName: "محمود",
    localLastName: "العيني",
    gender: "male",
    dateOfBirth: "1955-01-05",
    age: 70,
    bloodType: "B-",
    nationality: "Yemeni",
    nationalId: "ID-1093456789",
    maritalStatus: "married",
    occupation: "Retired Judge",
    phone: "+967-1-6789014",
    mobile: "+967-777890123",
    address: " Al-Maziah Street",
    city: "Sana'a",
    region: "Sana'a Governorate",
    country: "Yemen",
    emergencyContactName: "Abdulaziz Mahmoud",
    emergencyContactPhone: "+967-778901234",
    emergencyContactRelation: "Son",
    insuranceProvider: "اليمن للتأمين الصحي",
    insurancePolicyNumber: "YHI-CARDIO-019123",
    insuranceCardNumber: "YHI-77019123-024",
    insuranceExpiry: "2026-12-31",
    coPaymentPercent: "5",
    allergies: [],
    chronicConditions: [
      {
        condition: "Atrial Fibrillation",
        icdCode: "I48.91",
        diagnosedDate: "2018-06-15",
        status: "under treatment",
      },
      {
        condition: "Congestive Heart Failure",
        icdCode: "I50.9",
        diagnosedDate: "2019-03-20",
        status: "managed",
      },
      {
        condition: "Hypertension",
        icdCode: "I10",
        diagnosedDate: "2010-08-10",
        status: "managed",
      },
    ],
    medications: [
      { name: "Warfarin 5mg", dosage: "As per INR", frequency: "Once daily" },
      { name: "Carvedilol 25mg", dosage: "1-0-0", frequency: "Once daily" },
      { name: "Lisinopril 20mg", dosage: "1-0-0", frequency: "Once daily" },
      { name: "Furosemide 40mg", dosage: "1-0-0", frequency: "Once daily" },
      { name: "Spironolactone 25mg", dosage: "1-0-0", frequency: "Once daily" },
    ],
    isVIP: true,
  },
  {
    patientNumber: "PAT-025",
    firstName: "Khadija",
    lastName: "Al-Akhfash",
    localFirstName: "خديجة",
    localLastName: "الأخشف",
    gender: "female",
    dateOfBirth: "1970-10-20",
    age: 55,
    bloodType: "A+",
    nationality: "Yemeni",
    nationalId: "ID-2104567890",
    maritalStatus: "married",
    occupation: "School Principal",
    email: "khadija.akhfash@school.ye",
    phone: "+967-2-4567890",
    mobile: "+967-771234567",
    address: " Al-Mansoura",
    city: "Aden",
    region: "Aden Governorate",
    country: "Yemen",
    emergencyContactName: "Al-Akhfash Family",
    emergencyContactPhone: "+967-772345678",
    emergencyContactRelation: "Husband",
    insuranceProvider: "شركة التأمين اليمنية",
    insurancePolicyNumber: "YIC-CARDIO-020234",
    insuranceCardNumber: "YIC-77020234-025",
    insuranceExpiry: "2026-09-30",
    coPaymentPercent: "15",
    allergies: [],
    chronicConditions: [
      {
        condition: "Stable Angina",
        icdCode: "I25.118",
        diagnosedDate: "2021-05-10",
        status: "managed",
      },
      {
        condition: "Hyperlipidemia",
        icdCode: "E78.5",
        diagnosedDate: "2020-02-15",
        status: "managed",
      },
      {
        condition: "Obesity Grade I",
        icdCode: "E66.01",
        diagnosedDate: "2019-08-20",
        status: "weight management",
      },
    ],
    medications: [
      { name: "Aspirin 81mg", dosage: "1-0-0", frequency: "Once daily" },
      {
        name: "Atorvastatin 40mg",
        dosage: "0-0-1",
        frequency: "Once daily night",
      },
      { name: "Metoprolol 50mg", dosage: "1-0-1", frequency: "Twice daily" },
      {
        name: "Isosorbide mononitrate 60mg",
        dosage: "1-0-0",
        frequency: "Once daily morning",
      },
    ],
  },
  // ─── Mental Health Patients ────────────────────────────────────────────────────
  {
    patientNumber: "PAT-026",
    firstName: "Yasser",
    lastName: "Al-Shami",
    localFirstName: "ياسر",
    localLastName: "الشامي",
    gender: "male",
    dateOfBirth: "1992-04-08",
    age: 33,
    bloodType: "O+",
    nationality: "Yemeni",
    nationalId: "ID-1105678901",
    maritalStatus: "single",
    occupation: "Software Developer",
    email: "yasser.shami@tech.ye",
    phone: "+967-1-7890125",
    mobile: "+967-773456789",
    address: " Haddah Tech Hub",
    city: "Sana'a",
    region: "Sana'a Governorate",
    country: "Yemen",
    emergencyContactName: "Saad Al-Shami",
    emergencyContactPhone: "+967-774567890",
    emergencyContactRelation: "Brother",
    insuranceProvider: "التأمين الصحي الشامل",
    insurancePolicyNumber: "GHI-MH-021345",
    insuranceCardNumber: "GHI-77021345-026",
    insuranceExpiry: "2026-06-30",
    coPaymentPercent: "20",
    allergies: [],
    chronicConditions: [
      {
        condition: "Generalized Anxiety Disorder",
        icdCode: "F41.1",
        diagnosedDate: "2023-02-15",
        status: "under treatment",
      },
      {
        condition: "Insomnia",
        icdCode: "G47.00",
        diagnosedDate: "2023-02-15",
        status: "under treatment",
      },
    ],
    medications: [
      {
        name: "Escitalopram 10mg",
        dosage: "1-0-0",
        frequency: "Once daily morning",
      },
      {
        name: "Zolpidem 10mg",
        dosage: "0-0-1 PRN",
        frequency: "When needed for sleep",
      },
    ],
  },
  {
    patientNumber: "PAT-027",
    firstName: "Reem",
    lastName: "Al-Din",
    localFirstName: "ريم",
    localLastName: "الدين",
    gender: "female",
    dateOfBirth: "1998-08-15",
    age: 27,
    bloodType: "A-",
    nationality: "Yemeni",
    nationalId: "ID-2116789012",
    maritalStatus: "single",
    occupation: "Graduate Student",
    email: "reem.din@uni.ye",
    phone: "+967-1-8901236",
    mobile: "+967-775678901",
    address: " Al-Thawra University District",
    city: "Sana'a",
    region: "Sana'a Governorate",
    country: "Yemen",
    emergencyContactName: "Dana Al-Din",
    emergencyContactPhone: "+967-776789012",
    emergencyContactRelation: "Sister",
    insuranceProvider: "اليمن للتأمين الصحي",
    insurancePolicyNumber: "YHI-MH-022456",
    insuranceCardNumber: "YHI-77022456-027",
    insuranceExpiry: "2026-03-31",
    coPaymentPercent: "15",
    allergies: [
      { allergen: "Latex", severity: "mild", reaction: "Contact rash" },
    ],
    chronicConditions: [
      {
        condition: "Bipolar I Disorder",
        icdCode: "F31.9",
        diagnosedDate: "2022-09-10",
        status: "under treatment",
      },
      {
        condition: "Migraine",
        icdCode: "G43.909",
        diagnosedDate: "2020-05-15",
        status: "controlled",
      },
    ],
    medications: [
      {
        name: "Lithium Carbonate 300mg",
        dosage: "1-1-1",
        frequency: "Three times daily",
      },
      {
        name: "Propranolol 40mg",
        dosage: "1-0-0",
        frequency: "Once daily morning",
      },
      {
        name: "Sumatriptan 50mg",
        dosage: "As needed",
        frequency: "When needed",
      },
    ],
  },
  // ─── Surgical Cases ────────────────────────────────────────────────────────────
  {
    patientNumber: "PAT-028",
    firstName: "Talal",
    lastName: "Al-Haddad",
    localFirstName: "طلال",
    localLastName: "الحضرمي",
    gender: "male",
    dateOfBirth: "1983-06-25",
    age: 42,
    bloodType: "B+",
    nationality: "Yemeni",
    nationalId: "ID-1117890123",
    maritalStatus: "married",
    occupation: "Contractor",
    phone: "+967-1-9012347",
    mobile: "+967-777890123",
    address: " Al-Maziah Villa 25",
    city: "Sana'a",
    region: "Sana'a Governorate",
    country: "Yemen",
    emergencyContactName: "Fahd Al-Haddad",
    emergencyContactPhone: "+967-778901234",
    emergencyContactRelation: "Brother",
    insuranceProvider: "شركة التأمين اليمنية",
    insurancePolicyNumber: "YIC-SURG-023567",
    insuranceCardNumber: "YIC-77023567-028",
    insuranceExpiry: "2026-10-31",
    coPaymentPercent: "20",
    allergies: [
      {
        allergen: "General anesthesia",
        severity: "unknown",
        reaction: "To be assessed pre-op",
      },
    ],
    chronicConditions: [
      {
        condition: "Cholelithiasis",
        icdCode: "K80.20",
        diagnosedDate: "2024-10-15",
        status: "awaiting surgery",
      },
    ],
    medications: [],
  },
  {
    patientNumber: "PAT-029",
    firstName: "Nadia",
    lastName: "Al-Hakimi",
    localFirstName: "نادية",
    localLastName: "الحكمي",
    gender: "female",
    dateOfBirth: "1986-02-14",
    age: 39,
    bloodType: "O+",
    nationality: "Yemeni",
    nationalId: "ID-2128901234",
    maritalStatus: "married",
    occupation: "Architect",
    email: "nadia.hakimi@design.ye",
    phone: "+967-1-0123456",
    mobile: "+967-779012345",
    address: " Al-Mudhakkir Street",
    city: "Sana'a",
    region: "Sana'a Governorate",
    country: "Yemen",
    emergencyContactName: "Omar Al-Hakimi",
    emergencyContactPhone: "+967-770123456",
    emergencyContactRelation: "Husband",
    insuranceProvider: "التأمين الصحي الشامل",
    insurancePolicyNumber: "GHI-SURG-024678",
    insuranceCardNumber: "GHI-77024678-029",
    insuranceExpiry: "2026-07-31",
    coPaymentPercent: "15",
    allergies: [
      {
        allergen: "Stitches/sutures",
        severity: "mild",
        reaction: "Delayed wound healing",
      },
    ],
    chronicConditions: [
      {
        condition: "Uterine Fibroids",
        icdCode: "D25.9",
        diagnosedDate: "2024-08-20",
        status: "awaiting myomectomy",
      },
    ],
    medications: [
      {
        name: "Tranexamic acid 500mg",
        dosage: "1-1-1",
        frequency: "During menses",
      },
    ],
  },
  // ─── ENT Cases ─────────────────────────────────────────────────────────────────
  {
    patientNumber: "PAT-030",
    firstName: "Majed",
    lastName: "Bamashmoos",
    localFirstName: "ماجد",
    localLastName: "باماشموس",
    gender: "male",
    dateOfBirth: "2012-11-08",
    age: 13,
    bloodType: "A+",
    nationality: "Yemeni",
    nationalId: "ID-1129012345",
    maritalStatus: "single",
    occupation: "Student",
    phone: "+967-1-1234567",
    mobile: "+967-771234567",
    address: " Al-Thawra District",
    city: "Sana'a",
    region: "Sana'a Governorate",
    country: "Yemen",
    emergencyContactName: "Nabil Majed",
    emergencyContactPhone: "+967-772345678",
    emergencyContactRelation: "Father",
    insuranceProvider: "اليمن للتأمين الصحي",
    insurancePolicyNumber: "YHI-PED-025789",
    insuranceCardNumber: "YHI-77025789-030",
    insuranceExpiry: "2026-12-31",
    coPaymentPercent: "10",
    allergies: [
      { allergen: "Amoxicillin", severity: "moderate", reaction: "Hives" },
    ],
    chronicConditions: [
      {
        condition: "Adenoid Hypertrophy",
        icdCode: "J35.2",
        diagnosedDate: "2024-06-10",
        status: "under treatment",
      },
      {
        condition: "Otitis Media with Effusion",
        icdCode: "H65.90",
        diagnosedDate: "2024-06-10",
        status: "under treatment",
      },
    ],
    medications: [
      { name: "Montelukast 5mg", dosage: "1-0-1", frequency: "Twice daily" },
      {
        name: "Fluticasone nasal spray",
        dosage: "1 spray each nostril",
        frequency: "Once daily",
      },
    ],
  },
  // ─── Orthopedic Cases ─────────────────────────────────────────────────────────
  {
    patientNumber: "PAT-031",
    firstName: "Waleed",
    lastName: "Al-Absi",
    localFirstName: "وليد",
    localLastName: "العبدسي",
    gender: "male",
    dateOfBirth: "1972-08-12",
    age: 53,
    bloodType: "AB+",
    nationality: "Yemeni",
    nationalId: "ID-1130123456",
    maritalStatus: "married",
    occupation: "Police Officer",
    phone: "+967-1-2345670",
    mobile: "+967-773456789",
    address: " Al-Maziah Police Quarter",
    city: "Sana'a",
    region: "Sana'a Governorate",
    country: "Yemen",
    emergencyContactName: "Saleh Al-Absi",
    emergencyContactPhone: "+967-774567890",
    emergencyContactRelation: "Brother",
    insuranceProvider: "شركة التأمين اليمنية",
    insurancePolicyNumber: "YIC-GOV-026890",
    insuranceCardNumber: "YIC-77026890-031",
    insuranceExpiry: "2026-11-30",
    coPaymentPercent: "10",
    allergies: [],
    chronicConditions: [
      {
        condition: "Lumbar Disc Herniation L4-L5",
        icdCode: "M51.26",
        diagnosedDate: "2024-07-20",
        status: "under treatment",
      },
      {
        condition: "Chronic Low Back Pain",
        icdCode: "M54.5",
        diagnosedDate: "2022-03-15",
        status: "under treatment",
      },
    ],
    medications: [
      { name: "Diclofenac 75mg", dosage: "1-0-0", frequency: "Once daily" },
      {
        name: "Baclofen 10mg",
        dosage: "1-1-1",
        frequency: "Three times daily",
      },
      {
        name: "Physiotherapy",
        dosage: "3x weekly",
        frequency: "Referral sent",
      },
    ],
  },
  {
    patientNumber: "PAT-032",
    firstName: "Samira",
    lastName: "Al-Mashreqi",
    localFirstName: "سميرة",
    localLastName: "المشرقي",
    gender: "female",
    dateOfBirth: "1968-04-22",
    age: 57,
    bloodType: "B-",
    nationality: "Yemeni",
    nationalId: "ID-2131234567",
    maritalStatus: "married",
    occupation: "Retired Civil Servant",
    phone: "+967-2-5678901",
    mobile: "+967-775678901",
    address: " Khormaksar",
    city: "Aden",
    region: "Aden Governorate",
    country: "Yemen",
    emergencyContactName: "Faisal Samira",
    emergencyContactPhone: "+967-776789012",
    emergencyContactRelation: "Husband",
    insuranceProvider: "التأمين الصحي الشامل",
    insurancePolicyNumber: "GHI-ORTHO-027901",
    insuranceCardNumber: "GHI-77027901-032",
    insuranceExpiry: "2026-08-31",
    coPaymentPercent: "15",
    allergies: [
      {
        allergen: "Tramadol",
        severity: "moderate",
        reaction: "Severe dizziness",
      },
    ],
    chronicConditions: [
      {
        condition: "Knee Osteoarthritis Bilateral",
        icdCode: "M17.9",
        diagnosedDate: "2020-05-15",
        status: "managed",
      },
      {
        condition: "Osteoporosis",
        icdCode: "M81.0",
        diagnosedDate: "2019-09-20",
        status: "managed",
      },
      {
        condition: "Varicose Veins",
        icdCode: "I83.90",
        diagnosedDate: "2018-02-10",
        status: "monitoring",
      },
    ],
    medications: [
      {
        name: "Paracetamol 500mg",
        dosage: "1-1-1",
        frequency: "Three times daily PRN",
      },
      {
        name: "Glucosamine 500mg",
        dosage: "1-1-1",
        frequency: "Three times daily",
      },
      {
        name: "Alendronate 70mg",
        dosage: "1-0-0 weekly",
        frequency: "Once weekly",
      },
      {
        name: "Compression stockings",
        dosage: "Daily",
        frequency: "Daytime wear",
      },
    ],
  },
  // ─── Gastrointestinal Cases ───────────────────────────────────────────────────
  {
    patientNumber: "PAT-033",
    firstName: "Rami",
    lastName: "Al-Sharif",
    localFirstName: "رامي",
    localLastName: "الشيبي",
    gender: "male",
    dateOfBirth: "1990-01-30",
    age: 35,
    bloodType: "O+",
    nationality: "Yemeni",
    nationalId: "ID-1142345678",
    maritalStatus: "married",
    occupation: "Chef",
    phone: "+967-1-3456781",
    mobile: "+967-777890123",
    address: " Haddah Street",
    city: "Sana'a",
    region: "Sana'a Governorate",
    country: "Yemen",
    emergencyContactName: "Samir Al-Sharif",
    emergencyContactPhone: "+967-778901234",
    emergencyContactRelation: "Brother",
    insuranceProvider: "اليمن للتأمين الصحي",
    insurancePolicyNumber: "YHI-GI-028012",
    insuranceCardNumber: "YHI-77028012-033",
    insuranceExpiry: "2026-05-31",
    coPaymentPercent: "15",
    allergies: [
      { allergen: "Shellfish", severity: "moderate", reaction: "Urticaria" },
    ],
    chronicConditions: [
      {
        condition: "Gastroesophageal Reflux Disease",
        icdCode: "K21.0",
        diagnosedDate: "2022-08-15",
        status: "under treatment",
      },
      {
        condition: "Helicobacter Pylori Infection",
        icdCode: "B96.81",
        diagnosedDate: "2024-09-10",
        status: "being treated",
      },
    ],
    medications: [
      {
        name: "Omeprazole 40mg",
        dosage: "1-0-0",
        frequency: "Once daily morning",
      },
      {
        name: "Metronidazole 500mg",
        dosage: "1-1-1",
        frequency: "Three times daily",
      },
      {
        name: "Clarithromycin 500mg",
        dosage: "1-1-1",
        frequency: "Three times daily",
      },
      {
        name: "Amoxicillin 1g",
        dosage: "1-1-1",
        frequency: "Three times daily",
      },
    ],
  },
  {
    patientNumber: "PAT-034",
    firstName: "Dana",
    lastName: "Al-Sarari",
    localFirstName: "دانة",
    localLastName: "السراري",
    gender: "female",
    dateOfBirth: "2000-09-10",
    age: 25,
    bloodType: "A-",
    nationality: "Yemeni",
    nationalId: "ID-2143456789",
    maritalStatus: "single",
    occupation: "University Student",
    email: "dana.sarari@uni.ye",
    phone: "+967-1-4567892",
    mobile: "+967-771234567",
    address: " Al-Thawra University District",
    city: "Sana'a",
    region: "Sana'a Governorate",
    country: "Yemen",
    emergencyContactName: "Lina Al-Sarari",
    emergencyContactPhone: "+967-772345678",
    emergencyContactRelation: "Sister",
    insuranceProvider: "شركة التأمين اليمنية",
    insurancePolicyNumber: "YIC-GI-029123",
    insuranceCardNumber: "YIC-77029123-034",
    insuranceExpiry: "2026-06-30",
    coPaymentPercent: "20",
    allergies: [],
    chronicConditions: [
      {
        condition: "Irritable Bowel Syndrome - Diarrhea Predominant",
        icdCode: "K58.0",
        diagnosedDate: "2023-04-20",
        status: "under treatment",
      },
    ],
    medications: [
      {
        name: "Hyoscine butylbromide 10mg",
        dosage: "1-1-1 PRN",
        frequency: "When needed",
      },
      { name: "Loperamide 2mg", dosage: "PRN", frequency: "Max 8mg/day" },
    ],
  },
  // ─── Respiratory Cases ────────────────────────────────────────────────────────
  {
    patientNumber: "PAT-035",
    firstName: "Hussein",
    lastName: "Al-Din",
    localFirstName: "حسين",
    localLastName: "الدين",
    gender: "male",
    dateOfBirth: "1960-12-03",
    age: 64,
    bloodType: "B+",
    nationality: "Yemeni",
    nationalId: "ID-1154567890",
    maritalStatus: "married",
    occupation: "Former Smoker",
    phone: "+967-1-5678914",
    mobile: "+967-773456789",
    address: " Al-Mudhakkir Street",
    city: "Sana'a",
    region: "Sana'a Governorate",
    country: "Yemen",
    emergencyContactName: "Ali Hussein",
    emergencyContactPhone: "+967-774567890",
    emergencyContactRelation: "Son",
    insuranceProvider: "التأمين الصحي الشامل",
    insurancePolicyNumber: "GHI-RESP-030234",
    insuranceCardNumber: "GHI-77030234-035",
    insuranceExpiry: "2026-12-31",
    coPaymentPercent: "10",
    allergies: [],
    chronicConditions: [
      {
        condition: "COPD - Moderate",
        icdCode: "J44.1",
        diagnosedDate: "2019-07-15",
        status: "under treatment",
      },
      {
        condition: "Former smoker",
        icdCode: "Z87.891",
        diagnosedDate: "2020-01-10",
        status: "quit 5 years ago",
      },
      {
        condition: "Hypertension",
        icdCode: "I10",
        diagnosedDate: "2017-03-20",
        status: "managed",
      },
    ],
    medications: [
      {
        name: "Tiotropium inhaler 18mcg",
        dosage: "1-0-0",
        frequency: "Once daily",
      },
      {
        name: "Salmeterol/Fluticasone 50/500mcg",
        dosage: "1-0-1",
        frequency: "Twice daily",
      },
      { name: "Amlodipine 5mg", dosage: "1-0-0", frequency: "Once daily" },
    ],
  },
  {
    patientNumber: "PAT-036",
    firstName: "Amal",
    lastName: "Binthaj",
    localFirstName: "أمل",
    localLastName: "بن تهامة",
    gender: "female",
    dateOfBirth: "1993-05-17",
    age: 32,
    bloodType: "O-",
    nationality: "Yemeni",
    nationalId: "ID-2155678901",
    maritalStatus: "married",
    occupation: "Environmental Engineer",
    email: "amal.binthaj@env.ye",
    phone: "+967-1-6789015",
    mobile: "+967-775678901",
    address: " Al-Maziah Street",
    city: "Sana'a",
    region: "Sana'a Governorate",
    country: "Yemen",
    emergencyContactName: "Binthaj Abdullah",
    emergencyContactPhone: "+967-776789012",
    emergencyContactRelation: "Husband",
    insuranceProvider: "اليمن للتأمين الصحي",
    insurancePolicyNumber: "YHI-RESP-031345",
    insuranceCardNumber: "YHI-77031345-036",
    insuranceExpiry: "2026-09-30",
    coPaymentPercent: "15",
    allergies: [
      {
        allergen: "Dust mites",
        severity: "moderate",
        reaction: "Rhinitis and conjunctivitis",
      },
    ],
    chronicConditions: [
      {
        condition: "Allergic Rhinitis",
        icdCode: "J30.1",
        diagnosedDate: "2018-03-10",
        status: "controlled",
      },
      {
        condition: "Mild Intermittent Asthma",
        icdCode: "J45.20",
        diagnosedDate: "2018-03-10",
        status: "controlled",
      },
    ],
    medications: [
      {
        name: "Fluticasone nasal spray",
        dosage: "1 spray each nostril",
        frequency: "Once daily",
      },
      {
        name: "Cetirizine 10mg",
        dosage: "1-0-0",
        frequency: "Once daily evening",
      },
      {
        name: "Salbutamol inhaler",
        dosage: "As needed",
        frequency: "When needed",
      },
    ],
  },
  // ─── Endocrine Cases ──────────────────────────────────────────────────────────
  {
    patientNumber: "PAT-037",
    firstName: "Faisal",
    lastName: "Al-Maqtari",
    localFirstName: "فيصل",
    localLastName: "المقطري",
    gender: "male",
    dateOfBirth: "1978-03-28",
    age: 47,
    bloodType: "A+",
    nationality: "Yemeni",
    nationalId: "ID-1166789012",
    maritalStatus: "married",
    occupation: "Bank Manager",
    email: "faisal.maqtari@bank.ye",
    phone: "+967-1-7890126",
    mobile: "+967-777890123",
    address: " Al-Thawra Street",
    city: "Sana'a",
    region: "Sana'a Governorate",
    country: "Yemen",
    emergencyContactName: "Nadia Faisal",
    emergencyContactPhone: "+967-778901234",
    emergencyContactRelation: "Wife",
    insuranceProvider: "شركة التأمين اليمنية",
    insurancePolicyNumber: "YIC-ENDO-032456",
    insuranceCardNumber: "YIC-77032456-037",
    insuranceExpiry: "2026-08-31",
    coPaymentPercent: "15",
    allergies: [],
    chronicConditions: [
      {
        condition: "Type 2 Diabetes Mellitus",
        icdCode: "E11.9",
        diagnosedDate: "2015-09-20",
        status: "managed",
      },
      {
        condition: "Obesity Grade II",
        icdCode: "E66.02",
        diagnosedDate: "2020-04-15",
        status: "weight management",
      },
      {
        condition: "Prediabetes",
        icdCode: "R73.03",
        diagnosedDate: "2014-01-10",
        status: "resolved - progressed to T2DM",
      },
    ],
    medications: [
      { name: "Metformin 1000mg", dosage: "1-0-1", frequency: "Twice daily" },
      { name: "Sitagliptin 100mg", dosage: "1-0-0", frequency: "Once daily" },
      {
        name: "Semaglutide 1mg injection",
        dosage: "1 injection weekly",
        frequency: "Once weekly",
      },
    ],
    isVIP: true,
  },
  {
    patientNumber: "PAT-038",
    firstName: "Sana",
    lastName: "Al-Ahdal",
    localFirstName: "ثنا",
    localLastName: "الأهدل",
    gender: "female",
    dateOfBirth: "1985-11-05",
    age: 40,
    bloodType: "B+",
    nationality: "Yemeni",
    nationalId: "ID-2167890123",
    maritalStatus: "married",
    occupation: "Dermatologist",
    email: "sana.ahdal@husseiniya.ye",
    phone: "+967-1-8901237",
    mobile: "+967-771234567",
    address: " Haddah Medical District",
    city: "Sana'a",
    region: "Sana'a Governorate",
    country: "Yemen",
    emergencyContactName: "Omar Al-Ahdal",
    emergencyContactPhone: "+967-772345678",
    emergencyContactRelation: "Husband",
    insuranceProvider: "التأمين الصحي الشامل",
    insurancePolicyNumber: "GHI-ENDO-033567",
    insuranceCardNumber: "GHI-77033567-038",
    insuranceExpiry: "2026-11-30",
    coPaymentPercent: "10",
    allergies: [
      { allergen: "Latex", severity: "mild", reaction: "Contact dermatitis" },
    ],
    chronicConditions: [
      {
        condition: "Hashimoto's Thyroiditis",
        icdCode: "E06.3",
        diagnosedDate: "2020-06-15",
        status: "managed",
      },
      {
        condition: "Vitamin D Deficiency",
        icdCode: "E55.9",
        diagnosedDate: "2021-02-10",
        status: "treated",
      },
    ],
    medications: [
      {
        name: "Levothyroxine 100mcg",
        dosage: "1-0-0",
        frequency: "Once daily morning",
      },
      {
        name: "Vitamin D3 5000 IU",
        dosage: "1-0-0 weekly",
        frequency: "Once weekly",
      },
    ],
  },
  // ─── Nephrology Cases ─────────────────────────────────────────────────────────
  {
    patientNumber: "PAT-039",
    firstName: "Saeed",
    lastName: "Al-Amri",
    localFirstName: "سعيد",
    localLastName: "العمري",
    gender: "male",
    dateOfBirth: "1955-07-14",
    age: 70,
    bloodType: "AB-",
    nationality: "Yemeni",
    nationalId: "ID-1178901234",
    maritalStatus: "married",
    occupation: "Retired",
    phone: "+967-4-5678901",
    mobile: "+967-773456789",
    address: " Al-Salakheen Street",
    city: "Hodeidah",
    region: "Hodeidah Governorate",
    country: "Yemen",
    emergencyContactName: "Khalid Saeed",
    emergencyContactPhone: "+967-774567890",
    emergencyContactRelation: "Son",
    insuranceProvider: "اليمن للتأمين الصحي",
    insurancePolicyNumber: "YHI-NEPHRO-034678",
    insuranceCardNumber: "YHI-77034678-039",
    insuranceExpiry: "2026-12-31",
    coPaymentPercent: "5",
    allergies: [
      {
        allergen: "Allopurinol",
        severity: "severe",
        reaction: "Stevens-Johnson Syndrome",
      },
    ],
    chronicConditions: [
      {
        condition: "Chronic Kidney Disease Stage 4",
        icdCode: "N18.4",
        diagnosedDate: "2019-08-20",
        status: "under treatment",
      },
      {
        condition: "Gout - Chronic",
        icdCode: "M1A.90",
        diagnosedDate: "2010-05-15",
        status: "controlled",
      },
      {
        condition: "Benign Prostatic Hyperplasia",
        icdCode: "N40.1",
        diagnosedDate: "2018-03-10",
        status: "monitoring",
      },
      {
        condition: "Hypertension",
        icdCode: "I10",
        diagnosedDate: "2005-02-20",
        status: "managed",
      },
    ],
    medications: [
      { name: "Amlodipine 10mg", dosage: "1-0-0", frequency: "Once daily" },
      { name: "Lisinopril 20mg", dosage: "1-0-0", frequency: "Once daily" },
      { name: "Colchicine 0.5mg", dosage: "1-0-0", frequency: "Once daily" },
      {
        name: "Calcium carbonate 500mg",
        dosage: "1-1-1 with meals",
        frequency: "Three times daily",
      },
    ],
  },
  // ─── Oncology Follow-up Cases ─────────────────────────────────────────────────
  {
    patientNumber: "PAT-040",
    firstName: "Zahra",
    lastName: "Al-Mutawakel",
    localFirstName: "زهرة",
    localLastName: "المتوكل",
    gender: "female",
    dateOfBirth: "1968-02-28",
    age: 57,
    bloodType: "A+",
    nationality: "Yemeni",
    nationalId: "ID-2179012345",
    maritalStatus: "widowed",
    occupation: "Retired Teacher",
    phone: "+967-1-9012348",
    mobile: "+967-775678901",
    address: " Al-Thawra District",
    city: "Sana'a",
    region: "Sana'a Governorate",
    country: "Yemen",
    emergencyContactName: "Fatima Zahra",
    emergencyContactPhone: "+967-776789012",
    emergencyContactRelation: "Daughter",
    insuranceProvider: "التأمين الصحي الشامل",
    insurancePolicyNumber: "GHI-ONCO-FU-035789",
    insuranceCardNumber: "GHI-77035789-040",
    insuranceExpiry: "2026-06-30",
    coPaymentPercent: "5",
    allergies: [],
    chronicConditions: [
      {
        condition: "Breast Cancer - Post-treatment",
        icdCode: "C50.919",
        diagnosedDate: "2021-03-15",
        status: "in remission - follow up",
      },
      {
        condition: "Osteopenia",
        icdCode: "M85.80",
        diagnosedDate: "2022-09-10",
        status: "monitoring",
      },
    ],
    medications: [
      { name: "Tamoxifen 20mg", dosage: "1-0-0", frequency: "Once daily" },
      { name: "Calcium 600mg + D3", dosage: "1-0-0", frequency: "Once daily" },
    ],
  },
  // ─── Uninsured / Private Pay ──────────────────────────────────────────────────
  {
    patientNumber: "PAT-041",
    firstName: "Ahmed",
    lastName: "Al-Dubhani",
    localFirstName: "أحمد",
    localLastName: "الضباعي",
    gender: "male",
    dateOfBirth: "1995-04-22",
    age: 30,
    bloodType: "O+",
    nationality: "Yemeni",
    nationalId: "ID-1180123456",
    maritalStatus: "single",
    occupation: "Taxi Driver",
    phone: "+967-1-0123457",
    mobile: "+967-777890123",
    address: " Al-Shaab Area",
    city: "Sana'a",
    region: "Sana'a Governorate",
    country: "Yemen",
    emergencyContactName: "Mohammed Al-Dubhani",
    emergencyContactPhone: "+967-778901234",
    emergencyContactRelation: "Brother",
    allergies: [],
    chronicConditions: [],
    medications: [],
  },
  {
    patientNumber: "PAT-042",
    firstName: "Mariam",
    lastName: "Al-Hakimi",
    localFirstName: "مريم",
    localLastName: "الحكمي",
    gender: "female",
    dateOfBirth: "1980-08-15",
    age: 45,
    bloodType: "B-",
    nationality: "Yemeni",
    nationalId: "ID-2181234567",
    maritalStatus: "married",
    occupation: "Housewife",
    phone: "+967-3-5678901",
    mobile: "+967-771234567",
    address: " Taiz Old City",
    city: "Taiz",
    region: "Taiz Governorate",
    country: "Yemen",
    emergencyContactName: "Abdulrahman Mariam",
    emergencyContactPhone: "+967-772345678",
    emergencyContactRelation: "Husband",
    allergies: [],
    chronicConditions: [
      {
        condition: "Iron Deficiency Anemia",
        icdCode: "D50.9",
        diagnosedDate: "2024-05-20",
        status: "under treatment",
      },
    ],
    medications: [
      {
        name: "Ferrous sulfate 325mg",
        dosage: "1-0-0",
        frequency: "Once daily",
      },
    ],
  },
  // ─── Additional Patients for Testing ─────────────────────────────────────────
  {
    patientNumber: "PAT-043",
    firstName: "Ali",
    lastName: "Mansoor",
    localFirstName: "علي",
    localLastName: "منصور",
    gender: "male",
    dateOfBirth: "1988-10-05",
    age: 37,
    bloodType: "A-",
    nationality: "Yemeni",
    nationalId: "ID-1192345678",
    maritalStatus: "married",
    occupation: "Electrician",
    phone: "+967-1-1234568",
    mobile: "+967-773456789",
    address: " Al-Mudhakkir Street",
    city: "Sana'a",
    region: "Sana'a Governorate",
    country: "Yemen",
    emergencyContactName: "Mansoor Ali",
    emergencyContactPhone: "+967-774567890",
    emergencyContactRelation: "Father",
    allergies: [
      {
        allergen: "Codeine",
        severity: "moderate",
        reaction: "Severe vomiting",
      },
    ],
    chronicConditions: [
      {
        condition: "Epilepsy - Focal Impaired Awareness",
        icdCode: "G40.209",
        diagnosedDate: "2015-06-20",
        status: "controlled",
      },
    ],
    medications: [
      {
        name: "Levetiracetam 500mg",
        dosage: "1-1-1",
        frequency: "Twice daily",
      },
    ],
  },
  {
    patientNumber: "PAT-044",
    firstName: "Reem",
    lastName: "Al-Houthi",
    localFirstName: "ريم",
    localLastName: " Houthis",
    gender: "female",
    dateOfBirth: "2003-12-20",
    age: 22,
    bloodType: "O-",
    nationality: "Yemeni",
    nationalId: "ID-2193456789",
    maritalStatus: "single",
    occupation: "University Student",
    email: "reem.houthi@uni.ye",
    phone: "+967-1-2345671",
    mobile: "+967-775678901",
    address: " Haddah University Area",
    city: "Sana'a",
    region: "Sana'a Governorate",
    country: "Yemen",
    emergencyContactName: "Al-Houthi Family",
    emergencyContactPhone: "+967-776789012",
    emergencyContactRelation: "Father",
    allergies: [
      { allergen: "Banana", severity: "mild", reaction: "Oral itching" },
    ],
    chronicConditions: [],
    medications: [],
  },
  {
    patientNumber: "PAT-045",
    firstName: "Khalid",
    lastName: "Binthaj",
    localFirstName: "خالد",
    localLastName: "بن تهامة",
    gender: "male",
    dateOfBirth: "1948-06-10",
    age: 77,
    bloodType: "B+",
    nationality: "Yemeni",
    nationalId: "ID-1204567890",
    maritalStatus: "married",
    occupation: "Retired Merchant",
    phone: "+967-2-6789012",
    mobile: "+967-777890123",
    address: " Crater District",
    city: "Aden",
    region: "Aden Governorate",
    country: "Yemen",
    emergencyContactName: "Ahmed Khalid",
    emergencyContactPhone: "+967-778901234",
    emergencyContactRelation: "Son",
    insuranceProvider: "اليمن للتأمين الصحي",
    insurancePolicyNumber: "YHI-GER-036890",
    insuranceCardNumber: "YHI-77036890-045",
    insuranceExpiry: "2026-03-31",
    coPaymentPercent: "5",
    allergies: [],
    chronicConditions: [
      {
        condition: "Parkinson's Disease",
        icdCode: "G20",
        diagnosedDate: "2020-08-15",
        status: "under treatment",
      },
      {
        condition: "Benign Prostatic Hyperplasia",
        icdCode: "N40.1",
        diagnosedDate: "2018-05-20",
        status: "monitoring",
      },
      {
        condition: "Hypertension",
        icdCode: "I10",
        diagnosedDate: "2012-03-10",
        status: "managed",
      },
    ],
    medications: [
      {
        name: "Levodopa/Carbidopa 100/25mg",
        dosage: "1-1-1-1",
        frequency: "Four times daily",
      },
      {
        name: "Entacapone 200mg",
        dosage: "With each Levodopa dose",
        frequency: "With each dose",
      },
      {
        name: "Tamsulosin 0.4mg",
        dosage: "0-0-1",
        frequency: "Once daily evening",
      },
      { name: "Amlodipine 5mg", dosage: "1-0-0", frequency: "Once daily" },
    ],
  },
  // ─── More Complex Cases ───────────────────────────────────────────────────────
  {
    patientNumber: "PAT-046",
    firstName: "Fatima",
    lastName: "Al-Maqtari",
    localFirstName: "فاطمة",
    localLastName: "المقطري",
    gender: "female",
    dateOfBirth: "1972-09-30",
    age: 53,
    bloodType: "A+",
    nationality: "Yemeni",
    nationalId: "ID-2215678901",
    maritalStatus: "married",
    occupation: "Housewife",
    phone: "+967-1-3456782",
    mobile: "+967-771234567",
    address: " Al-Thawra Street",
    city: "Sana'a",
    region: "Sana'a Governorate",
    country: "Yemen",
    emergencyContactName: "Hassan Fatima",
    emergencyContactPhone: "+967-772345678",
    emergencyContactRelation: "Husband",
    allergies: [
      { allergen: "Morphine", severity: "moderate", reaction: "Severe nausea" },
    ],
    chronicConditions: [
      {
        condition: "Multiple Sclerosis - Relapsing Remitting",
        icdCode: "G35.00",
        diagnosedDate: "2018-04-15",
        status: "under treatment",
      },
      {
        condition: "Vitamin B12 Deficiency",
        icdCode: "E53.8",
        diagnosedDate: "2022-07-10",
        status: "treated",
      },
      {
        condition: "Depression",
        icdCode: "F32.9",
        diagnosedDate: "2019-02-20",
        status: "under treatment",
      },
    ],
    medications: [
      {
        name: "Interferon beta-1a 44mcg",
        dosage: "3x weekly",
        frequency: "Injection",
      },
      {
        name: "Vitamin B12 1000mcg",
        dosage: "1-0-0 monthly",
        frequency: "Monthly injection",
      },
      {
        name: "Fluoxetine 20mg",
        dosage: "1-0-0",
        frequency: "Once daily morning",
      },
    ],
  },
  {
    patientNumber: "PAT-047",
    firstName: "Youssef",
    lastName: "Al-Shami",
    localFirstName: "يوسف",
    localLastName: "الشامي",
    gender: "male",
    dateOfBirth: "2008-07-12",
    age: 17,
    bloodType: "O+",
    nationality: "Yemeni",
    nationalId: "ID-1216789012",
    maritalStatus: "single",
    occupation: "High School Student",
    phone: "+967-1-4567893",
    mobile: "+967-773456789",
    address: " Al-Maziah Street",
    city: "Sana'a",
    region: "Sana'a Governorate",
    country: "Yemen",
    emergencyContactName: "Tarek Youssef",
    emergencyContactPhone: "+967-774567890",
    emergencyContactRelation: "Father",
    insuranceProvider: "شركة التأمين اليمنية",
    insurancePolicyNumber: "YIC-PED-037901",
    insuranceCardNumber: "YIC-77037901-047",
    insuranceExpiry: "2026-12-31",
    coPaymentPercent: "10",
    allergies: [],
    chronicConditions: [
      {
        condition: "Type 1 Diabetes Mellitus",
        icdCode: "E10.9",
        diagnosedDate: "2020-11-15",
        status: "under treatment",
      },
      {
        condition: "Celiac Disease",
        icdCode: "K90.0",
        diagnosedDate: "2021-03-20",
        status: "on gluten-free diet",
      },
    ],
    medications: [
      {
        name: "Insulin Aspart",
        dosage: "Per carb counting",
        frequency: "With meals",
      },
      {
        name: "Insulin Glargine 20 units",
        dosage: "1-0-0",
        frequency: "Once daily night",
      },
    ],
    familyHistory: "Mother: Type 2 Diabetes. Father: No significant history.",
  },
  {
    patientNumber: "PAT-048",
    firstName: "Salma",
    lastName: "Al-Awbali",
    localFirstName: "سلمى",
    localLastName: "الأوعبي",
    gender: "female",
    dateOfBirth: "1992-05-08",
    age: 33,
    bloodType: "AB+",
    nationality: "Yemeni",
    nationalId: "ID-2227890123",
    maritalStatus: "single",
    occupation: "Nurse",
    email: "salma.awbali@hospital.ye",
    phone: "+967-1-5678915",
    mobile: "+967-775678901",
    address: " Al-Thawra Medical District",
    city: "Sana'a",
    region: "Sana'a Governorate",
    country: "Yemen",
    emergencyContactName: "Al-Awbali Family",
    emergencyContactPhone: "+967-776789012",
    emergencyContactRelation: "Father",
    allergies: [
      {
        allergen: "Chlorhexidine",
        severity: "moderate",
        reaction: "Contact dermatitis",
      },
    ],
    chronicConditions: [
      {
        condition: "Polycystic Ovary Syndrome",
        icdCode: "E28.2",
        diagnosedDate: "2018-09-15",
        status: "managed",
      },
      {
        condition: "Insulin Resistance",
        icdCode: "R73.03",
        diagnosedDate: "2018-09-15",
        status: "managed",
      },
    ],
    medications: [
      { name: "Metformin 500mg", dosage: "1-0-1", frequency: "Twice daily" },
      {
        name: "Spironolactone 25mg",
        dosage: "1-0-0",
        frequency: "Once daily morning",
      },
    ],
  },
  // ─── Final Batch ──────────────────────────────────────────────────────────────
  {
    patientNumber: "PAT-049",
    firstName: "Omar",
    lastName: "Al-Emadi",
    localFirstName: "عمر",
    localLastName: "العمدي",
    gender: "male",
    dateOfBirth: "2016-03-25",
    age: 9,
    bloodType: "B-",
    nationality: "Yemeni",
    nationalId: "ID-1228901234",
    maritalStatus: "single",
    occupation: "Student",
    phone: "+967-1-6789016",
    mobile: "+967-771234567",
    address: " Al-Maziah Compound",
    city: "Sana'a",
    region: "Sana'a Governorate",
    country: "Yemen",
    emergencyContactName: "Rashid Omar",
    emergencyContactPhone: "+967-772345678",
    emergencyContactRelation: "Father",
    insuranceProvider: "اليمن للتأمين الصحي",
    insurancePolicyNumber: "YHI-VIP-CHILD-038012",
    insuranceCardNumber: "YHI-77038012-049",
    insuranceExpiry: "2026-12-31",
    coPaymentPercent: "5",
    allergies: [
      { allergen: "Eggs", severity: "moderate", reaction: "Urticaria" },
    ],
    chronicConditions: [
      {
        condition: "Attention Deficit Hyperactivity Disorder",
        icdCode: "F90.9",
        diagnosedDate: "2022-09-10",
        status: "under treatment",
      },
    ],
    medications: [
      {
        name: "Methylphenidate 5mg",
        dosage: "1-0-0",
        frequency: "Once daily morning",
      },
    ],
    isVIP: true,
  },
  {
    patientNumber: "PAT-050",
    firstName: "Nadia",
    lastName: "Al-Din",
    localFirstName: "نادية",
    localLastName: "الدين",
    gender: "female",
    dateOfBirth: "1962-11-18",
    age: 62,
    bloodType: "A-",
    nationality: "Yemeni",
    nationalId: "ID-2239012345",
    maritalStatus: "widowed",
    occupation: "Retired Professor",
    email: "nadia.din@retired.ye",
    phone: "+967-1-7890127",
    mobile: "+967-773456789",
    address: " Haddah Street",
    city: "Sana'a",
    region: "Sana'a Governorate",
    country: "Yemen",
    emergencyContactName: "Youssef Nadia",
    emergencyContactPhone: "+967-774567890",
    emergencyContactRelation: "Son",
    insuranceProvider: "شركة التأمين اليمنية",
    insurancePolicyNumber: "YIC-GER-039123",
    insuranceCardNumber: "YIC-77039123-050",
    insuranceExpiry: "2026-09-30",
    coPaymentPercent: "10",
    allergies: [],
    chronicConditions: [
      {
        condition: "Osteoporosis with Pathological Fracture",
        icdCode: "M80.00XA",
        diagnosedDate: "2023-06-20",
        status: "post-treatment",
      },
      {
        condition: "Degenerative Scoliosis",
        icdCode: "M53.2",
        diagnosedDate: "2020-04-15",
        status: "managed",
      },
      {
        condition: "Glaucoma - Open Angle",
        icdCode: "H40.10",
        diagnosedDate: "2019-11-10",
        status: "under treatment",
      },
    ],
    medications: [
      {
        name: "Denosumab 60mg",
        dosage: "1 injection",
        frequency: "Every 6 months",
      },
      {
        name: "Calcium + Vitamin D",
        dosage: "1-0-1",
        frequency: "Twice daily",
      },
      {
        name: "Timolol 0.5% eye drops",
        dosage: "1 drop each eye",
        frequency: "Twice daily",
      },
      {
        name: "Latanoprost 0.005% eye drops",
        dosage: "1 drop each eye",
        frequency: "Once daily night",
      },
    ],
  },
];
