import type { SeedFacility } from "./healthcareTenantData";

// Healthcare Facilities - Yemen & Gulf Region Standards
// Realistic medical facilities following Yemeni Ministry of Health (MOH) and GCC standards
export const healthcareFacilities: SeedFacility[] = [
  // ─── Main Hospital Departments ──────────────────────────────────────
  {
    code: "HOSP-ER",
    name: "Emergency Department",
    nameAr: "قسم الطوارئ",
    type: "hospital",
    specialty: "emergency",
    department: "Emergency",
    floor: "Ground",
    building: "Main Building",
    acceptsInsurance: true,
    insuranceProviders: [
      "اليمن للتأمين",
      "التأمين الصحي الشامل",
      "شركة التأمين اليمنية",
    ],
    operatingHours: { "0-6": "24 hours", "7-23": "24 hours" },
    contactPhone: "+967-1-234-5678",
    contactEmail: "emergency@husseiniya-health.com",
    notes: "24/7 Emergency services with ambulance",
  },
  {
    code: "HOSP-ICU",
    name: "Intensive Care Unit",
    nameAr: "وحدة العناية المركزة",
    type: "hospital",
    specialty: "critical_care",
    department: "ICU",
    floor: "2nd",
    building: "Main Building",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "0-6": "24 hours", "7-23": "24 hours" },
    contactPhone: "+967-1-234-5679",
    contactEmail: "icu@husseiniya-health.com",
    notes: "12-bed ICU with ventilators",
  },
  {
    code: "HOSP-OR",
    name: "Operating Rooms",
    nameAr: "غرف العمليات",
    type: "hospital",
    specialty: "surgery",
    department: "Surgery",
    floor: "3rd",
    building: "Surgical Wing",
    acceptsInsurance: true,
    insuranceProviders: [
      "اليمن للتأمين",
      "التأمين الصحي الشامل",
      "شركة التأمين اليمنية",
    ],
    operatingHours: { "0-6": "24 hours", "7-23": "24 hours" },
    contactPhone: "+967-1-234-5680",
    contactEmail: "or@husseiniya-health.com",
    notes: "5 state-of-the-art operating rooms",
  },
  {
    code: "HOSP-MAT",
    name: "Maternity Ward",
    nameAr: "قسم الولادة",
    type: "hospital",
    specialty: "obstetrics",
    department: "Women's Health",
    floor: "4th",
    building: "Women's Wing",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "0-6": "24 hours", "7-23": "24 hours" },
    contactPhone: "+967-1-234-5681",
    contactEmail: "maternity@husseiniya-health.com",
    notes: "Labor, delivery, recovery rooms (LDR)",
  },
  {
    code: "HOSP-NICU",
    name: "Neonatal ICU",
    nameAr: "العناية المركزة لحديثي الولادة",
    type: "hospital",
    specialty: "neonatology",
    department: "Women's Health",
    floor: "4th",
    building: "Women's Wing",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "0-6": "24 hours", "7-23": "24 hours" },
    contactPhone: "+967-1-234-5682",
    contactEmail: "nicu@husseiniya-health.com",
    notes: "Specialized care for premature infants",
  },
  {
    code: "HOSP-PICU",
    name: "Pediatric ICU",
    nameAr: "العناية المركزة للأطفال",
    type: "hospital",
    specialty: "pediatrics",
    department: "Pediatrics",
    floor: "5th",
    building: "Pediatric Wing",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "0-6": "24 hours", "7-23": "24 hours" },
    contactPhone: "+967-1-234-5683",
    contactEmail: "picu@husseiniya-health.com",
    notes: "Specialized pediatric critical care",
  },
  {
    code: "HOSP-IPD",
    name: "Inpatient Departments",
    nameAr: "الأقسام الداخلية",
    type: "hospital",
    specialty: null,
    department: "Inpatient",
    floor: "5th-8th",
    building: "Main Building",
    acceptsInsurance: true,
    insuranceProviders: [
      "اليمن للتأمين",
      "التأمين الصحي الشامل",
      "شركة التأمين اليمنية",
    ],
    operatingHours: { "0-6": "24 hours", "7-23": "24 hours" },
    contactPhone: "+967-1-234-5684",
    contactEmail: "ipd@husseiniya-health.com",
    notes: "200-bed capacity general wards",
  },

  // ─── Outpatient Clinics ──────────────────────────────────────────────
  {
    code: "CLINIC-GP",
    name: "General Practice Clinic",
    nameAr: "عيادة الطب العام",
    type: "clinic",
    specialty: "general_practice",
    department: "Outpatient",
    floor: "Ground",
    building: "Outpatient Building",
    acceptsInsurance: true,
    insuranceProviders: [
      "اليمن للتأمين",
      "التأمين الصحي الشامل",
      "شركة التأمين اليمنية",
    ],
    operatingHours: { "sat-thu": "08:00-20:00", fri: "10:00-18:00" },
    contactPhone: "+967-1-234-5700",
    contactEmail: "gp@husseiniya-health.com",
    notes: "Primary care services",
  },
  {
    code: "CLINIC-FAMILY",
    name: "Family Medicine Clinic",
    nameAr: "عيادة طب الأسرة",
    type: "clinic",
    specialty: "family_medicine",
    department: "Outpatient",
    floor: "Ground",
    building: "Outpatient Building",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "sat-thu": "08:00-20:00", fri: "10:00-18:00" },
    contactPhone: "+967-1-234-5701",
    contactEmail: "family@husseiniya-health.com",
    notes: "Family and community health",
  },
  {
    code: "CLINIC-IM",
    name: "Internal Medicine Clinic",
    nameAr: "عيادة الباطنية",
    type: "clinic",
    specialty: "internal_medicine",
    department: "Outpatient",
    floor: "1st",
    building: "Outpatient Building",
    acceptsInsurance: true,
    insuranceProviders: [
      "اليمن للتأمين",
      "التأمين الصحي الشامل",
      "شركة التأمين اليمنية",
    ],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5702",
    contactEmail: "internal@husseiniya-health.com",
    notes: "Adult internal medicine specialists",
  },
  {
    code: "CLINIC-CARDIO",
    name: "Cardiology Clinic",
    nameAr: "عيادة القلب",
    type: "clinic",
    specialty: "cardiology",
    department: "Cardiology Center",
    floor: "2nd",
    building: "Specialty Building",
    acceptsInsurance: true,
    insuranceProviders: [
      "اليمن للتأمين",
      "التأمين الصحي الشامل",
      "شركة التأمين اليمنية",
    ],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5703",
    contactEmail: "cardiology@husseiniya-health.com",
    notes: "Heart and cardiovascular care",
  },
  {
    code: "CLINIC-NEURO",
    name: "Neurology Clinic",
    nameAr: "عيادة الأعصاب",
    type: "clinic",
    specialty: "neurology",
    department: "Neurosciences",
    floor: "2nd",
    building: "Specialty Building",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5704",
    contactEmail: "neurology@husseiniya-health.com",
    notes: "Brain and nervous system disorders",
  },
  {
    code: "CLINIC-GASTRO",
    name: "Gastroenterology Clinic",
    nameAr: "عيادة الجهاز الهضمي",
    type: "clinic",
    specialty: "gastroenterology",
    department: "Outpatient",
    floor: "1st",
    building: "Outpatient Building",
    acceptsInsurance: true,
    insuranceProviders: [
      "اليمن للتأمين",
      "التأمين الصحي الشامل",
      "شركة التأمين اليمنية",
    ],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5705",
    contactEmail: "gastro@husseiniya-health.com",
    notes: "Digestive system disorders",
  },
  {
    code: "CLINIC-NEPHRO",
    name: "Nephrology Clinic",
    nameAr: "عيادة الكلى",
    type: "clinic",
    specialty: "nephrology",
    department: "Outpatient",
    floor: "1st",
    building: "Outpatient Building",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5706",
    contactEmail: "nephrology@husseiniya-health.com",
    notes: "Kidney diseases and dialysis",
  },
  {
    code: "CLINIC-ENDO",
    name: "Endocrinology Clinic",
    nameAr: "عيادة الغدد الصماء",
    type: "clinic",
    specialty: "endocrinology",
    department: "Outpatient",
    floor: "1st",
    building: "Outpatient Building",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5707",
    contactEmail: "endocrinology@husseiniya-health.com",
    notes: "Hormonal and metabolic disorders",
  },
  {
    code: "CLINIC-PULMO",
    name: "Pulmonology Clinic",
    nameAr: "عيادة الصدر",
    type: "clinic",
    specialty: "pulmonology",
    department: "Outpatient",
    floor: "1st",
    building: "Outpatient Building",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5708",
    contactEmail: "pulmonology@husseiniya-health.com",
    notes: "Lung and respiratory care",
  },
  {
    code: "CLINIC-RHEUM",
    name: "Rheumatology Clinic",
    nameAr: "عيادة الروماتيزم",
    type: "clinic",
    specialty: "rheumatology",
    department: "Outpatient",
    floor: "2nd",
    building: "Specialty Building",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5709",
    contactEmail: "rheumatology@husseiniya-health.com",
    notes: "Joint and autoimmune disorders",
  },
  {
    code: "CLINIC-DERMA",
    name: "Dermatology Clinic",
    nameAr: "عيادة الجلدية",
    type: "clinic",
    specialty: "dermatology",
    department: "Outpatient",
    floor: "Ground",
    building: "Outpatient Building",
    acceptsInsurance: true,
    insuranceProviders: [
      "اليمن للتأمين",
      "التأمين الصحي الشامل",
      "شركة التأمين اليمنية",
    ],
    operatingHours: { "sat-thu": "08:00-20:00", fri: "10:00-18:00" },
    contactPhone: "+967-1-234-5710",
    contactEmail: "dermatology@husseiniya-health.com",
    notes: "Skin, hair, and nail conditions",
  },
  {
    code: "CLINIC-ALLERGY",
    name: "Allergy & Immunology Clinic",
    nameAr: "عيادة الحساسية والمناعة",
    type: "clinic",
    specialty: "allergy",
    department: "Outpatient",
    floor: "Ground",
    building: "Outpatient Building",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5711",
    contactEmail: "allergy@husseiniya-health.com",
    notes: "Allergies and immune disorders",
  },
  {
    code: "CLINIC-INFEC",
    name: "Infectious Diseases Clinic",
    nameAr: "عيادة الأمراض المعدية",
    type: "clinic",
    specialty: "infectious_diseases",
    department: "Outpatient",
    floor: "1st",
    building: "Outpatient Building",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5712",
    contactEmail: "infectious@husseiniya-health.com",
    notes: "Infection control and treatment",
  },
  {
    code: "CLINIC-ONCO",
    name: "Oncology Clinic",
    nameAr: "عيادة الأورام",
    type: "clinic",
    specialty: "oncology",
    department: "Cancer Center",
    floor: "3rd",
    building: "Cancer Center",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5713",
    contactEmail: "oncology@husseiniya-health.com",
    notes: "Cancer diagnosis and treatment",
  },
  {
    code: "CLINIC-HEMA",
    name: "Hematology Clinic",
    nameAr: "عيادة الدم",
    type: "clinic",
    specialty: "hematology",
    department: "Outpatient",
    floor: "2nd",
    building: "Specialty Building",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5714",
    contactEmail: "hematology@husseiniya-health.com",
    notes: "Blood disorders and diseases",
  },
  {
    code: "CLINIC-PSYCH",
    name: "Psychiatry Clinic",
    nameAr: "عيادة الطب النفسي",
    type: "clinic",
    specialty: "psychiatry",
    department: "Mental Health",
    floor: "4th",
    building: "Mental Health Center",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5715",
    contactEmail: "psychiatry@husseiniya-health.com",
    notes: "Mental health services",
  },
  {
    code: "CLINIC-PSYCHO",
    name: "Psychology Clinic",
    nameAr: "عيادة علم النفس",
    type: "clinic",
    specialty: "psychology",
    department: "Mental Health",
    floor: "4th",
    building: "Mental Health Center",
    acceptsInsurance: false,
    insuranceProviders: [],
    operatingHours: { "sat-thu": "09:00-17:00", fri: "Closed" },
    contactPhone: "+967-1-234-5716",
    contactEmail: "psychology@husseiniya-health.com",
    notes: "Psychological counseling",
  },

  // ─── Surgical Specialties ─────────────────────────────────────────────
  {
    code: "CLINIC-GENSURG",
    name: "General Surgery Clinic",
    nameAr: "عيادة الجراحة العامة",
    type: "clinic",
    specialty: "general_surgery",
    department: "Surgery",
    floor: "2nd",
    building: "Surgical Building",
    acceptsInsurance: true,
    insuranceProviders: [
      "اليمن للتأمين",
      "التأمين الصحي الشامل",
      "شركة التأمين اليمنية",
    ],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5720",
    contactEmail: "gensurgery@husseiniya-health.com",
    notes: "General surgical procedures",
  },
  {
    code: "CLINIC-VASC",
    name: "Vascular Surgery Clinic",
    nameAr: "عيادة جراحة الأوعية الدموية",
    type: "clinic",
    specialty: "vascular_surgery",
    department: "Surgery",
    floor: "2nd",
    building: "Surgical Building",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5721",
    contactEmail: "vascular@husseiniya-health.com",
    notes: "Blood vessel surgery",
  },
  {
    code: "CLINIC-NEUROSURG",
    name: "Neurosurgery Clinic",
    nameAr: "عيادة جراحة الأعصاب",
    type: "clinic",
    specialty: "neurosurgery",
    department: "Neurosciences",
    floor: "3rd",
    building: "Surgical Building",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5722",
    contactEmail: "neurosurgery@husseiniya-health.com",
    notes: "Brain and spine surgery",
  },
  {
    code: "CLINIC-ORTHO",
    name: "Orthopedics Clinic",
    nameAr: "عيادة العظام",
    type: "clinic",
    specialty: "orthopedics",
    department: "Orthopedics",
    floor: "2nd",
    building: "Surgical Building",
    acceptsInsurance: true,
    insuranceProviders: [
      "اليمن للتأمين",
      "التأمين الصحي الشامل",
      "شركة التأمين اليمنية",
    ],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5723",
    contactEmail: "orthopedics@husseiniya-health.com",
    notes: "Bone, joint, and muscle care",
  },
  {
    code: "CLINIC-OTOLO",
    name: "Otorhinolaryngology (ENT) Clinic",
    nameAr: "عيادة الأنف والأذن والحنجرة",
    type: "clinic",
    specialty: "otolaryngology",
    department: "ENT",
    floor: "Ground",
    building: "Outpatient Building",
    acceptsInsurance: true,
    insuranceProviders: [
      "اليمن للتأمين",
      "التأمين الصحي الشامل",
      "شركة التأمين اليمنية",
    ],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5724",
    contactEmail: "ent@husseiniya-health.com",
    notes: "Ear, nose, throat care",
  },
  {
    code: "CLINIC-OPHTH",
    name: "Ophthalmology Clinic",
    nameAr: "عيادة العيون",
    type: "clinic",
    specialty: "ophthalmology",
    department: "Eye Center",
    floor: "Ground",
    building: "Eye Center",
    acceptsInsurance: true,
    insuranceProviders: [
      "اليمن للتأمين",
      "التأمين الصحي الشامل",
      "شركة التأمين اليمنية",
    ],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5725",
    contactEmail: "ophthalmology@husseiniya-health.com",
    notes: "Eye care and surgery",
  },
  {
    code: "CLINIC-URO",
    name: "Urology Clinic",
    nameAr: "عيادة المسالك البولية",
    type: "clinic",
    specialty: "urology",
    department: "Urology",
    floor: "2nd",
    building: "Surgical Building",
    acceptsInsurance: true,
    insuranceProviders: [
      "اليمن للتأمين",
      "التأمين الصحي الشامل",
      "شركة التأمين اليمنية",
    ],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5726",
    contactEmail: "urology@husseiniya-health.com",
    notes: "Urinary system care",
  },
  {
    code: "CLINIC-PLAST",
    name: "Plastic Surgery Clinic",
    nameAr: "عيادة الجراحة التجميلية",
    type: "clinic",
    specialty: "plastic_surgery",
    department: "Surgery",
    floor: "3rd",
    building: "Surgical Building",
    acceptsInsurance: false,
    insuranceProviders: [],
    operatingHours: { "sat-thu": "09:00-17:00", fri: "Closed" },
    contactPhone: "+967-1-234-5727",
    contactEmail: "plasticsurgery@husseiniya-health.com",
    notes: "Cosmetic and reconstructive surgery",
  },
  {
    code: "CLINIC-CARDIOVASC",
    name: "Cardiothoracic Surgery Clinic",
    nameAr: "عيادة جراحة القلب والصدر",
    type: "clinic",
    specialty: "cardiothoracic_surgery",
    department: "Cardiology Center",
    floor: "3rd",
    building: "Specialty Building",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5728",
    contactEmail: "cardiothoracic@husseiniya-health.com",
    notes: "Heart and chest surgery",
  },
  {
    code: "CLINIC-BURN",
    name: "Burns Unit",
    nameAr: "وحدة الحروق",
    type: "hospital",
    specialty: "burns",
    department: "Surgery",
    floor: "2nd",
    building: "Specialty Building",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "0-6": "24 hours", "7-23": "24 hours" },
    contactPhone: "+967-1-234-5729",
    contactEmail: "burns@husseiniya-health.com",
    notes: "Specialized burn care",
  },

  // ─── Women's Health ──────────────────────────────────────────────────
  {
    code: "CLINIC-OBGYN",
    name: "Obstetrics & Gynecology Clinic",
    nameAr: "عيادة النساء والولادة",
    type: "clinic",
    specialty: "obstetrics_gynecology",
    department: "Women's Health",
    floor: "1st",
    building: "Women's Wing",
    acceptsInsurance: true,
    insuranceProviders: [
      "اليمن للتأمين",
      "التأمين الصحي الشامل",
      "شركة التأمين اليمنية",
    ],
    operatingHours: { "sat-thu": "08:00-20:00", fri: "10:00-18:00" },
    contactPhone: "+967-1-234-5730",
    contactEmail: "obgyn@husseiniya-health.com",
    notes: "Women's health services",
  },
  {
    code: "CLINIC-IVF",
    name: "IVF & Infertility Clinic",
    nameAr: "عيادة أطفال الأنابيب والعقم",
    type: "clinic",
    specialty: "reproductive_medicine",
    department: "Women's Health",
    floor: "2nd",
    building: "Women's Wing",
    acceptsInsurance: false,
    insuranceProviders: [],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5731",
    contactEmail: "ivf@husseiniya-health.com",
    notes: "Fertility treatment services",
  },
  {
    code: "CLINIC-MAMMO",
    name: "Breast Health Clinic",
    nameAr: "عيادة صحة الثدي",
    type: "clinic",
    specialty: "breast_health",
    department: "Women's Health",
    floor: "1st",
    building: "Women's Wing",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5732",
    contactEmail: "breasthealth@husseiniya-health.com",
    notes: "Breast cancer screening and care",
  },

  // ─── Pediatrics ───────────────────────────────────────────────────────
  {
    code: "CLINIC-PED",
    name: "Pediatrics Clinic",
    nameAr: "عيادة الأطفال",
    type: "clinic",
    specialty: "pediatrics",
    department: "Pediatrics",
    floor: "Ground",
    building: "Pediatric Wing",
    acceptsInsurance: true,
    insuranceProviders: [
      "اليمن للتأمين",
      "التأمين الصحي الشامل",
      "شركة التأمين اليمنية",
    ],
    operatingHours: { "sat-thu": "08:00-20:00", fri: "10:00-18:00" },
    contactPhone: "+967-1-234-5740",
    contactEmail: "pediatrics@husseiniya-health.com",
    notes: "Children's health services",
  },
  {
    code: "CLINIC-PEDDEV",
    name: "Developmental Pediatrics Clinic",
    nameAr: "عيادة نمو الأطفال",
    type: "clinic",
    specialty: "developmental_pediatrics",
    department: "Pediatrics",
    floor: "1st",
    building: "Pediatric Wing",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5741",
    contactEmail: "developmental@husseiniya-health.com",
    notes: "Child development assessment",
  },
  {
    code: "CLINIC-PEDNEPHO",
    name: "Pediatric Nephrology Clinic",
    nameAr: "عيادة كلى الأطفال",
    type: "clinic",
    specialty: "pediatric_nephrology",
    department: "Pediatrics",
    floor: "1st",
    building: "Pediatric Wing",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5742",
    contactEmail: "pednephro@husseiniya-health.com",
    notes: "Kidney care for children",
  },
  {
    code: "CLINIC-PEDCARDIO",
    name: "Pediatric Cardiology Clinic",
    nameAr: "عيادة قلب الأطفال",
    type: "clinic",
    specialty: "pediatric_cardiology",
    department: "Pediatrics",
    floor: "1st",
    building: "Pediatric Wing",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5743",
    contactEmail: "pedcardio@husseiniya-health.com",
    notes: "Heart care for children",
  },
  {
    code: "CLINIC-NEONAT",
    name: "Neonatology Clinic",
    nameAr: "عيادة حديثي الولادة",
    type: "clinic",
    specialty: "neonatology",
    department: "Women's Health",
    floor: "4th",
    building: "Women's Wing",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5744",
    contactEmail: "neonatology@husseiniya-health.com",
    notes: "Newborn care",
  },

  // ─── Diagnostic Services ─────────────────────────────────────────────
  {
    code: "LAB-CLINICAL",
    name: "Clinical Laboratory",
    nameAr: "المختبر الطبي",
    type: "lab",
    specialty: "clinical_laboratory",
    department: "Diagnostics",
    floor: "Ground",
    building: "Diagnostic Center",
    acceptsInsurance: true,
    insuranceProviders: [
      "اليمن للتأمين",
      "التأمين الصحي الشامل",
      "شركة التأمين اليمنية",
    ],
    operatingHours: { "sat-thu": "07:00-22:00", fri: "08:00-16:00" },
    contactPhone: "+967-1-234-5800",
    contactEmail: "lab@husseiniya-health.com",
    notes: "Full service clinical lab",
  },
  {
    code: "LAB-PATH",
    name: "Pathology Laboratory",
    nameAr: "مختبر الباثولوجيا",
    type: "lab",
    specialty: "pathology",
    department: "Diagnostics",
    floor: "2nd",
    building: "Diagnostic Center",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5801",
    contactEmail: "pathology@husseiniya-health.com",
    notes: "Histopathology and cytology",
  },
  {
    code: "LAB-MICRO",
    name: "Microbiology Laboratory",
    nameAr: "مختبر الأحياء الدقيقة",
    type: "lab",
    specialty: "microbiology",
    department: "Diagnostics",
    floor: "Ground",
    building: "Diagnostic Center",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "sat-thu": "07:00-20:00", fri: "08:00-14:00" },
    contactPhone: "+967-1-234-5802",
    contactEmail: "microbiology@husseiniya-health.com",
    notes: "Infectious disease testing",
  },
  {
    code: "LAB-BLOOD",
    name: "Blood Bank",
    nameAr: "بنك الدم",
    type: "lab",
    specialty: "transfusion_medicine",
    department: "Diagnostics",
    floor: "Ground",
    building: "Diagnostic Center",
    acceptsInsurance: true,
    insuranceProviders: [
      "اليمن للتأمين",
      "التأمين الصحي الشامل",
      "شركة التأمين اليمنية",
    ],
    operatingHours: { "0-6": "24 hours", "7-23": "24 hours" },
    contactPhone: "+967-1-234-5803",
    contactEmail: "bloodbank@husseiniya-health.com",
    notes: "Blood donation and transfusion services",
  },
  {
    code: "RAD-GENERAL",
    name: "General Radiology",
    nameAr: "الأشعة العامة",
    type: "radiology",
    specialty: "radiology",
    department: "Diagnostics",
    floor: "Ground",
    building: "Diagnostic Center",
    acceptsInsurance: true,
    insuranceProviders: [
      "اليمن للتأمين",
      "التأمين الصحي الشامل",
      "شركة التأمين اليمنية",
    ],
    operatingHours: { "sat-thu": "07:00-22:00", fri: "08:00-16:00" },
    contactPhone: "+967-1-234-5810",
    contactEmail: "radiology@husseiniya-health.com",
    notes: "X-ray and basic imaging",
  },
  {
    code: "RAD-CT",
    name: "CT Scan Center",
    nameAr: "مركز الأشعة المقطعية",
    type: "radiology",
    specialty: "ct_scan",
    department: "Diagnostics",
    floor: "Ground",
    building: "Diagnostic Center",
    acceptsInsurance: true,
    insuranceProviders: [
      "اليمن للتأمين",
      "التأمين الصحي الشامل",
      "شركة التأمين اليمنية",
    ],
    operatingHours: { "sat-thu": "07:00-22:00", fri: "08:00-18:00" },
    contactPhone: "+967-1-234-5811",
    contactEmail: "ctscan@husseiniya-health.com",
    notes: "64-slice CT scanner",
  },
  {
    code: "RAD-MRI",
    name: "MRI Center",
    nameAr: "مركز التصوير بالرنين المغناطيسي",
    type: "radiology",
    specialty: "mri",
    department: "Diagnostics",
    floor: "1st",
    building: "Diagnostic Center",
    acceptsInsurance: true,
    insuranceProviders: [
      "اليمن للتأمين",
      "التأمين الصحي الشامل",
      "شركة التأمين اليمنية",
    ],
    operatingHours: { "sat-thu": "07:00-22:00", fri: "08:00-18:00" },
    contactPhone: "+967-1-234-5812",
    contactEmail: "mri@husseiniya-health.com",
    notes: "1.5T MRI scanner",
  },
  {
    code: "RAD-ULTRASOUND",
    name: "Ultrasound Center",
    nameAr: "مركز الأشعة فوق الصوتية",
    type: "radiology",
    specialty: "ultrasound",
    department: "Diagnostics",
    floor: "Ground",
    building: "Diagnostic Center",
    acceptsInsurance: true,
    insuranceProviders: [
      "اليمن للتأمين",
      "التأمين الصحي الشامل",
      "شركة التأمين اليمنية",
    ],
    operatingHours: { "sat-thu": "07:00-22:00", fri: "08:00-16:00" },
    contactPhone: "+967-1-234-5813",
    contactEmail: "ultrasound@husseiniya-health.com",
    notes: "4D ultrasound services",
  },
  {
    code: "RAD-MAMMO",
    name: "Mammography Center",
    nameAr: "مركز تصوير الثدي",
    type: "radiology",
    specialty: "mammography",
    department: "Diagnostics",
    floor: "Ground",
    building: "Diagnostic Center",
    acceptsInsurance: true,
    insuranceProviders: [
      "اليمن للتأمين",
      "التأمين الصحي الشامل",
      "شركة التأمين اليمنية",
    ],
    operatingHours: { "sat-thu": "08:00-20:00", fri: "Closed" },
    contactPhone: "+967-1-234-5814",
    contactEmail: "mammography@husseiniya-health.com",
    notes: "Digital mammography",
  },
  {
    code: "RAD-NUCLEAR",
    name: "Nuclear Medicine Center",
    nameAr: "مركز الطب النووي",
    type: "radiology",
    specialty: "nuclear_medicine",
    department: "Diagnostics",
    floor: "2nd",
    building: "Diagnostic Center",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5815",
    contactEmail: "nuclear@husseiniya-health.com",
    notes: "PET-CT and nuclear imaging",
  },
  {
    code: "RAD-INTERV",
    name: "Interventional Radiology",
    nameAr: "الأشعة التداخلية",
    type: "radiology",
    specialty: "interventional_radiology",
    department: "Diagnostics",
    floor: "1st",
    building: "Surgical Building",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5816",
    contactEmail: "interventional@husseiniya-health.com",
    notes: "Minimally invasive procedures",
  },

  // ─── Pharmacy ─────────────────────────────────────────────────────────
  {
    code: "PHARM-MAIN",
    name: "Main Pharmacy",
    nameAr: "الصيدلية الرئيسية",
    type: "pharmacy",
    specialty: "pharmacy",
    department: "Pharmacy",
    floor: "Ground",
    building: "Main Building",
    acceptsInsurance: true,
    insuranceProviders: [
      "اليمن للتأمين",
      "التأمين الصحي الشامل",
      "شركة التأمين اليمنية",
    ],
    operatingHours: { "0-6": "24 hours", "7-23": "24 hours" },
    contactPhone: "+967-1-234-5900",
    contactEmail: "pharmacy@husseiniya-health.com",
    notes: "24/7 outpatient pharmacy",
  },
  {
    code: "PHARM-INPAT",
    name: "Inpatient Pharmacy",
    nameAr: "صيدلية المرضى الداخليين",
    type: "pharmacy",
    specialty: "clinical_pharmacy",
    department: "Pharmacy",
    floor: "2nd",
    building: "Main Building",
    acceptsInsurance: true,
    insuranceProviders: [
      "اليمن للتأمين",
      "التأمين الصحي الشامل",
      "شركة التأمين اليمنية",
    ],
    operatingHours: { "0-6": "24 hours", "7-23": "24 hours" },
    contactPhone: "+967-1-234-5901",
    contactEmail: "inpatientpharmacy@husseiniya-health.com",
    notes: "Ward pharmacy services",
  },
  {
    code: "PHARM-CHEMO",
    name: "Chemotherapy Pharmacy",
    nameAr: "صيدلية العلاج الكيميائي",
    type: "pharmacy",
    specialty: "oncology_pharmacy",
    department: "Cancer Center",
    floor: "3rd",
    building: "Cancer Center",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5902",
    contactEmail: "chemopharmacy@husseiniya-health.com",
    notes: "Oncology medications",
  },
  {
    code: "PHARM-IV",
    name: "IV Admixture Pharmacy",
    nameAr: "صيدلية تحضير الوريديات",
    type: "pharmacy",
    specialty: "sterile_compounding",
    department: "Pharmacy",
    floor: "Ground",
    building: "Main Building",
    acceptsInsurance: true,
    insuranceProviders: [
      "اليمن للتأمين",
      "التأمين الصحي الشامل",
      "شركة التأمين اليمنية",
    ],
    operatingHours: { "sat-thu": "07:00-20:00", fri: "08:00-16:00" },
    contactPhone: "+967-1-234-5903",
    contactEmail: "ivpharmacy@husseiniya-health.com",
    notes: "IV medication preparation",
  },

  // ─── Specialized Centers ────────────────────────────────────────────
  {
    code: "CENTER-DIALYSIS",
    name: "Dialysis Center",
    nameAr: "مركز الغسيل الكلوي",
    type: "clinic",
    specialty: "dialysis",
    department: "Nephrology",
    floor: "Ground",
    building: "Specialty Building",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: {
      "sat-thu": "06:00-22:00",
      fri: "06:00-18:00",
      sun: "06:00-14:00",
    },
    contactPhone: "+967-1-234-5750",
    contactEmail: "dialysis@husseiniya-health.com",
    notes: "30 dialysis stations",
  },
  {
    code: "CENTER-DIABETES",
    name: "Diabetes Center",
    nameAr: "مركز السكري",
    type: "clinic",
    specialty: "diabetology",
    department: "Endocrinology",
    floor: "1st",
    building: "Specialty Building",
    acceptsInsurance: true,
    insuranceProviders: [
      "اليمن للتأمين",
      "التأمين الصحي الشامل",
      "شركة التأمين اليمنية",
    ],
    operatingHours: { "sat-thu": "08:00-20:00", fri: "10:00-18:00" },
    contactPhone: "+967-1-234-5751",
    contactEmail: "diabetes@husseiniya-health.com",
    notes: "Comprehensive diabetes care",
  },
  {
    code: "CENTER-WOUND",
    name: "Wound Care Center",
    nameAr: "مركز علاج الجروح",
    type: "clinic",
    specialty: "wound_care",
    department: "Outpatient",
    floor: "Ground",
    building: "Outpatient Building",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5752",
    contactEmail: "woundcare@husseiniya-health.com",
    notes: "Chronic wound management",
  },
  {
    code: "CENTER-PAIN",
    name: "Pain Management Center",
    nameAr: "مركز علاج الألم",
    type: "clinic",
    specialty: "pain_management",
    department: "Anesthesiology",
    floor: "2nd",
    building: "Specialty Building",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5753",
    contactEmail: "painmanagement@husseiniya-health.com",
    notes: "Chronic pain treatment",
  },
  {
    code: "CENTER-REHAB",
    name: "Rehabilitation Center",
    nameAr: "مركز إعادة التأهيل",
    type: "clinic",
    specialty: "rehabilitation",
    department: "Rehabilitation",
    floor: "Ground",
    building: "Rehabilitation Center",
    acceptsInsurance: true,
    insuranceProviders: [
      "اليمن للتأمين",
      "التأمين الصحي الشامل",
      "شركة التأمين اليمنية",
    ],
    operatingHours: { "sat-thu": "07:00-20:00", fri: "08:00-16:00" },
    contactPhone: "+967-1-234-5754",
    contactEmail: "rehab@husseiniya-health.com",
    notes: "Physical and occupational therapy",
  },
  {
    code: "CENTER-SLEEP",
    name: "Sleep Disorders Center",
    nameAr: "مركز اضطرابات النوم",
    type: "clinic",
    specialty: "sleep_medicine",
    department: "Pulmonology",
    floor: "2nd",
    building: "Specialty Building",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5755",
    contactEmail: "sleep@husseiniya-health.com",
    notes: "Sleep study and treatment",
  },
  {
    code: "CENTER-LIVER",
    name: "Liver Center",
    nameAr: "مركز الكبد",
    type: "clinic",
    specialty: "hepatology",
    department: "Gastroenterology",
    floor: "2nd",
    building: "Specialty Building",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5756",
    contactEmail: "liver@husseiniya-health.com",
    notes: "Hepatitis and liver disease care",
  },
  {
    code: "CENTER-THALASSEMIA",
    name: "Thalassemia Center",
    nameAr: "مركز الثلاسيميا",
    type: "clinic",
    specialty: "hematology",
    department: "Hematology",
    floor: "2nd",
    building: "Specialty Building",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5757",
    contactEmail: "thalassemia@husseiniya-health.com",
    notes: "Thalassemia and hemoglobinopathy care",
  },

  // ─── Outpatient Procedures ───────────────────────────────────────────
  {
    code: "ENDO-GASTRO",
    name: "Gastroenterology Endoscopy",
    nameAr: "منظار الجهاز الهضمي",
    type: "clinic",
    specialty: "gastroenterology",
    department: "Gastroenterology",
    floor: "Ground",
    building: "Endoscopy Center",
    acceptsInsurance: true,
    insuranceProviders: [
      "اليمن للتأمين",
      "التأمين الصحي الشامل",
      "شركة التأمين اليمنية",
    ],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5760",
    contactEmail: "endoscopy@husseiniya-health.com",
    notes: "Gastroscopy and colonoscopy",
  },
  {
    code: "ENDO-BRONCHO",
    name: "Bronchoscopy Unit",
    nameAr: "وحدة تنظير القصبات",
    type: "clinic",
    specialty: "pulmonology",
    department: "Pulmonology",
    floor: "Ground",
    building: "Endoscopy Center",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5761",
    contactEmail: "bronchoscopy@husseiniya-health.com",
    notes: "Airway examination",
  },
  {
    code: "ENDO-ERCP",
    name: "ERCP Unit",
    nameAr: "وحدة التنظير العلاجي",
    type: "clinic",
    specialty: "gastroenterology",
    department: "Gastroenterology",
    floor: "1st",
    building: "Endoscopy Center",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5762",
    contactEmail: "ercp@husseiniya-health.com",
    notes: "Advanced biliary procedures",
  },
  {
    code: "CATH-LAB",
    name: "Cardiac Catheterization Lab",
    nameAr: "مختبر القسطرة القلبية",
    type: "hospital",
    specialty: "cardiology",
    department: "Cardiology Center",
    floor: "Ground",
    building: "Cardiac Center",
    acceptsInsurance: true,
    insuranceProviders: [
      "اليمن للتأمين",
      "التأمين الصحي الشامل",
      "شركة التأمين اليمنية",
    ],
    operatingHours: { "sat-thu": "07:00-22:00", fri: "08:00-18:00" },
    contactPhone: "+967-1-234-5763",
    contactEmail: "cathlab@husseiniya-health.com",
    notes: "Cardiac catheterization and angioplasty",
  },
  {
    code: "EMERG-CARDIO",
    name: "Chest Pain Center",
    nameAr: "مركز ألم الصدر",
    type: "hospital",
    specialty: "emergency_cardiology",
    department: "Emergency",
    floor: "Ground",
    building: "Main Building",
    acceptsInsurance: true,
    insuranceProviders: [
      "اليمن للتأمين",
      "التأمين الصحي الشامل",
      "شركة التأمين اليمنية",
    ],
    operatingHours: { "0-6": "24 hours", "7-23": "24 hours" },
    contactPhone: "+967-1-234-5764",
    contactEmail: "chestpain@husseiniya-health.com",
    notes: "24/7 heart attack care",
  },
  {
    code: "STROKE-UNIT",
    name: "Stroke Unit",
    nameAr: "وحدة السكتة الدماغية",
    type: "hospital",
    specialty: "stroke",
    department: "Neurology",
    floor: "2nd",
    building: "Main Building",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "0-6": "24 hours", "7-23": "24 hours" },
    contactPhone: "+967-1-234-5765",
    contactEmail: "stroke@husseiniya-health.com",
    notes: "Acute stroke treatment",
  },

  // ─── Allied Health ───────────────────────────────────────────────────
  {
    code: "ALLIED-DIET",
    name: "Dietetics & Nutrition Clinic",
    nameAr: "عيادة التغذية",
    type: "clinic",
    specialty: "dietetics",
    department: "Allied Health",
    floor: "Ground",
    building: "Outpatient Building",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5770",
    contactEmail: "dietetics@husseiniya-health.com",
    notes: "Nutritional counseling",
  },
  {
    code: "ALLIED-SPEECH",
    name: "Speech Therapy Clinic",
    nameAr: "عيادة علاج النطق",
    type: "clinic",
    specialty: "speech_therapy",
    department: "Rehabilitation",
    floor: "Ground",
    building: "Rehabilitation Center",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5771",
    contactEmail: "speech@husseiniya-health.com",
    notes: "Speech and language therapy",
  },
  {
    code: "ALLIED-AUDI",
    name: "Audiology Clinic",
    nameAr: "عيادة السمعيات",
    type: "clinic",
    specialty: "audiology",
    department: "ENT",
    floor: "Ground",
    building: "Outpatient Building",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5772",
    contactEmail: "audiology@husseiniya-health.com",
    notes: "Hearing tests and devices",
  },
  {
    code: "ALLIED-OCCUP",
    name: "Occupational Therapy Clinic",
    nameAr: "عيادة العلاج الوظيفي",
    type: "clinic",
    specialty: "occupational_therapy",
    department: "Rehabilitation",
    floor: "Ground",
    building: "Rehabilitation Center",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5773",
    contactEmail: "occupational@husseiniya-health.com",
    notes: "Occupational rehabilitation",
  },
  {
    code: "ALLIED-PHYST",
    name: "Physiotherapy Clinic",
    nameAr: "عيادة العلاج الطبيعي",
    type: "clinic",
    specialty: "physiotherapy",
    department: "Rehabilitation",
    floor: "Ground",
    building: "Rehabilitation Center",
    acceptsInsurance: true,
    insuranceProviders: [
      "اليمن للتأمين",
      "التأمين الصحي الشامل",
      "شركة التأمين اليمنية",
    ],
    operatingHours: { "sat-thu": "07:00-20:00", fri: "08:00-16:00" },
    contactPhone: "+967-1-234-5774",
    contactEmail: "physiotherapy@husseiniya-health.com",
    notes: "Physical therapy services",
  },
  {
    code: "ALLIED-PROSTH",
    name: "Prosthetics & Orthotics",
    nameAr: "الأطراف الصناعية والأطراف المساعدة",
    type: "clinic",
    specialty: "prosthetics",
    department: "Rehabilitation",
    floor: "Ground",
    building: "Rehabilitation Center",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للت التأمين", "التأمين الصحي الشامل"],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5775",
    contactEmail: "prosthetics@husseiniya-health.com",
    notes: "Artificial limbs and braces",
  },
  {
    code: "ALLIED-SOCIAL",
    name: "Medical Social Services",
    nameAr: "الخدمات الاجتماعية الطبية",
    type: "clinic",
    specialty: "social_work",
    department: "Allied Health",
    floor: "Ground",
    building: "Outpatient Building",
    acceptsInsurance: false,
    insuranceProviders: [],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5776",
    contactEmail: "socialwork@husseiniya-health.com",
    notes: "Patient support services",
  },
  {
    code: "ALLIED-GENETIC",
    name: "Genetic Counseling Clinic",
    nameAr: "عيادة الإرشاد الوراثي",
    type: "clinic",
    specialty: "genetics",
    department: "Diagnostics",
    floor: "2nd",
    building: "Specialty Building",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5777",
    contactEmail: "genetics@husseiniya-health.com",
    notes: "Genetic testing and counseling",
  },

  // ─── Support Services ─────────────────────────────────────────────────
  {
    code: "SUPPORT-EMSS",
    name: "Emergency Medical Services",
    nameAr: "الخدمات الطبية الطارئة",
    type: "hospital",
    specialty: "emergency_services",
    department: "Emergency",
    floor: "Ground",
    building: "Main Building",
    acceptsInsurance: true,
    insuranceProviders: [
      "اليمن للتأمين",
      "التأمين الصحي الشامل",
      "شركة التأمين اليمنية",
    ],
    operatingHours: { "0-6": "24 hours", "7-23": "24 hours" },
    contactPhone: "+967-1-234-5999",
    contactEmail: "ems@husseiniya-health.com",
    notes: "Ambulance and emergency response",
  },
  {
    code: "SUPPORT-HOME",
    name: "Home Healthcare Services",
    nameAr: "خدمات الرعاية المنزلية",
    type: "hospital",
    specialty: "home_healthcare",
    department: "Outpatient",
    floor: "Ground",
    building: "Outpatient Building",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "sat-thu": "08:00-20:00", fri: "10:00-18:00" },
    contactPhone: "+967-1-234-5998",
    contactEmail: "homecare@husseiniya-health.com",
    notes: "Home nursing and medical care",
  },
  {
    code: "SUPPORT-TELE",
    name: "Telemedicine Center",
    nameAr: "مركز الطب عن بُعد",
    type: "clinic",
    specialty: "telemedicine",
    department: "Outpatient",
    floor: "2nd",
    building: "Outpatient Building",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "sat-thu": "08:00-20:00", fri: "10:00-18:00" },
    contactPhone: "+967-1-234-5997",
    contactEmail: "telemedicine@husseiniya-health.com",
    notes: "Virtual consultations",
  },
  {
    code: "SUPPORT-MEDREC",
    name: "Medical Records Department",
    nameAr: "قسم السجلات الطبية",
    type: "hospital",
    specialty: "health_information",
    department: "Administration",
    floor: "1st",
    building: "Admin Building",
    acceptsInsurance: false,
    insuranceProviders: [],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5996",
    contactEmail: "medicalrecords@husseiniya-health.com",
    notes: "Health records management",
  },
  {
    code: "SUPPORT-BLOOD",
    name: "Blood Donation Center",
    nameAr: "مركز التبرع بالدم",
    type: "hospital",
    specialty: "blood_donation",
    department: "Diagnostics",
    floor: "Ground",
    building: "Diagnostic Center",
    acceptsInsurance: false,
    insuranceProviders: [],
    operatingHours: { "sat-thu": "08:00-20:00", fri: "10:00-18:00" },
    contactPhone: "+967-1-234-5995",
    contactEmail: "donation@husseiniya-health.com",
    notes: "Voluntary blood donation",
  },
  {
    code: "SUPPORT-HC",
    name: "Health Checkup Center",
    nameAr: "مركز الفحص الصحي",
    type: "clinic",
    specialty: "preventive_medicine",
    department: "Outpatient",
    floor: "Ground",
    building: "Outpatient Building",
    acceptsInsurance: true,
    insuranceProviders: [
      "اليمن للتأمين",
      "التأمين الصحي الشامل",
      "شركة التأمين اليمنية",
    ],
    operatingHours: { "sat-thu": "07:00-14:00", fri: "Closed" },
    contactPhone: "+967-1-234-5994",
    contactEmail: "healthcheckup@husseiniya-health.com",
    notes: "Executive and routine health checks",
  },
  {
    code: "SUPPORT-TRAVEL",
    name: "Travel Medicine Clinic",
    nameAr: "عيادة طب السفر",
    type: "clinic",
    specialty: "travel_medicine",
    department: "Outpatient",
    floor: "Ground",
    building: "Outpatient Building",
    acceptsInsurance: false,
    insuranceProviders: [],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5993",
    contactEmail: "travelmedicine@husseiniya-health.com",
    notes: "Travel vaccinations and advice",
  },
  {
    code: "SUPPORT-OCCUP",
    name: "Occupational Health Clinic",
    nameAr: "عيادة الصحة المهنية",
    type: "clinic",
    specialty: "occupational_health",
    department: "Outpatient",
    floor: "Ground",
    building: "Outpatient Building",
    acceptsInsurance: false,
    insuranceProviders: [],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5992",
    contactEmail: "occupationalhealth@husseiniya-health.com",
    notes: "Workplace health services",
  },
  {
    code: "SUPPORT-MEDEVAC",
    name: "Medical Evacuation Services",
    nameAr: "خدمات الإخلاء الطبي",
    type: "hospital",
    specialty: "medical_evaluation",
    department: "Emergency",
    floor: "Ground",
    building: "Main Building",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "0-6": "24 hours", "7-23": "24 hours" },
    contactPhone: "+967-1-234-5991",
    contactEmail: "medevac@husseiniya-health.com",
    notes: "International medical transfers",
  },
  {
    code: "SUPPORT-STOMA",
    name: "Stoma Care Clinic",
    nameAr: "عيادة رعاية الفغرة",
    type: "clinic",
    specialty: "stoma_care",
    department: "Surgery",
    floor: "Ground",
    building: "Outpatient Building",
    acceptsInsurance: true,
    insuranceProviders: ["اليمن للتأمين", "التأمين الصحي الشامل"],
    operatingHours: { "sat-thu": "08:00-16:00", fri: "Closed" },
    contactPhone: "+967-1-234-5990",
    contactEmail: "stomacare@husseiniya-health.com",
    notes: "Ostomy care and supplies",
  },
];
