import type { SeedProvider } from "./healthcareTenantData";

// Healthcare Providers - Realistic Yemeni & Arab Doctors with Valid Credentials
// Following Yemeni Medical Council and GCC licensing standards
export const healthcareProviders: SeedProvider[] = [
  // ─── General Practice & Family Medicine ──────────────────────────────
  {
    licenseNumber: "YEM-GP-001234",
    specialization: "general_practice",
    title: "Dr.",
    qualifications: ["MBBS", "Yemeni Board Family Medicine"],
    yearsExperience: 15,
    consultationFee: "5000",
    followUpFee: "3000",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CLINIC-GP",
    fullName: "Ahmad Mohammed Al-Husseini",
    fullNameAr: "أحمد محمد الحسيني",
    email: "a.alhusseini@husseiniya-health.com",
    phone: "+967-711-234-001",
  },
  {
    licenseNumber: "YEM-GP-001235",
    specialization: "general_practice",
    title: "Dr.",
    qualifications: ["MBBS", "MD Internal Medicine"],
    yearsExperience: 22,
    consultationFee: "7000",
    followUpFee: "4000",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CLINIC-GP",
    fullName: "Fatima Hassan Al-Sharabi",
    fullNameAr: "فاطمة حسن الشربعي",
    email: "f.alsharabi@husseiniya-health.com",
    phone: "+967-711-234-002",
  },
  {
    licenseNumber: "YEM-FM-002001",
    specialization: "family_medicine",
    title: "Dr.",
    qualifications: ["MBBS", "Arab Board Family Medicine", "FMCFM"],
    yearsExperience: 18,
    consultationFee: "8000",
    followUpFee: "5000",
    scheduleTemplate: { "sat-thu": "08:00-20:00" },
    facilityCode: "CLINIC-FAMILY",
    fullName: "Khaled Abdullah Al-Amiri",
    fullNameAr: "خالد عبدالله العامري",
    email: "k.aamiri@husseiniya-health.com",
    phone: "+967-711-234-003",
  },
  {
    licenseNumber: "YEM-FM-002002",
    specialization: "family_medicine",
    title: "Dr.",
    qualifications: ["MBBS", "Arab Board Family Medicine"],
    yearsExperience: 10,
    consultationFee: "6000",
    followUpFee: "3500",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CLINIC-FAMILY",
    fullName: "Mariam Saeed Al-Maqtari",
    fullNameAr: "مريم سعيد المقطري",
    email: "m.almaqtari@husseiniya-health.com",
    phone: "+967-711-234-004",
  },

  // ─── Internal Medicine ──────────────────────────────────────────────
  {
    licenseNumber: "YEM-IM-003001",
    specialization: "internal_medicine",
    title: "Dr.",
    qualifications: ["MBBS", "MD Internal Medicine", "MRCP UK"],
    yearsExperience: 25,
    consultationFee: "15000",
    followUpFee: "8000",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CLINIC-IM",
    fullName: "Yahia Ali Al-Zaidi",
    fullNameAr: "يحيى علي الزيدي",
    email: "y.alzaidi@husseiniya-health.com",
    phone: "+967-711-234-005",
  },
  {
    licenseNumber: "YEM-IM-003002",
    specialization: "internal_medicine",
    title: "Dr.",
    qualifications: ["MBBS", "Arab Board Internal Medicine", "MRCP Ireland"],
    yearsExperience: 18,
    consultationFee: "12000",
    followUpFee: "7000",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CLINIC-IM",
    fullName: "Amina Taha Al-Hamdani",
    fullNameAr: "أمينة طه الحمداني",
    email: "a.alhamdani@husseiniya-health.com",
    phone: "+967-711-234-006",
  },

  // ─── Cardiology ─────────────────────────────────────────────────────
  {
    licenseNumber: "YEM-CD-004001",
    specialization: "cardiology",
    title: "Dr.",
    qualifications: ["MBBS", "MD Cardiology", "FRCP London"],
    yearsExperience: 28,
    consultationFee: "25000",
    followUpFee: "15000",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CLINIC-CARDIO",
    fullName: "Saleh Mohammed Al-Bakri",
    fullNameAr: "صالح محمد البكري",
    email: "s.albakri@husseiniya-health.com",
    phone: "+967-711-234-007",
  },
  {
    licenseNumber: "YEM-CD-004002",
    specialization: "cardiology",
    title: "Dr.",
    qualifications: ["MBBS", "Arab Board Cardiology", "FACC"],
    yearsExperience: 15,
    consultationFee: "18000",
    followUpFee: "10000",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CLINIC-CARDIO",
    fullName: "Hanan Abdulrahman Al-Mahdi",
    fullNameAr: "حنان عبدالرحمن المهدي",
    email: "h.almahdi@husseiniya-health.com",
    phone: "+967-711-234-008",
  },
  {
    licenseNumber: "YEM-CD-004003",
    specialization: "interventional_cardiology",
    title: "Dr.",
    qualifications: [
      "MBBS",
      "MD Cardiology",
      "Fellowship Interventional Cardiology USA",
    ],
    yearsExperience: 20,
    consultationFee: "30000",
    followUpFee: "18000",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CATH-LAB",
    fullName: "Mohammed Naser Al-Sharabi",
    fullNameAr: "محمد ناصر الشربعي",
    email: "m.alsharabi@husseiniya-health.com",
    phone: "+967-711-234-009",
  },

  // ─── Neurology ─────────────────────────────────────────────────────
  {
    licenseNumber: "YEM-NU-005001",
    specialization: "neurology",
    title: "Dr.",
    qualifications: ["MBBS", "MD Neurology", "European Board Neurology"],
    yearsExperience: 22,
    consultationFee: "20000",
    followUpFee: "12000",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CLINIC-NEURO",
    fullName: "Abdul Karim Ali Al-Shami",
    fullNameAr: "عبدالكريم علي الشامعي",
    email: "a.alshami@husseiniya-health.com",
    phone: "+967-711-234-010",
  },
  {
    licenseNumber: "YEM-NU-005002",
    specialization: "neurology",
    title: "Dr.",
    qualifications: ["MBBS", "Arab Board Neurology"],
    yearsExperience: 12,
    consultationFee: "15000",
    followUpFee: "9000",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CLINIC-NEURO",
    fullName: "Sana Hassan Al-Rawhani",
    fullNameAr: "سناء حسن الروحاني",
    email: "s.alrawhani@husseiniya-health.com",
    phone: "+967-711-234-011",
  },
  {
    licenseNumber: "YEM-NS-005101",
    specialization: "neurosurgery",
    title: "Dr.",
    qualifications: ["MBBS", "MD Neurosurgery", "Fellowship UK"],
    yearsExperience: 25,
    consultationFee: "30000",
    followUpFee: "18000",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CLINIC-NEUROSURG",
    fullName: "Omar Salim Al-Maqtari",
    fullNameAr: "عمر سالم المقطري",
    email: "o.almaqtari@husseiniya-health.com",
    phone: "+967-711-234-012",
  },

  // ─── Gastroenterology ──────────────────────────────────────────────
  {
    licenseNumber: "YEM-GE-006001",
    specialization: "gastroenterology",
    title: "Dr.",
    qualifications: ["MBBS", "MD Gastroenterology", "European Board"],
    yearsExperience: 20,
    consultationFee: "18000",
    followUpFee: "10000",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CLINIC-GASTRO",
    fullName: "Nabil Ahmed Al-Ansi",
    fullNameAr: "نبيل أحمد العنسي",
    email: "n.alansi@husseiniya-health.com",
    phone: "+967-711-234-013",
  },
  {
    licenseNumber: "YEM-GE-006002",
    specialization: "hepatology",
    title: "Dr.",
    qualifications: [
      "MBBS",
      "MD Internal Medicine",
      "Fellowship Hepatology Egypt",
    ],
    yearsExperience: 16,
    consultationFee: "16000",
    followUpFee: "9500",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CENTER-LIVER",
    fullName: "Rana Yasser Al-Jawfi",
    fullNameAr: "رنا ياسر الجوفي",
    email: "r.aljawfi@husseiniya-health.com",
    phone: "+967-711-234-014",
  },

  // ─── Nephrology ─────────────────────────────────────────────────────
  {
    licenseNumber: "YEM-NP-007001",
    specialization: "nephrology",
    title: "Dr.",
    qualifications: ["MBBS", "MD Nephrology", "European Board Nephrology"],
    yearsExperience: 22,
    consultationFee: "18000",
    followUpFee: "10000",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CLINIC-NEPHRO",
    fullName: "Faisal Hassan Al-Kohlani",
    fullNameAr: "فيصل حسن الكحلاني",
    email: "f.alkohlani@husseiniya-health.com",
    phone: "+967-711-234-015",
  },
  {
    licenseNumber: "YEM-NP-007002",
    specialization: "nephrology",
    title: "Dr.",
    qualifications: ["MBBS", "Arab Board Nephrology"],
    yearsExperience: 14,
    consultationFee: "14000",
    followUpFee: "8000",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CENTER-DIALYSIS",
    fullName: "Wafa Ali Al-Houthi",
    fullNameAr: "وفاء علي الحوتي",
    email: "w.alhouthi@husseiniya-health.com",
    phone: "+967-711-234-016",
  },

  // ─── Endocrinology & Diabetes ─────────────────────────────────────
  {
    licenseNumber: "YEM-EN-008001",
    specialization: "endocrinology",
    title: "Dr.",
    qualifications: ["MBBS", "MD Endocrinology", "MRCP UK"],
    yearsExperience: 19,
    consultationFee: "18000",
    followUpFee: "10000",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CLINIC-ENDO",
    fullName: "Tariq Mohammed Al-Sharjabi",
    fullNameAr: "طارق محمد الشرجبي",
    email: "t.alsharjabi@husseiniya-health.com",
    phone: "+967-711-234-017",
  },
  {
    licenseNumber: "YEM-EN-008002",
    specialization: "diabetology",
    title: "Dr.",
    qualifications: ["MBBS", "Arab Board Endocrinology"],
    yearsExperience: 12,
    consultationFee: "15000",
    followUpFee: "9000",
    scheduleTemplate: { "sat-thu": "08:00-20:00" },
    facilityCode: "CENTER-DIABETES",
    fullName: "Lubna Khaled Al-Mahdali",
    fullNameAr: "لبنى خالد المهدلي",
    email: "l.almahdali@husseiniya-health.com",
    phone: "+967-711-234-018",
  },

  // ─── Pulmonology ────────────────────────────────────────────────────
  {
    licenseNumber: "YEM-PU-009001",
    specialization: "pulmonology",
    title: "Dr.",
    qualifications: ["MBBS", "MD Pulmonology", "European Board"],
    yearsExperience: 17,
    consultationFee: "16000",
    followUpFee: "9500",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CLINIC-PULMO",
    fullName: "Adel Hussein Al-Rawe",
    fullNameAr: "عادل حسين الرويعي",
    email: "a.alrawe@husseiniya-health.com",
    phone: "+967-711-234-019",
  },

  // ─── Rheumatology ───────────────────────────────────────────────────
  {
    licenseNumber: "YEM-RH-010001",
    specialization: "rheumatology",
    title: "Dr.",
    qualifications: ["MBBS", "MD Rheumatology", "MRCP UK"],
    yearsExperience: 15,
    consultationFee: "16000",
    followUpFee: "9000",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CLINIC-RHEUM",
    fullName: "Zainab Mohammed Al-Attas",
    fullNameAr: "زينب محمد العطاس",
    email: "z.alattas@husseiniya-health.com",
    phone: "+967-711-234-020",
  },

  // ─── Dermatology ────────────────────────────────────────────────────
  {
    licenseNumber: "YEM-DE-011001",
    specialization: "dermatology",
    title: "Dr.",
    qualifications: ["MBBS", "MD Dermatology", "European Board Dermatology"],
    yearsExperience: 18,
    consultationFee: "15000",
    followUpFee: "9000",
    scheduleTemplate: { "sat-thu": "08:00-20:00" },
    facilityCode: "CLINIC-DERMA",
    fullName: "Mona Ali Al-Khaledy",
    fullNameAr: "منى علي الخالدي",
    email: "m.alkhaledy@husseiniya-health.com",
    phone: "+967-711-234-021",
  },
  {
    licenseNumber: "YEM-DE-011002",
    specialization: "dermatology",
    title: "Dr.",
    qualifications: ["MBBS", "Arab Board Dermatology"],
    yearsExperience: 11,
    consultationFee: "12000",
    followUpFee: "7000",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CLINIC-DERMA",
    fullName: "Salem Nasser Al-Ghaili",
    fullNameAr: "سالم ناصر الغيلي",
    email: "s.algaili@husseiniya-health.com",
    phone: "+967-711-234-022",
  },

  // ─── Allergy ───────────────────────────────────────────────────────
  {
    licenseNumber: "YEM-AL-012001",
    specialization: "allergy",
    title: "Dr.",
    qualifications: [
      "MBBS",
      "MD Internal Medicine",
      "Fellowship Allergy & Immunology",
    ],
    yearsExperience: 13,
    consultationFee: "14000",
    followUpFee: "8500",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CLINIC-ALLERGY",
    fullName: "Ibrahim Hassan Al-Shami",
    fullNameAr: "إبراهيم حسن الشامعي",
    email: "i.alshami@husseiniya-health.com",
    phone: "+967-711-234-023",
  },

  // ─── Infectious Diseases ──────────────────────────────────────────
  {
    licenseNumber: "YEM-ID-013001",
    specialization: "infectious_diseases",
    title: "Dr.",
    qualifications: ["MBBS", "MD Infectious Diseases", "European Board"],
    yearsExperience: 16,
    consultationFee: "16000",
    followUpFee: "9500",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CLINIC-INFEC",
    fullName: "Hassan Mohammed Al-Wazeer",
    fullNameAr: "حسن محمد الوزير",
    email: "h.alwazeer@husseiniya-health.com",
    phone: "+967-711-234-024",
  },

  // ─── Oncology ───────────────────────────────────────────────────────
  {
    licenseNumber: "YEM-ON-014001",
    specialization: "oncology",
    title: "Dr.",
    qualifications: ["MBBS", "MD Oncology", "European Board Medical Oncology"],
    yearsExperience: 22,
    consultationFee: "25000",
    followUpFee: "15000",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CLINIC-ONCO",
    fullName: "Anwar Ali Al-Sabri",
    fullNameAr: "أنور علي الصبري",
    email: "a.alsabri@husseiniya-health.com",
    phone: "+967-711-234-025",
  },
  {
    licenseNumber: "YEM-ON-014002",
    specialization: "hematology",
    title: "Dr.",
    qualifications: ["MBBS", "MD Hematology", "MRCP UK"],
    yearsExperience: 17,
    consultationFee: "20000",
    followUpFee: "12000",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CLINIC-HEMA",
    fullName: "Layla Saeed Al-Mahdi",
    fullNameAr: "ليلى سعيد المهدي",
    email: "l.almahdi@husseiniya-health.com",
    phone: "+967-711-234-026",
  },

  // ─── Psychiatry ────────────────────────────────────────────────────
  {
    licenseNumber: "YEM-PS-015001",
    specialization: "psychiatry",
    title: "Dr.",
    qualifications: ["MBBS", "MD Psychiatry", "Arab Board Psychiatry"],
    yearsExperience: 20,
    consultationFee: "18000",
    followUpFee: "10000",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CLINIC-PSYCH",
    fullName: "Khaled Mohammed Al-Kamish",
    fullNameAr: "خالد محمد الكامش",
    email: "k.alkamish@husseiniya-health.com",
    phone: "+967-711-234-027",
  },
  {
    licenseNumber: "YEM-PS-015002",
    specialization: "psychology",
    title: "Dr.",
    qualifications: [
      "PhD Clinical Psychology",
      "Post-doc Cognitive Behavioral Therapy",
    ],
    yearsExperience: 12,
    consultationFee: "12000",
    followUpFee: "8000",
    scheduleTemplate: { "sat-thu": "09:00-17:00" },
    facilityCode: "CLINIC-PSYCHO",
    fullName: "Aisha Ahmed Al-Maqtari",
    fullNameAr: "عائشة أحمد المقطري",
    email: "a.almaqtari@husseiniya-health.com",
    phone: "+967-711-234-028",
  },

  // ─── Surgical Specialties ──────────────────────────────────────────
  {
    licenseNumber: "YEM-SU-016001",
    specialization: "general_surgery",
    title: "Dr.",
    qualifications: ["MBBS", "MD General Surgery", "FRCS Edinburgh"],
    yearsExperience: 25,
    consultationFee: "20000",
    followUpFee: "12000",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CLINIC-GENSURG",
    fullName: "Mohammed Ali Al-Maqtari",
    fullNameAr: "محمد علي المقطري",
    email: "m.almaqtari@husseiniya-health.com",
    phone: "+967-711-234-029",
  },
  {
    licenseNumber: "YEM-SU-016002",
    specialization: "general_surgery",
    title: "Dr.",
    qualifications: ["MBBS", "Arab Board General Surgery"],
    yearsExperience: 15,
    consultationFee: "15000",
    followUpFee: "9000",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CLINIC-GENSURG",
    fullName: "Yasser Abdullah Al-Khaledi",
    fullNameAr: "ياسر عبدالله الخالدي",
    email: "y.alkhaledi@husseiniya-health.com",
    phone: "+967-711-234-030",
  },
  {
    licenseNumber: "YEM-VS-016101",
    specialization: "vascular_surgery",
    title: "Dr.",
    qualifications: ["MBBS", "MD Vascular Surgery", "FRCS England"],
    yearsExperience: 18,
    consultationFee: "22000",
    followUpFee: "13000",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CLINIC-VASC",
    fullName: "Saeed Mohammed Al-Haj",
    fullNameAr: "سعيد محمد الحاج",
    email: "s.alhaj@husseiniya-health.com",
    phone: "+967-711-234-031",
  },
  {
    licenseNumber: "YEM-OR-016201",
    specialization: "orthopedics",
    title: "Dr.",
    qualifications: ["MBBS", "MD Orthopedics", "FRCS Ortho"],
    yearsExperience: 20,
    consultationFee: "20000",
    followUpFee: "12000",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CLINIC-ORTHO",
    fullName: "Ali Mohammed Al-Amiri",
    fullNameAr: "علي محمد العامري",
    email: "a.aamiri@husseiniya-health.com",
    phone: "+967-711-234-032",
  },
  {
    licenseNumber: "YEM-OR-016202",
    specialization: "orthopedics",
    title: "Dr.",
    qualifications: ["MBBS", "Arab Board Orthopedics"],
    yearsExperience: 14,
    consultationFee: "16000",
    followUpFee: "9500",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CLINIC-ORTHO",
    fullName: "Nasser Ali Al-Husseini",
    fullNameAr: "ناصر علي الحسيني",
    email: "n.alhusseini@husseiniya-health.com",
    phone: "+967-711-234-033",
  },
  {
    licenseNumber: "YEM-EN-016301",
    specialization: "otolaryngology",
    title: "Dr.",
    qualifications: ["MBBS", "MD ENT", "Arab Board ENT"],
    yearsExperience: 17,
    consultationFee: "16000",
    followUpFee: "9500",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CLINIC-OTOLO",
    fullName: "Mohammed Saeed Al-Hamdani",
    fullNameAr: "محمد سعيد الحمداني",
    email: "m.alhamdani@husseiniya-health.com",
    phone: "+967-711-234-034",
  },
  {
    licenseNumber: "YEM-OP-016401",
    specialization: "ophthalmology",
    title: "Dr.",
    qualifications: ["MBBS", "MD Ophthalmology", "FRCS Glasgow"],
    yearsExperience: 19,
    consultationFee: "18000",
    followUpFee: "10000",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CLINIC-OPHTH",
    fullName: "Abdulrahman Ali Al-Sayed",
    fullNameAr: "عبدالرحمن علي السيد",
    email: "a.alsayed@husseiniya-health.com",
    phone: "+967-711-234-035",
  },
  {
    licenseNumber: "YEM-UR-016501",
    specialization: "urology",
    title: "Dr.",
    qualifications: ["MBBS", "MD Urology", "Arab Board Urology"],
    yearsExperience: 16,
    consultationFee: "18000",
    followUpFee: "10000",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CLINIC-URO",
    fullName: "Hassan Mohammed Al-Maqtari",
    fullNameAr: "حسن محمد المقطري",
    email: "h.almaqtari@husseiniya-health.com",
    phone: "+967-711-234-036",
  },
  {
    licenseNumber: "YEM-PS-016601",
    specialization: "plastic_surgery",
    title: "Dr.",
    qualifications: ["MBBS", "MD Plastic Surgery", "Fellowship USA"],
    yearsExperience: 15,
    consultationFee: "30000",
    followUpFee: "15000",
    scheduleTemplate: { "sat-thu": "09:00-17:00" },
    facilityCode: "CLINIC-PLAST",
    fullName: "Mohammed Ali Al-Sayani",
    fullNameAr: "محمد علي السياني",
    email: "m.alsayani@husseiniya-health.com",
    phone: "+967-711-234-037",
  },
  {
    licenseNumber: "YEM-CTS-016701",
    specialization: "cardiothoracic_surgery",
    title: "Dr.",
    qualifications: ["MBBS", "MD Cardiothoracic Surgery", "FRCS England"],
    yearsExperience: 22,
    consultationFee: "35000",
    followUpFee: "20000",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CLINIC-CARDIOVASC",
    fullName: "Faisal Mohammed Al-Saqqaf",
    fullNameAr: "فيصل محمد السقاف",
    email: "f.alsaqqaf@husseiniya-health.com",
    phone: "+967-711-234-038",
  },

  // ─── OB/GYN ─────────────────────────────────────────────────────────
  {
    licenseNumber: "YEM-OG-017001",
    specialization: "obstetrics_gynecology",
    title: "Dr.",
    qualifications: ["MBBS", "MD OB/GYN", "Arab Board OB/GYN"],
    yearsExperience: 22,
    consultationFee: "18000",
    followUpFee: "10000",
    scheduleTemplate: { "sat-thu": "08:00-20:00" },
    facilityCode: "CLINIC-OBGYN",
    fullName: "Samiya Ali Al-Khaledi",
    fullNameAr: "سامية علي الخالدي",
    email: "s.alkhaledi@husseiniya-health.com",
    phone: "+967-711-234-039",
  },
  {
    licenseNumber: "YEM-OG-017002",
    specialization: "obstetrics_gynecology",
    title: "Dr.",
    qualifications: ["MBBS", "Arab Board OB/GYN", "MRCOG UK"],
    yearsExperience: 18,
    consultationFee: "20000",
    followUpFee: "12000",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CLINIC-OBGYN",
    fullName: "Nawal Mohammed Al-Maqtari",
    fullNameAr: "نوال محمد المقطري",
    email: "n.almaqtari@husseiniya-health.com",
    phone: "+967-711-234-040",
  },
  {
    licenseNumber: "YEM-RM-017101",
    specialization: "reproductive_medicine",
    title: "Dr.",
    qualifications: [
      "MBBS",
      "MD OB/GYN",
      "Fellowship Reproductive Medicine UK",
    ],
    yearsExperience: 15,
    consultationFee: "25000",
    followUpFee: "15000",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CLINIC-IVF",
    fullName: "Hala Abdullah Al-Mahdi",
    fullNameAr: "هالة عبدالله المهدي",
    email: "h.almahdi@husseiniya-health.com",
    phone: "+967-711-234-041",
  },
  {
    licenseNumber: "YEM-BH-017201",
    specialization: "breast_surgery",
    title: "Dr.",
    qualifications: [
      "MBBS",
      "MD General Surgery",
      "Fellowship Breast Surgery UK",
    ],
    yearsExperience: 16,
    consultationFee: "20000",
    followUpFee: "12000",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CLINIC-MAMMO",
    fullName: "Eman Ali Al-Sabahi",
    fullNameAr: "إيمان علي الصباحي",
    email: "e.alsabahi@husseiniya-health.com",
    phone: "+967-711-234-042",
  },

  // ─── Pediatrics ─────────────────────────────────────────────────────
  {
    licenseNumber: "YEM-PE-018001",
    specialization: "pediatrics",
    title: "Dr.",
    qualifications: ["MBBS", "MD Pediatrics", "MRCPCH UK"],
    yearsExperience: 20,
    consultationFee: "15000",
    followUpFee: "9000",
    scheduleTemplate: { "sat-thu": "08:00-20:00" },
    facilityCode: "CLINIC-PED",
    fullName: "Aisha Mohammed Al-Mahdi",
    fullNameAr: "عائشة محمد المهدي",
    email: "a.almahdi@husseiniya-health.com",
    phone: "+967-711-234-043",
  },
  {
    licenseNumber: "YEM-PE-018002",
    specialization: "pediatrics",
    title: "Dr.",
    qualifications: ["MBBS", "Arab Board Pediatrics"],
    yearsExperience: 12,
    consultationFee: "12000",
    followUpFee: "7000",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CLINIC-PED",
    fullName: "Ahmed Ali Al-Sharjabi",
    fullNameAr: "أحمد علي الشرجبي",
    email: "a.alsharjabi@husseiniya-health.com",
    phone: "+967-711-234-044",
  },
  {
    licenseNumber: "YEM-PN-018101",
    specialization: "pediatric_nephrology",
    title: "Dr.",
    qualifications: [
      "MBBS",
      "MD Pediatrics",
      "Fellowship Pediatric Nephrology",
    ],
    yearsExperience: 13,
    consultationFee: "16000",
    followUpFee: "9500",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CLINIC-PEDNEPHO",
    fullName: "Faten Hassan Al-Maqtari",
    fullNameAr: "فاتن حسن المقطري",
    email: "f.almaqtari@husseiniya-health.com",
    phone: "+967-711-234-045",
  },
  {
    licenseNumber: "YEM-PC-018201",
    specialization: "pediatric_cardiology",
    title: "Dr.",
    qualifications: [
      "MBBS",
      "MD Pediatrics",
      "Fellowship Pediatric Cardiology UK",
    ],
    yearsExperience: 15,
    consultationFee: "18000",
    followUpFee: "10000",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CLINIC-PEDCARDIO",
    fullName: "Sameer Ali Al-Khaledi",
    fullNameAr: "سمير علي الخالدي",
    email: "s.alkhaledi@husseiniya-health.com",
    phone: "+967-711-234-046",
  },
  {
    licenseNumber: "YEM-DP-018301",
    specialization: "developmental_pediatrics",
    title: "Dr.",
    qualifications: [
      "MBBS",
      "MD Pediatrics",
      "Fellowship Developmental Pediatrics",
    ],
    yearsExperience: 14,
    consultationFee: "16000",
    followUpFee: "9000",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CLINIC-PEDDEV",
    fullName: "Reem Abdullah Al-Shami",
    fullNameAr: "ريم عبدالله الشامعي",
    email: "r.alshami@husseiniya-health.com",
    phone: "+967-711-234-047",
  },
  {
    licenseNumber: "YEM-NN-018401",
    specialization: "neonatology",
    title: "Dr.",
    qualifications: ["MBBS", "MD Pediatrics", "Fellowship Neonatology"],
    yearsExperience: 18,
    consultationFee: "18000",
    followUpFee: "10000",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CLINIC-NEONAT",
    fullName: "Ahmed Hassan Al-Sharabi",
    fullNameAr: "أحمد حسن الشربعي",
    email: "a.alsharabi@husseiniya-health.com",
    phone: "+967-711-234-048",
  },

  // ─── Pathology & Laboratory Medicine ────────────────────────────────
  {
    licenseNumber: "YEM-PA-019001",
    specialization: "pathology",
    title: "Dr.",
    qualifications: ["MBBS", "MD Pathology", "Arab Board Pathology"],
    yearsExperience: 22,
    consultationFee: "0",
    followUpFee: "0",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "LAB-PATH",
    fullName: "Mohammed Ali Al-Sabahi",
    fullNameAr: "محمد علي الصباحي",
    email: "m.alsabahi@husseiniya-health.com",
    phone: "+967-711-234-049",
  },
  {
    licenseNumber: "YEM-MI-019101",
    specialization: "microbiology",
    title: "Dr.",
    qualifications: ["MBBS", "MD Microbiology", "European Board"],
    yearsExperience: 17,
    consultationFee: "0",
    followUpFee: "0",
    scheduleTemplate: { "sat-thu": "07:00-20:00" },
    facilityCode: "LAB-MICRO",
    fullName: "Sami Ali Al-Kohlani",
    fullNameAr: "سامي علي الكحلاني",
    email: "s.alkohlani@husseiniya-health.com",
    phone: "+967-711-234-050",
  },

  // ─── Radiology ──────────────────────────────────────────────────────
  {
    licenseNumber: "YEM-RA-020001",
    specialization: "radiology",
    title: "Dr.",
    qualifications: ["MBBS", "MD Radiology", "European Board Radiology"],
    yearsExperience: 20,
    consultationFee: "0",
    followUpFee: "0",
    scheduleTemplate: { "sat-thu": "07:00-22:00" },
    facilityCode: "RAD-GENERAL",
    fullName: "Tarek Mohammed Al-Mahdali",
    fullNameAr: "طارق محمد المهدلي",
    email: "t.almahdali@husseiniya-health.com",
    phone: "+967-711-234-051",
  },
  {
    licenseNumber: "YEM-IR-020101",
    specialization: "interventional_radiology",
    title: "Dr.",
    qualifications: [
      "MBBS",
      "MD Radiology",
      "Fellowship Interventional Radiology",
    ],
    yearsExperience: 16,
    consultationFee: "0",
    followUpFee: "0",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "RAD-INTERV",
    fullName: "Basel Ali Al-Hamdani",
    fullNameAr: "باسل علي الحمداني",
    email: "b.alhamdani@husseiniya-health.com",
    phone: "+967-711-234-052",
  },
  {
    licenseNumber: "YEM-NM-020201",
    specialization: "nuclear_medicine",
    title: "Dr.",
    qualifications: ["MBBS", "MD Nuclear Medicine", "European Board"],
    yearsExperience: 15,
    consultationFee: "0",
    followUpFee: "0",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "RAD-NUCLEAR",
    fullName: "Nadia Ali Al-Mahdi",
    fullNameAr: "نادية علي المهدي",
    email: "n.almahdi@husseiniya-health.com",
    phone: "+967-711-234-053",
  },

  // ─── Pharmacy (Pharmacists) ─────────────────────────────────────────
  {
    licenseNumber: "YEM-PH-021001",
    specialization: "clinical_pharmacy",
    title: "PharmD",
    qualifications: ["PharmD", "BCPS"],
    yearsExperience: 15,
    consultationFee: "0",
    followUpFee: "0",
    scheduleTemplate: { "0-6": "24 hours" },
    facilityCode: "PHARM-INPAT",
    fullName: "Ahmed Mohammed Al-Shami",
    fullNameAr: "أحمد محمد الشامعي",
    email: "a.alshami@husseiniya-health.com",
    phone: "+967-711-234-054",
  },
  {
    licenseNumber: "YEM-PH-021002",
    specialization: "oncology_pharmacy",
    title: "PharmD",
    qualifications: ["PharmD", "BCOP"],
    yearsExperience: 12,
    consultationFee: "0",
    followUpFee: "0",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "PHARM-CHEMO",
    fullName: "Mariam Ali Al-Husseini",
    fullNameAr: "مريم علي الحسيني",
    email: "m.alhusseini@husseiniya-health.com",
    phone: "+967-711-234-055",
  },

  // ─── Anesthesia & Pain ───────────────────────────────────────────────
  {
    licenseNumber: "YEM-AN-022001",
    specialization: "anesthesiology",
    title: "Dr.",
    qualifications: ["MBBS", "MD Anesthesiology", "Arab Board Anesthesia"],
    yearsExperience: 18,
    consultationFee: "0",
    followUpFee: "0",
    scheduleTemplate: { "0-6": "24 hours" },
    facilityCode: "HOSP-OR",
    fullName: "Walid Mohammed Al-Sharabi",
    fullNameAr: "وليد محمد الشربعي",
    email: "w.alsharabi@husseiniya-health.com",
    phone: "+967-711-234-056",
  },
  {
    licenseNumber: "YEM-PM-022101",
    specialization: "pain_management",
    title: "Dr.",
    qualifications: ["MBBS", "MD Anesthesiology", "Fellowship Pain Medicine"],
    yearsExperience: 14,
    consultationFee: "16000",
    followUpFee: "9500",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CENTER-PAIN",
    fullName: "Mahmoud Ali Al-Maqtari",
    fullNameAr: "محمود علي المقطري",
    email: "m.almaqtari@husseiniya-health.com",
    phone: "+967-711-234-057",
  },

  // ─── Emergency Medicine ─────────────────────────────────────────────
  {
    licenseNumber: "YEM-EM-023001",
    specialization: "emergency_medicine",
    title: "Dr.",
    qualifications: ["MBBS", "MD Emergency Medicine", "Arab Board Emergency"],
    yearsExperience: 14,
    consultationFee: "10000",
    followUpFee: "0",
    scheduleTemplate: { "0-6": "24 hours" },
    facilityCode: "HOSP-ER",
    fullName: "Fawaz Ali Al-Shami",
    fullNameAr: "فواز علي الشامعي",
    email: "f.alshami@husseiniya-health.com",
    phone: "+967-711-234-058",
  },
  {
    licenseNumber: "YEM-EM-023002",
    specialization: "emergency_medicine",
    title: "Dr.",
    qualifications: ["MBBS", "MD Emergency Medicine"],
    yearsExperience: 10,
    consultationFee: "8000",
    followUpFee: "0",
    scheduleTemplate: { "0-6": "24 hours" },
    facilityCode: "HOSP-ER",
    fullName: "Tasneem Mohammed Al-Mahdi",
    fullNameAr: "تسنيم محمد المهدي",
    email: "t.almahdi@husseiniya-health.com",
    phone: "+967-711-234-059",
  },

  // ─── ICU/Critical Care ──────────────────────────────────────────────
  {
    licenseNumber: "YEM-CC-024001",
    specialization: "critical_care",
    title: "Dr.",
    qualifications: [
      "MBBS",
      "MD Anesthesiology",
      "Fellowship Critical Care UK",
    ],
    yearsExperience: 16,
    consultationFee: "0",
    followUpFee: "0",
    scheduleTemplate: { "0-6": "24 hours" },
    facilityCode: "HOSP-ICU",
    fullName: "Walid Abdullah Al-Mahdali",
    fullNameAr: "وليد عبدالله المهدلي",
    email: "w.almahdali@husseiniya-health.com",
    phone: "+967-711-234-060",
  },

  // ─── Rehabilitation Medicine ────────────────────────────────────────
  {
    licenseNumber: "YEM-RM-025001",
    specialization: "rehabilitation",
    title: "Dr.",
    qualifications: ["MBBS", "MD Physical Medicine & Rehabilitation"],
    yearsExperience: 13,
    consultationFee: "14000",
    followUpFee: "8000",
    scheduleTemplate: { "sat-thu": "07:00-20:00" },
    facilityCode: "CENTER-REHAB",
    fullName: "Yousef Hassan Al-Mahdi",
    fullNameAr: "يوسف حسن المهدي",
    email: "y.almahdi@husseiniya-health.com",
    phone: "+967-711-234-061",
  },
  {
    licenseNumber: "YEM-PT-025101",
    specialization: "physiotherapy",
    title: "Dr.",
    qualifications: ["BSc Physiotherapy", "MSc Sports Physiotherapy"],
    yearsExperience: 10,
    consultationFee: "8000",
    followUpFee: "5000",
    scheduleTemplate: { "sat-thu": "07:00-20:00" },
    facilityCode: "ALLIED-PHYST",
    fullName: "Khalil Ali Al-Sharabi",
    fullNameAr: "خليل علي الشربعي",
    email: "k.alsharabi@husseiniya-health.com",
    phone: "+967-711-234-062",
  },
  {
    licenseNumber: "YEM-OT-025201",
    specialization: "occupational_therapy",
    title: "Dr.",
    qualifications: ["BSc Occupational Therapy", "MSc Rehabilitation"],
    yearsExperience: 8,
    consultationFee: "8000",
    followUpFee: "5000",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "ALLIED-OCCUP",
    fullName: "Aya Ali Al-Mahdi",
    fullNameAr: "آية علي المهدي",
    email: "a.almahdi@husseiniya-health.com",
    phone: "+967-711-234-063",
  },
  {
    licenseNumber: "YEM-ST-025301",
    specialization: "speech_therapy",
    title: "Dr.",
    qualifications: ["MSc Speech Language Pathology"],
    yearsExperience: 7,
    consultationFee: "10000",
    followUpFee: "6000",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "ALLIED-SPEECH",
    fullName: "Heba Mohammed Al-Khaledi",
    fullNameAr: "هبة محمد الخالدي",
    email: "h.alkhaledi@husseiniya-health.com",
    phone: "+967-711-234-064",
  },
  {
    licenseNumber: "YEM-AU-025401",
    specialization: "audiology",
    title: "Dr.",
    qualifications: ["MSc Audiology", "PhD Hearing Sciences"],
    yearsExperience: 11,
    consultationFee: "10000",
    followUpFee: "6000",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "ALLIED-AUDI",
    fullName: "Ahmed Ali Al-Mahdi",
    fullNameAr: "أحمد علي المهدي",
    email: "a.almahdi@husseiniya-health.com",
    phone: "+967-711-234-065",
  },

  // ─── Nutrition & Dietetics ───────────────────────────────────────────
  {
    licenseNumber: "YEM-DT-026001",
    specialization: "dietetics",
    title: "Dr.",
    qualifications: [
      "BSc Nutrition",
      "MSc Clinical Nutrition",
      "PhD Nutrition",
    ],
    yearsExperience: 9,
    consultationFee: "8000",
    followUpFee: "5000",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "ALLIED-DIET",
    fullName: "Shatha Ali Al-Mahdi",
    fullNameAr: "شذى علي المهدي",
    email: "s.almahdi@husseiniya-health.com",
    phone: "+967-711-234-066",
  },

  // ─── Sleep Medicine ──────────────────────────────────────────────────
  {
    licenseNumber: "YEM-SM-027001",
    specialization: "sleep_medicine",
    title: "Dr.",
    qualifications: ["MBBS", "MD Pulmonology", "Fellowship Sleep Medicine"],
    yearsExperience: 12,
    consultationFee: "15000",
    followUpFee: "9000",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CENTER-SLEEP",
    fullName: "Yasser Mohammed Al-Shami",
    fullNameAr: "ياسر محمد الشامعي",
    email: "y.alshami@husseiniya-health.com",
    phone: "+967-711-234-067",
  },

  // ─── Hematology - Thalassemia ───────────────────────────────────────
  {
    licenseNumber: "YEM-HT-028001",
    specialization: "hematology",
    title: "Dr.",
    qualifications: ["MBBS", "MD Hematology", "Fellowship Thalassemia Italy"],
    yearsExperience: 16,
    consultationFee: "18000",
    followUpFee: "10000",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CENTER-THALASSEMIA",
    fullName: "Mohammed Ali Al-Hamdani",
    fullNameAr: "محمد علي الحمداني",
    email: "m.alhamdani@husseiniya-health.com",
    phone: "+967-711-234-068",
  },

  // ─── Genetics ────────────────────────────────────────────────────────
  {
    licenseNumber: "YEM-GE-029001",
    specialization: "genetics",
    title: "Dr.",
    qualifications: ["MBBS", "PhD Genetics", "European Board Medical Genetics"],
    yearsExperience: 14,
    consultationFee: "18000",
    followUpFee: "10000",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "ALLIED-GENETIC",
    fullName: "Sarah Ali Al-Khaledi",
    fullNameAr: "سارة علي الخالدي",
    email: "s.alkhaledi@husseiniya-health.com",
    phone: "+967-711-234-069",
  },

  // ─── Wound Care ──────────────────────────────────────────────────────
  {
    licenseNumber: "YEM-WC-030001",
    specialization: "wound_care",
    title: "Dr.",
    qualifications: ["MBBS", "MD General Surgery", "Fellowship Wound Care UK"],
    yearsExperience: 12,
    consultationFee: "12000",
    followUpFee: "7000",
    scheduleTemplate: { "sat-thu": "08:00-16:00" },
    facilityCode: "CENTER-WOUND",
    fullName: "Ahmed Mohammed Al-Sharabi",
    fullNameAr: "أحمد محمد الشربعي",
    email: "a.alsharabi@husseiniya-health.com",
    phone: "+967-711-234-070",
  },
];
